### ISSUE TITLE
Implement REST API for using ForestDB

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-java-core#1005]
- [ ]  REST API for selecting Storage Engine to use

- [ ]  REST API for configuring database encryption

#https://github.com/couchbase/couchbase-lite-java-listener/issues/63
#https://github.com/fraserxu/react-native-couchbase-lite/issues/16

**Comment by snej** [comment]
We should do some API design for this, just like with a native API, and implement it consistently across platforms. I've filed some issues in the API repo.

**Comment by hideki** [comment]
This Request should be handled by #1444 (storage type) and #1445 (encryption key)
