### ISSUE TITLE
Changes feed api and other api calls never recover in case of low connectivity

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1006]
I've attached the thread dump zip along with a few Chrome debugging screenshots. The application we tested uses the Cordova plugin (Listener to fetch the data and replications). After decreasing the connectivity, some calls to the Listener are kept in a pending state. We found that the UI thread was also blocked. So it could be the Android OS that suspends all threads.

**Comment by hideki** [comment]
Hi @jamiltz,  does this happen only with PhoneGap plugin? or independent from phonegap?

**Comment by jamiltz** [comment]
I was able to freeze the UI on a similar Android app that uses the Listener as well but with a native UI. I'm  not sure if the PhoneGap plugin has anything related to this unfortunately.

**Comment by hideki** [comment]
Hi @jamiltz,

Can you look into #976? Is this same issue with #976?

Thanks!

**Comment by jamiltz** [comment]
Additional logs from today's testing.

[logs.zip](https://github.com/couchbase/couchbase-lite-java-core/files/124743/logs.zip)

**Comment by hideki** [comment]
I believe this is duplicate with #1026. Close this.
