### ISSUE TITLE
External property on database change event

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1008]
See https://github.com/couchbase/couchbase-lite-ios/issues/1100.
The same applies on java core.

**Comment by hideki** [comment]
Notes to Self:

Tested this issue with using LiteServ and GrocerySync

##### Observation:
- In case GrocerySync pull a doc from LiteServ, ChangeEvent in GrocerySync has isExternal=true and source points to local database (GrocerySync database).
- In case GrocerySync push a doc to LiteServ, ChangeEvent in LiteServ has isExternal=false and source points to local database (LiteServ database).

##### Notes:
- Second case, `isExternal` property value should be true.
- Java version does not have URL field in `Database.ChangeEvent`. And `source` field always points to local database. With current API, Java version can not point to Remote URL for source property.

**Comment by hideki** [comment]
After discussed this at sprint-planning,  we take care only isExternal with ticket.

@zack will figure out if we need to support `URL` as `source` in `Database.ChangeEvent`.

**Comment by zack** [comment]
@hideki :) wrong zack. someone who should have been notified may not have been.

**Comment by hideki** [comment]
@zack Thank you for letting us know.
