### ISSUE TITLE
Requests to Listener in pending state

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1030]
I've not been able to reproduce this issue consistently yet but have seen it occurring a few times. To try to do it, I'm using the app at https://github.com/jamiltz/P2PSync-Android.

It happens when querying multiple endpoints on the changes feed (and perhaps writing to the db at the same time but I'm not sure).

I will do more tests tomorrow to try to reproduce consistently.

**Comment by jamiltz** [comment]
Note: when it occurs, any HTTP request to the Listener will be in pending state and the server is hanging.

**Comment by pasin** [comment]
@jamiltz, is it possible to run the listener on the android or simulator attached to the android studio in debug mode while reproducing the issue? If possible, can you use Android studio's device monitor to capture all the thread backtrace while the dead lock is happening? With the backtrace of all threads, we may be able to identify where the deadlock is.

**Comment by pasin** [comment]
Maybe debug mode might not be necessary to capture the backtrace.

**Comment by jamiltz** [comment]
Here's the thread backtrace from a test I did last week when the listener was hanging.

[thread_pool.txt](https://github.com/couchbase/couchbase-lite-java-core/files/129194/thread_pool.txt)

**Comment by hideki** [comment]
simplified version of above thread dump:
https://gist.github.com/hideki/1b8783b909774a5ee1a0

First thread hangs in Router.start(), second one might wait for 1st thread, then following 16 threads are blocked at Line 127 because 1st thread does not exit from synchronized block.

**Comment by hideki** [comment]
First thread hangs at https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/router/Router.java#L186-L187

This `InputStream` is originally from `Socket`: https://github.com/drogatkin/TJWS2/blob/master/1.x/src/Acme/Serve/Serve.java#L1960

I assume this could happen under non-stable network environment. And this could be recovered if recoverable or could throw IOException if network error is detected.

To avoid dead-lock entire REST APIs, we should not synchronize with Manager instance in Servlet
```java
synchronized (manager) {
   router.start();
}
```

**Comment by jamiltz** [comment]
Another thread dump: https://gist.github.com/jamiltz/4e69cd8bc294950bb09d

**Comment by jamiltz** [comment]
In testing the fixes in a harsh environment with lots of interference and low connectivity the listener will sometimes enter the "hanging state" where all HTTP requests are pending (it's happening less often since the fixes merged in this issue but can still be observed). Here are the details of testing with build 596:

Logs: https://gist.github.com/jamiltz/2d8f49f682c5d7ab2d53
Thread dump: https://gist.github.com/jamiltz/a2eabefeb9e26e9c9461

**Comment by hideki** [comment]
From Thread-dump, I can not observe any dead-lock. None of threads unexpectedly became waiting (blocked) state or blocking state.

With discussion with @jamiltz, It seems TJWS connection setting and replicator retry frequency might cause the problem under unstable Wifi environment.

Following changes might solve:
- set DEFAULT_SO_TIMEOUT_SECONDS to 30sec (currently 20sec)
- apply same timeout setting to [DEFAULT_CONNECTION_TIMEOUT_SECONDS]  (https://github.com/couchbase/couchbase-lite-java-core/blob/f7f1cd4320f66d77bcd796cad7b0939fe0c53838/src/main/java/com/couchbase/lite/support/CouchbaseLiteHttpClientFactory.java#L45)
- set `ARG_KEEPALIVE_TIMEOUT` value to `1` as suggested in https://github.com/couchbase/couchbase-lite-java-listener/issues/40 During our conversation, I suggested to switch back to default value 30sec. I might not make sense.

**Comment by jamiltz** [comment]
Thread dump with `ARG_KEEPALIVE_TIMEOUT` set to 1 on slave device https://gist.github.com/jamiltz/1b74a748c94fd606058f

**Comment by NitzDKoder** [comment]
@hideki 
Test environment is make to many network transitions(unstable) and i end with
