### ISSUE TITLE
Proxy setting on Android blocks access to Listener

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1037]
Steps to reproduce:

- Enable a proxy setting in the network tab of the Android Wifi panel -> http://cl.ly/070J1u133W16/a7xeltexxLMY47Xjamesnocentini02152016224058.png

- Then the "Unable to connect to the proxy server" page is displayed for http://localhost:5984 -> http://cl.ly/0x0D031X3r0m/a7xeltexxLMY47Xjamesnocentini02152016222339.png

The workaround is to add `localhost` in the "Bypass proxy for" section in the proxy settings.

Is there a way that the Listener could automatically enable this? Maybe something similar to how couchbase-lite-ios does it by using an internal URL only accessible within the app.

**Comment by hideki** [comment]
@jamiltz,

As WebView (browser), which is used from PhoneGap, can not reach to localhost:5984, it is not Listener issue.

User might be able to set Proxy setting by them self with following  samples.
- http://stackoverflow.com/questions/12486441/how-can-i-set-proxysettings-and-proxyproperties-on-android-wi-fi-connection-usin
- http://grepcode.com/file/repo1.maven.org/maven2/org.robolectric/android-all/5.0.0_r2-robolectric-0/android/net/ProxyInfo.java
- http://grepcode.com/file/repo1.maven.org/maven2/org.robolectric/android-all/5.0.0_r2-robolectric-0/android/net/ProxyInfo.java

**Comment by hideki** [comment]
@jamiltz, Can we close this ticket? Please let us know.

**Comment by jamiltz** [comment]
Yes sure. Thanks for the links!
