### ISSUE TITLE
Support POST /_changes in Listener

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1054]
From my understanding, the replicators communicate with sync_gateway via POST and I think iOS also supports this on the Listener. On Android, it would be nice to allow unified communication with the _changes endpoint via POST.

**Comment by hideki** [comment]
https://github.com/couchbase/couchbase-lite-ios/pull/1110/files

**Comment by hideki** [comment]
See #1188
