### ISSUE TITLE
cbforest master branch version fails with many unit test (1.2.0-java -> master)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1057]
It is compilable, but fails many unit tests.

![screen shot 2016-02-19 at 5 58 14 pm](https://cloud.githubusercontent.com/assets/15889/13193729/7b8ff6a8-d732-11e5-95e0-cd6f55b71b41.png)

**Comment by zgramana** [comment]
@snej please review with @hideki

**Comment by snej** [comment]
What are the errors? Does it look like one type of problem or several different ones?

If you have some unit tests for the Java binding of the C4 API (without Couchbase Lite), we can try to move them into CBForest and set it up to run them without having to have a full Java/Android IDE; that way I could do it when I make changes to C4.

**Comment by zgramana** [comment]
@snej lets get you setup with Android Studio so you run them with a debugger attached.

**Comment by hideki** [comment]
Latest master of cbforest can pass cbforest java wrapper level unit tests which were ported from cbforest Objective-C test. https://github.com/couchbaselabs/couchbase-lite-java-forestdb/tree/master/src/androidTest/java/com/couchbase/cbforest

I will work for this issue.

**Comment by hideki** [comment]
Issue was solved by cbforest PR: https://github.com/couchbaselabs/cbforest/pull/80
