### ISSUE TITLE
Pull replication skipped documents

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1068]
Similar outcome to #1047 but the scenario is different and it happens on pull replications.

_Scenario:_

- 1 master device and 5 slaves. The slaves are running the Listener and master is pushing/pulling with each one (10 continuous replications in total).
- Switch the WiFi off on each slave device.
- Add 20 docs on each slave device.
- Bring back all the slave devices online at the same time.

_Result:_ The doc count on master is below the expected value (it should be = previous doc count + 100). All replications are still syncing documents after the initial catch-up but the doc counts don't match.
_Expected:_ The doc count on every device to be the previous doc count + 100.

It seems that in this case the pull replications are skipping documents.

**Comment by jamiltz** [comment]
Adding logs/thread dump of master device:
Logs https://gist.github.com/jamiltz/830335d7693103a4c250
Thread dump https://gist.github.com/jamiltz/b40814dd0360b2778c82

And same for slave device:
Logs https://gist.github.com/jamiltz/919d45590e8de2dd8c65
Thread dump https://gist.github.com/jamiltz/70fc1001f8fc1e34f103

**Comment by hideki** [comment]
Note to self:

From thread-dump master:
- 4 ChangeTrackers are running: It should be 5. 
- Observed 4 CBLPusherInternalExecutor threads: It should be 5.
- Two out of all replicators are still processing. Actually batcher is sleeping. There is another network error??
- Observed 45 CBLRequestWorker threads: It should be 50 if 10 repls are running. or 40 if 8 repls are running (because of 4 active pull repls and 4 active push repls)

```
master

"CBLRequestWorker-5ed49-1@23800" prio=5 runnable
	at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182)

From thread dump - 4 change tracker is running. 
http://172.23.8.27:5984/ek0073@23793
http://172.23.8.25:5984/ek0073@23795
http://172.23.8.22:5984/ek0073@23809
http://172.23.8.24:5984/ek0073@23789

Acme.Utils.ThreadPool(1)
Acme.Utils.ThreadPool(5)

Thread-2295@23756" prio=5 waiting
	at com.couchbase.lite.support.RemoteRequestRetry.get(RemoteRequestRetry.java:339)
"Thread-2296@23757" prio=5 waiting
"Thread-2300@23758" prio=5 waiting
"Thread-2298@23759" prio=5 waiting
"Thread-2302@23760" prio=5 waiting
"Thread-15624@23761" prio=5 waiting
"Thread-15657@23762" prio=5 waiting
"Thread-15730@23763" prio=5 waiting
"Thread-18918@23771" prio=5 waiting
"Thread-26430@23772" prio=5 waiting
"Thread-26428@23773" prio=5 waiting
"Thread-26434@23774" prio=5 waiting
"Thread-26436@23775" prio=5 waiting
"Thread-26489@23776" prio=5 waiting
"Thread-33856@23777" prio=5 waiting
"Thread-36637@23782" prio=5 waiting
"Thread-36639@23783" prio=5 waiting
"Thread-36641@23784" prio=5 waiting
"Thread-39018@23838" prio=5 waiting

"CBLManagerWorkExecutor@23754" prio=5 waiting

"CBLRequestWorker-87d18-0@23764" prio=5 waiting
"CBLRequestWorker-87d18-1@23765" prio=5 waiting
"CBLRequestWorker-87d18-2@23766" prio=5 waiting
"CBLRequestWorker-87d18-3@23767" prio=5 waiting
"CBLRequestWorker-87d18-4@23768" prio=5 waiting

"CBLRequestWorker-5ed49-0@23785" prio=5 waiting
see above
"CBLRequestWorker-5ed49-2@23805" prio=5 waiting
"CBLRequestWorker-5ed49-3@23814" prio=5 waiting
"CBLRequestWorker-5ed49-4@23816" prio=5 waiting

"CBLRequestWorker-a6e67-0@23786" prio=5 waiting
"CBLRequestWorker-a6e67-1@23803" prio=5 waiting
"CBLRequestWorker-a6e67-2@23826" prio=5 waiting
"CBLRequestWorker-a6e67-3@23830" prio=5 waiting
"CBLRequestWorker-a6e67-4@23834" prio=5 waiting

"CBLRequestWorker-491a2-0@23787" prio=5 waiting
"CBLRequestWorker-491a2-1@23801" prio=5 waiting
"CBLRequestWorker-491a2-2@23806" prio=5 waiting
"CBLRequestWorker-491a2-3@23813" prio=5 waiting
"CBLRequestWorker-491a2-4@23815" prio=5 waiting

"CBLRequestWorker-857d8-0@23791" prio=5 waiting
"CBLRequestWorker-857d8-1@23802" prio=5 waiting
"CBLRequestWorker-857d8-2@23804" prio=5 waiting
"CBLRequestWorker-857d8-3@23818" prio=5 waiting
"CBLRequestWorker-857d8-4@23820" prio=5 waiting

"CBLRequestWorker-ed898-0@23792" prio=5 waiting
"CBLRequestWorker-ed898-1@23827" prio=5 waiting
"CBLRequestWorker-ed898-2@23831" prio=5 waiting
"CBLRequestWorker-ed898-3@23835" prio=5 waiting
"CBLRequestWorker-ed898-4@23836" prio=5 waiting

"CBLRequestWorker-d5e5c-0@23807" prio=5 waiting
"CBLRequestWorker-d5e5c-1@23810" prio=5 waiting
"CBLRequestWorker-d5e5c-2@23812" prio=5 waiting
"CBLRequestWorker-d5e5c-3@23817" prio=5 waiting
"CBLRequestWorker-d5e5c-4@23819" prio=5 waiting

"CBLRequestWorker-ea2a4-0@23808" prio=5 waiting
"CBLRequestWorker-ea2a4-1@23822" prio=5 waiting
"CBLRequestWorker-ea2a4-2@23823" prio=5 waiting
"CBLRequestWorker-ea2a4-3@23825" prio=5 waiting
"CBLRequestWorker-ea2a4-4@23829" prio=5 waiting

"CBLRequestWorker-22a6c-0@23788" prio=5 waiting
"CBLRequestWorker-22a6c-1@23824" prio=5 waiting
"CBLRequestWorker-22a6c-2@23828" prio=5 waiting
"CBLRequestWorker-22a6c-3@23832" prio=5 waiting
"CBLRequestWorker-22a6c-4@23833" prio=5 waiting



"CBLPusherInternalExecutor-41@23797" prio=9 waiting
"CBLPusherInternalExecutor-42@23798" prio=9 waiting
"CBLPusherInternalExecutor-43@23799" prio=9 waiting
"CBLPusherInternalExecutor-44@23821" prio=5 waiting

"Thread-39031@23706" prio=5 sleeping
	at com.couchbase.lite.replicator.ReplicationInternal.waitBatcherCompleted(ReplicationInternal.java:1785)
"Thread-39032@23708" prio=5 sleeping
```

**Comment by hideki** [comment]
@jamiltz,

##### Notes from thread-dump and log files

- [Thread-dump from master](https://gist.github.com/jamiltz/b40814dd0360b2778c82#file-thread-dump-master-L1-L32) indicates still one of replicator is RUNNING state. Actually the thread was waiting response from listener. There is possibility network issue happened with one slave device. Or network is really slow.

##### Notes from code review
- [waitForAllTasksCompleted()](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L994-L1009): There is possibility exits from `waitForAllTasksCompleted()` method before pull replication tasks are completed. And set IDLE state to continuous pull replicator. I assume this wrong replicator state does not cause skipping document. But needs to investigate.

**Comment by hideki** [comment]
Request to @jamiltz 
Next time encounter the issue, can you ask them to call /_active_tasks REST API to check replication progress on master device? http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/rest-api/server/get-active-tasks/index.html
