### ISSUE TITLE
Deleting database and stopping replications at the same time

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1069]
Intermittent issue. I'm currently simultaneously deleting the database and stopping all replications at the same time and sometimes the call to DELETE /db doesn't return. However, making the same call 20/30 seconds later returns instantly.

Logs: https://gist.github.com/jamiltz/35ec4c60f18a27450f68

Search for "Delete DB [object Object]". It appears twice in the logs. First at `17:00:07` and then at `17:00:20`. The user clicked on logout button a second time 13 seconds later. The second time the button was clicked the DELETE /db request returned instantly.

**Comment by hideki** [comment]
It seems there are some STOPPED notification missing because of multi-thread issue
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L1278-L1319
