### ISSUE TITLE
Impossible to get non-reduced view from CBL Listener

### ISSUE THREAD

**Issue by Poundex** [couchbase/couchbase-lite-java-core#1082]
In `com.couchbase.lite.router.Router` the `reduce` property of the `QueryOptions` is set correctly from the query parameters of the HTTP request. 
However, because the `reduceSpecified` property is never set, then because of the logic in `com.couchbase.lite.View::groupOrReduce` then the `reduce` property is ignored and if a reduce function is present then it is always used, regardless of the request, meaning that for any view that has a reduce function it is never possible to get a non-reduced view

**Comment by hideki** [comment]
Missing following line to be ported.
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Router.m#L201
