### ISSUE TITLE
LiteServ app for Java

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1087]
It would be great to have a command lite utility app to start the Listener. Flags could be passed to perform different tasks (https://github.com/couchbase/couchbase-lite-ios/blob/master/Listener/LiteServ.m#L165-L181).

**Comment by hideki** [comment]
Note to Self:

ATTN: @sethrosetter 

Implementing LiteServ for Java and operating [mobile-testkit](https://github.com/couchbaselabs/mobile-testkit) on all three platforms (Windows, Linux and OSX) could find issue like [sqlcipher.dll missing on windows](https://forums.couchbase.com/t/issue-in-pull-replication-for-couchbase-lite-java/10119/5). Need higher priority for this task.

**Comment by sethrosetter** [comment]
@hideki @michaelkwok We need to add this to CI as part of closedown of this task.
