### ISSUE TITLE
Possible bug in PhoneGap Android, but not iOS reported by user

### ISSUE THREAD

**Issue by nraboy** [couchbase/couchbase-lite-java-core#1094]
This is related to the following:

http://blog.couchbase.com/using-couchbase-in-your-ionic-framework-application-part-1#comment-2557540255

> Android 4.1.2. I'm deploying on device using ionic build android -> ionic run android.
> 
> However, if it helps, I ran it in ios emulator and it works.

A few others are reporting the same.

**Comment by hideki** [comment]
Hi @nraboy,
Could you please provide details of this issue?
Thanks!

**Comment by nraboy** [comment]
The details were in the comments:

<img width="1084" alt="screen shot 2016-03-09 at 9 24 27 am" src="https://cloud.githubusercontent.com/assets/983958/13644087/c9f2f16a-e5d8-11e5-9238-51dfa367bfa9.png">

**Comment by zgramana** [comment]
@pasin do you mind taking a look at this?

**Comment by nraboy** [comment]
Just reviewed the blog comments.  Nothing new has been reported.  Posted a follow up response in the comments of the blog article.

Best,

**Comment by pasin** [comment]
The status code = 0 is weird. From the Router.java, I guessed that `openDB()` method returned status code = 0 however I couldn't see how that can happen.

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.2.0/src/main/java/com/couchbase/lite/router/Router.java#L389-L398

**Comment by pasin** [comment]
@nraboy it would be really helpful, if the user can provide the exception from the log cat. I guessed there should be one.
