### ISSUE TITLE
`ReplicationInternal.stop()` always return immediately

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1115]
`ReplicationInternal.stop()` is called after stateMachine became `STOPPING` state, so the method returns immediately.

`ReplicationInternal.stop()`
```
    protected void stop() {
        if (!isRunning())
            return;
```
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java#L1092-L1094

**Comment by pasin** [comment]
Close as the ticket got opened as #1158.
