### ISSUE TITLE
[Scenario 1] Pusher missing docs: Potential race condition when calling PusherInternal.removePending()

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1129]
PusherInternal.removePending() could be called from request workers which could be more than one threads at the same time. This might cause an issue with setting last sequence and result to skipping docs.

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PusherInternal.java#L393-L492

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PusherInternal.java#L521-L561

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PusherInternal.java#L387

**Comment by hideki** [comment]
With 5 RemoteRequest threads, followings are not thread-safe.
- `pendingSequences`
- `maxPendingSequence`

Following two local variable might not be accurate.
- `wasFirst` could be not accurate
- `maxCompleted` could be not accurate

**Comment by pasin** [comment]
This could be fixed by just synchronize `addPending()` and `removePending() `method on the `PusherInternal` class.
