### ISSUE TITLE
Listener returns incorrect version string for dev builds

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1153]
```
curl http://localhost:5984
```
returns something similar to "0.0.0--1" for dev build 0.0.0-635. I would expect it to return "0.0.0-635". 

This would be also useful in Jenkins to verify what version we are targeting in the build logs

**Comment by hideki** [comment]
duplicated with https://github.com/couchbase/couchbase-lite-java-listener/issues/68
