### ISSUE TITLE
Replication.stop() sometimes fails to stop pull replication

### ISSUE THREAD

**Issue by 4u7** [couchbase/couchbase-lite-java-core#1157]
Sometimes when `Replication.stop()` is called replication never goes to stopped state, but all work is actually stopped. This behavior is caused by lock in `Batcher.waitForPendingFutures()`. I’ve found that after `Replication.stop()` is called `PullerInternal.waitForAllTasksCompleted()` called two times from two different threads and one of them occasionally may never return. First one is called in `PullerInternal.stop()` and second one from `ReplicationInternal.waitForPendingFutures()` when change tracker is stopped.

If second one returns and first one hangs, replication never becomes stopped.
If first one returns and second one hangs, replication becomes stopped, but one thread is still waiting forever.

Problem is in `Batcher.waitForPendingFutures()` in line `mutex.wait();` one of the threads never gets notified.

```java
ScheduledFuture future;
synchronized (mutex) {
    while (!inbox.isEmpty()) {
        try {
            Log.v(Log.TAG_BATCHER, "%s: waitForPendingFutures, inbox size: %d",
                    this, inbox.size());
            mutex.wait();
        } catch (InterruptedException e) {}
    }
    future = pendingFuture;
}
```
I fixed that by calling wait with minimal timeout `mutex.wait(1);` But I’m not sure that it is the optimal way to fix this issue.

This issue may be related to #1141

**Comment by 4u7** [comment]
Added some logs to investigate this issue here 8e1098c08f09232814dabed8b54caeeb2f16b04a. Filter out `waitForAllTasksCompleted` and you will see something like this:
```
03-24 16:12:17.392 19599-21213/r V/Sync: PullerInternal calling waitForAllTasksCompleted()...
03-24 16:12:17.402 19599-21214/r V/Sync: ReplicationInternal calling waitForAllTasksCompleted()...
03-24 16:12:18.952 19599-21214/r V/Sync: ReplicationInternal waitForAllTasksCompleted() returned!
``` 
As you can see one of `waitForAllTasksCompleted()` never returned.

**Comment by hideki** [comment]
related with #1141

**Comment by hideki** [comment]
Hi @4u7, 
Thank you very much for your analysis. 
I'd like to know which version of Couchbase Lite you are using? 1.2.0? or build from master branch?
Thanks!
Hideki

**Comment by hideki** [comment]
Hi @4u7,
Again, Thank you very much for finding this bug and your analysis!
Thanks!

**Comment by 4u7** [comment]
Hi @hideki,
I'm glad i could help. Thank you for maintaining this great project!
