### ISSUE TITLE
No peer certificate on https.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1209]
Hi folks,
Server/f5 has go daddy secure certificate authority sh2 certificate installed.
Cbl throws below error in android devices
![screenshot_2016-04-20-22-30-22-1](https://cloud.githubusercontent.com/assets/1461456/14684118/e3fad39a-074b-11e6-80a9-2fd34f0fdb7d.png)
.

```
04/20 01:30:23.146] [3] RemoteRequest: io exception.  url: https://f5fqdn:443/dbdata/_session
javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
```

Generally Apache HTTPClient should do server certificate validation with device inbuilt certificates isn't?

We have f5 proxy server in middle..What could be the issue here?
Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

This solution, https://github.com/couchbase/couchbase-lite-android/issues/116, might help you.

**Comment by hideki** [comment]
@NitzDKoder Do you have any update about this?

**Comment by NitzDKoder** [comment]
@hideki CBL was  able to do server certificate validation/SSL/HTTPS with **Symantec SHA2 certificate**. We are still investigating why  it failed on "**Go daddy secure certificate authority sh2** "..will update on this..

**Comment by hideki** [comment]
Hi @NitzDKoder,
Do you have any update for this ticket?
If no more update, I'd like to close this ticket.
Thanks!

**Comment by NitzDKoder** [comment]
You can close now..will check with new okHttp build and update..

**Comment by NitzDKoder** [comment]
@hideki 
Apache httpclient is been used.

https://bsyncgw.stgpttplus.com:443/pttdata

We have issues in 4.4 and minus android devices.(Android Browser fails too).
But 5.0 plus devices works well..

ssllabs labs passes SSL the same in all devices of android..
https://www.ssllabs.com/ssltest/analyze.html?d=bsyncgw.stgpttplus.com

Any hints on this issues?

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

I guess following stackoverflow answer gives you hints.
http://stackoverflow.com/questions/2642777/trusting-all-certificates-using-httpclient-over-https

To avoid your problem with 4.x or lower android device, you might implement SSLSocketFactory. Some of users use this technique to solve self-signed certificate issue.
Hints in following ticket might also help you 
https://github.com/couchbase/couchbase-lite-java-core/issues/330

Thanks!
