### ISSUE TITLE
Listener ?attachments=true to return attachment in base64

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1210]
The `attachments=true` option can be used to return the attachment as base64 encoded and inlined in the doc https://github.com/couchbaselabs/react-native-couchbase-lite/issues/11#issuecomment-214046543. This querystring option is currently handled by LiteServ iOS.

Steps to repro:

1. Run lite serv
2. Upload an attachment with PUT `/dbname/docid/attachmentname`
3. Get the attachment with `/dbname/docid?attachments=true`

Expected: 
```
{"_attachments":
  {
    "attachmentname":
      {
        "digest":"sha1-jm0YDvxvrWnYlesBkw9JKXuIi84=",
        "revpos":2,
        "length":36718,
        "content_type":"image/png",
        "data":"/9j/4AAQSkZJRgABAQA..."
      }
    },
    "_id": 1,
    "_rev": "1-..."
}
```

Result: There is no data attribute in the attachmentname body.

**Comment by hideki** [comment]
- Actual: Currently Router always returns with `stub: true`
```json
{
  "text": "Inline text string created by cblite functional test",
  "_attachments": {
    "inline.txt": {
      "length": 52,
      "digest": "sha1-i\/STphkUNnLhfyegJkGZIcUECYk=",
      "revpos": 1,
      "content_type": "text\/plain",
      "stub": true
    }
  },
  "_rev": "1-bc4efbf2cb19b850a148cf597b2fe7a9",
  "_id": "docWithAttachment"
}
```

- Expect: `attachments (boolean) – Includes attachments bodies in response. Default is false`
http://docs.couchdb.org/en/1.6.1/api/document/common.html
