### ISSUE TITLE
CBL 1.2 Push Replication Continuous mode Behaviour .

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1228]
Hi Folks,

Below is the setup:

CBL <-----> F5 Proxy Server <-----> SyncGateway

1) Push Replication is in Continuous mode.
2) SyncGateWay is brought down.
3) Doc 1 and Doc 2 is inserted.And below error was seen.

https://github.com/couchbase/couchbase-lite-android/issues/818
https://bsyncgw.com:443 /dbdata/_revs_diff
org.apache.http.conn.HttpHostConnectException: Connection to https://bsyncgw.com:443 refused

4)Sync-gateway is brought up but the DOC1 and Doc2 didnt sync.Below error seen.
java.net.SocketTimeoutException: Read timed out
https://github.com/couchbase/couchbase-lite-java-core/issues/1081

5) Doc 3 is inserted after 10 mins.

6)On _bulk_docs sync only Doc 3 was synced not Doc 1 and Doc 2.

7) After 30 mins due to network down/up Sync: [fireTrigger()] => GO_OFFLINEand Sync: [fireTrigger()] => GO_ONLINE
all docs were synced.

Any insights on this? How should be the behaviour.

```
     HttpConnectionParams.setConnectionTimeout(basicHttpParams, DEFAULT_CONNECTION_TIMEOUT_SECONDS * 1000);
            HttpConnectionParams.setSoTimeout(basicHttpParams, DEFAULT_SO_TIMEOUT_SECONDS * 1000);
```
Hows setConnectionTimeout and setSoTimeout work?

Thanks
Nithin

**Comment by hideki** [comment]
@NitzDKoder,

If you bypass proxy, does CBL work as expected?

> Hows setConnectionTimeout and setSoTimeout work?

- setConnectionTimeout: timeout for connection
- setSoTimeout: timeout for read/write

**Comment by NitzDKoder** [comment]
@hideki not tried yet..will update on that..
Pls comment on #6 behavior..

**Comment by hideki** [comment]
> 6)On _bulk_docs sync only Doc 3 was synced not Doc 1 and Doc 2.

Without log, I am not sure what happening. Usually CBL consider Doc 1 and Doc 2 were already synchronized by checking last sequence value for replication target. Or CBL did not retry replication for Doc 1 and Doc 2 for unknown reason.

**Comment by hideki** [comment]
Hi @NitzDKoder,
Do you have any update for this ticket? If not, I will close this ticket.

**Comment by hideki** [comment]
I will close this ticket. If you are still encountering this issue, please reopen.
