### ISSUE TITLE
Push replication from Android LiteServ and sync_gateway not pushing all deleted documents

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1243]
Using Android 0.0.0-710 and sync_gateway 1.2.1-4

The LiteServ db has push / pull replication with a sync_gateway db setup. 
I deleted documents on a a liteserv db and only a subset of the deleted document replicate. 

Below is the failure step. It is interesting that the first time I delete docs on the LiteServ db, they all successfully replicate to sync_gateway. However after creating the docs with the same doc ids, and trying the same action, they do not all replicate.

Failure Step - https://github.com/couchbaselabs/mobile-testkit/blob/feature/implement-compact-revs-limit-test/testsuites/listener/shared/listener_sg_replication_compact_revs_limit.robot#L124

I have reviewed this with @hideki and will help him set up an reproduction next week.

**Comment by sethrosetter** [comment]
Need to verify but I think this was due to a misunderstanding - https://github.com/couchbase/couchbase-lite-ios/issues/1277

**Comment by hideki** [comment]
@sethrosetter Do you have any update for this ticket?

**Comment by sethrosetter** [comment]
I am working on running these tests again with fixes to avoid the race condition pushing which I'm 99% sure was the reason for filing this. Once I get a chance to run this test again, I will update the results.
