### ISSUE TITLE
Investigate behavior when locking / unlocking screen in Android

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1259]
As part of this, look into - `android.intent.action.SCREEN_ON` and `android.intent.action.SCREEN_OFF`

**Comment by djpongh** [comment]
@sethrosetter What is the exact task here?

**Comment by sethrosetter** [comment]
This should be covered with https://github.com/couchbaselabs/mobile-testkit/issues/681

**Comment by djpongh** [comment]
Ok, Thanks!
