### ISSUE TITLE
Querying a design document view returns deleted documents too REST API

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1264]
Originally reported at Couchbase Forum: https://forums.couchbase.com/t/querying-a-design-document-view-returns-deleted-documents-too-rest-api/8643

```
Whenever I query a view, it also returns delete documents.

How can this be fixed?

I am doing something like this:

database.queryView(config.designDoc,"viewName", { include_docs : true, key : id })
The delete documents that are returned in the response are not viewable so it confirms they are actually deleted from local database. I get a 404.

There is no includeDeleted at http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/design-document/get---db--design--design-doc--view--view-name-/index.html
```

**Comment by hideki** [comment]
I wrote the unit test for this scenario. See https://github.com/couchbase/couchbase-lite-android/commit/d221601906aeafa26710316063c295395629ab5c
I run the test against both latest codes and and 1.2.1. However I could not reproduce the issue.

**Comment by lucapale** [comment]
Hi. I have installed the 1.3.0 version of Phonegap plugin and I keep having this problem. The queries keep showing also deleted documents. The problem happens only with Android devices:
https://www.dropbox.com/s/zj7y4uqyg59tvxw/Schermata%202016-08-11%20alle%2018.25.56.png?dl=0

**Comment by NitzDKoder** [comment]
@hideki 

"
[08/16 10:47:47.466] [326] ChangeTracker: ChangeTracker{https://---:---@mydoamin/ptxdata, OneShot, @82d3255}: changeTrackerReceivedChange: {seq=9392470, id=s919916271001_ptx150568001001_meta.doc, deleted=true, removed=[PTX-919916270008-meta-CH], changes=[{rev=3-693a5976dca0e9d0ac1236b9c241304c}]}
[08/16 10:47:47.467] [326] Sync: changeTrackerReceivedChange: {seq=9392470, id=s919916271001_ptx150568001001_meta.doc, deleted=true, removed=[PTX-919916270008-meta-CH], changes=[{rev=3-693a5976dca0e9d0ac1236b9c241304c}]}
[08/16 10:47:47.467] [326] Sync: PullerInternal{https://---:---@mydoamin/ptxdata, pull, f8cce}: adding rev to inbox {s919916271001_ptx150568001001_meta.doc #3-693a5976dca0e9d0ac1236b9c241304c @0 DEL}
[08/16 10:47:47.467] [326] Sync: PullerInternal{https://---:---@mydoamin/ptxdata, pull, f8cce}: changeTrackerReceivedChange() incrementing changesCount by 1
[08/16 10:47:47.467] [326] Sync: PullerInternal{https://---:---@mydoamin/ptxdata, pull, f8cce}: Incrementing changesCount count from 16 by adding 1 -> 17
[08/16 10:47:47.467] [326] Sync: PullerInternal{https://---:---@mydoamin/ptxdata, pull, f8cce}: addToInbox() called, rev: {s919916271001_ptx150568001001_meta.doc #3-693a5976dca0e9d0ac1236b9c241304c @0 DEL}.  Thread: Thread[ChangeTracker-https://---:---@mydoamin/ptxdata,10,TJWS threads]
[08/16 10:47:47.468] [326] Batcher: com.couchbase.lite.support.Batcher@6125bd6: queueObjects called with 1 objects (current inbox size = 15)
[08/16 10:47:47.468] [326] Batcher: com.couchbase.lite.support.Batcher@6125bd6: scheduleWithDelay 250 ms, ignored
[08/16 10:47:47.468] [326] CBLite: setPaused: false
[08/16 10:47:47.468] [326] ChangeTracker: ChangeTracker{https://---:---@mydoamin/ptxdata, OneShot, @82d3255}: /changeTrackerReceivedChange: {seq=9392470, id=s919916271001_ptx150568001001_meta.doc, deleted=true, removed=[PTX-919916270008-meta-CH], changes=[{rev=3-693a5976dca0e9d0ac1236b9c241304c}]}
"

1) Client had s919916271001_ptx150568001001_meta.doc(shared doc) in DB i.e #2 Rev.

2)Server deletes this shared doc after TTL, and changetracker gets this event as above #3 rev .

3)Currenlty from REST View query we are not getting the deleted doc.

4) Does CBL deletes thsi doc from DB itself? Can application have control not to delete?

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

> Does CBL deletes this doc from DB itself or just marks deleted true to this DOC? Can application have control not to delete?

- Just makes deleted true with an empty body.
- You might try to setup sync function on Sync Gateway.

**Comment by NitzDKoder** [comment]
Hello @hideki 
"You might try to setup sync function on Sync Gateway."

1. I Guess Sync-function won’t be called when document is being fetched (GET/bulk-get) or changes_feed is being requested. 
Please clarify what Sync-function changes will help in resolving this issue? 

2.    When CBL receives channel removed event in changes_feed response (“removed”:[…]), today it is deleting local copy of the document. Do we have any control in CBL to not to delete? 

Thanks
Nithin

**Comment by hideki** [comment]
- Sync Gateway can control which documents should be replicated by Sync function.
- You could try Validator to control which revision is added into the database
https://github.com/couchbase/couchbase-lite-java-core/blob/0a991a6f132d4d262cd84e32c5f01a9a6ea03468/src/main/java/com/couchbase/lite/Database.java#L677-L686

> When CBL receives channel removed event in changes_feed response (“removed”:[…]), today it is deleting local copy of the document. Do we have any control in CBL to not to delete?

CBL does not provide the control

**Comment by NitzDKoder** [comment]
@hideki 

Sync Gateway can control which documents should be replicated by Sync function

**How sure are you that we can control at Sync Gateway.**


**Client:**


Option 1: 



active_only	                       	Default is false. When true, the changes response doesn't include either deleted documents, or notification for documents that the user no longer has access to.	query	boolean

Source: - https://developer.couchbase.com/documentation/mobile/current/references/sync-gateway/rest-api/index.html#!/database/post_db_changes



**active_only=true in _changes will address this?**


https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.4.0/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L69

**we have 2 pull replication in app one needs deleted or channel removed docs... other does not need..**

**planning to use channel name as differentiation.. any other way?**


Option 2:


**use DB setValidation and reject delete or removed channel docs.**


**Which would be proper OPTION?**





Thanks
Nithin

**Comment by NitzDKoder** [comment]
@hideki please talk to syncgateway eng and update..

**Comment by hideki** [comment]
@NitzDKoder,

I just talked with SG engineer. There are two approaches.
- `active_only=true` would solve your problem. But the client can not get the notification once the document is deleted on the server.
- Sync Function also solve your problem.

Thanks!

**Comment by ddash1** [comment]
@hideki 
I understand the client option.
How can we do this using the Sync Function? Pls advise.

**Comment by hideki** [comment]
I recommend you to post the question to Couchbase Forum.
https://forums.couchbase.com/c/mobile/sync-gateway

Sync Function Documentation:
https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/sync-function-api-guide/index.html

**Comment by ddash1** [comment]
@hideki 
I could not find any ways to do this from the documentation. Thats why the ask.
We have a ticket pending with support for the same but we are also not getting any responses on it. If there is any documentation please point to it rather than the generic index.html for us to proceed. 

I assume when you mentioned  this can be done using sync function, you had some idea in perspective....

**Comment by hideki** [comment]
Hi @ddash1,

I am not Sync Gateway expert. The following info might not be accurate.

I believe you could write a sync function like the following sample.
https://github.com/couchbase/sync_gateway/blob/master/examples/basic-sync-function.json

```
 if (doc._deleted) {
   throw({forbidden : "not allowed"})
} 
```

FYI: If you already talk with a customer support, I believe the customer support is the best channel to solve the problem.

**Comment by ddash1** [comment]
@hideki 
That would not work as it would not even allow deletion. We want doc deletion but not send in the change notification to preserve the local copy.

**Comment by hideki** [comment]
Hi @ddash1 
Did you try `active_only=true` flag with `/_changes` API?

### active_only
> Default is false. When true, the changes response doesn't include either deleted documents or notification for documents that the user no longer has access to. | query | boolean

https://developer.couchbase.com/documentation/mobile/current/references/sync-gateway/rest-api/index.html#!/database/get_db_changes

**Comment by ArihantRk** [comment]
Hi @hideki 

active_only works as expected which will ignore deleted and channel remove notification.

it would be easy if this is handled in sync function, please share sync function to stop send deleted notification/channel removed to clients.

**Comment by hideki** [comment]
Hi All,

Following is an answer from Sync Gateway Engineer.

#### Difference between `_changes with active_only` and `sync function`
- `_changes` REST API with `active_only` parameter is read-time filtering.
- Sync Function is applied at write-time.

#### An answer to the question:
- If you'd like to prevent deletes and channel removals being written using the sync function, YES you can.
- If you'd like to prevent deletes and channel removals being *sent as part of a pull replication* using sync function, NO you can not.

Sorry for my original answer would cause the confusion.

Hope this helps you!
Hideki

**Comment by ddash1** [comment]
Thanks @hideki

**Comment by ddash1** [comment]
@hideki 
Is this possible using the Replication apis on CBL? We cannot find the active_only option setting on the function properties... Pls advise.

**Comment by NitzDKoder** [comment]
@hideki 
Looking at the code there is no options to set from Replication API.. please confirm..


https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.4.0/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L135

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.4.0/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L186

**Comment by hideki** [comment]
Hi @ddash1 and @NitzDKoder,

`active_only` flag was created to improve the pull replication performance if a local database is empty. Therefore, it is not public API.

To utilize `active_only` flag, it requires modifying the source code.

**Comment by ddash1** [comment]
There seems like we have a valid usecase for having this property exposed  via public api.

**Comment by snej** [comment]
@NitzDKoder -- this is an old bug that seems to have been resurrected as an entirely different issue. And from reading this long thread I don't understand what functionality is desired. Could you please file a new issue with a clear description if what functionality you want to be added to Couchbase Lite? Thanks.
