### ISSUE TITLE
Attachments Store/Retrieve as URL using COAX/RestCBL/Phonegap and CBL(Router)?

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1267]
Hi,
App:

1)Cordova based HTML app.
2)CBL and Phonegap used.

As in CBL this plugin needs the attachments to be stored as blob in private memory absolute path and have a reference to it..this helps in store/retrieve attachments data as URL..Hence avoid content passing from native to Web level(JS) vice-versa.

couchbase/couchbase-lite-java-core#683
couchbase/couchbase-lite-java-core#895

*Retrieve: *
```java
/** 
     * Get the URL of the file containing the contents. 
     * This property is somewhat deprecated and is made available only for use with platform APIs that 
     * require file paths/URLs, e.g. some media playback APIs. Whenever possible, use the `getContent()` 
     * method to get the input stream of the content instead. 
     * The file must be treated as read-only! DO NOT MODIFY OR DELETE IT. 
     * If the database is encrypted, attachment files are also encrypted and not directly readable, 
     * so this property will return null. 
     */ 
    @InterfaceAudience.Public 
    public URL getContentURL() {
        try { 
            return internalAttachment().getContentURL(); 
        } catch (MalformedURLException e) {
            Log.w(Database.TAG, e.toString());
        } catch (CouchbaseLiteException e) {
            Log.w(Database.TAG, e.toString());
        } 
        return null; 
    } 
```
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.2.0/src/main/java/com/couchbase/lite/Attachment.java

**Store:**
```java
/** 
     * Sets the attachment with the given name. The Attachment data will be written 
     * to the Database when the Revision is saved. 
     * 
     * @param name             The name of the Attachment to set. 
     * @param contentType      The content-type of the Attachment. 
     * @param contentStreamURL The URL that contains the Attachment content. 
     */ 
    @InterfaceAudience.Public 
    public void setAttachment(String name, String contentType, URL contentStreamURL) {
        try { 
            InputStream inputStream = contentStreamURL.openStream();
            setAttachment(name, contentType, inputStream);
        } catch (IOException e) {
            Log.e(Database.TAG, "Error opening stream for url: %s", contentStreamURL);
            throw new RuntimeException(e);
        } 
    } 
```
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.2.0/src/main/java/com/couchbase/lite/UnsavedRevision.java

https://github.com/jchris/coax/issues/3

Setup/Queries :

1) Cordova/Phonegap and CBL is used..Basic doc CRUD is ok.
https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin
2) How to deal with attachments?
3) Is this feasible in CBL? Pls confirm..Changes needed in COAX/Phonegap and CBL(Router)?

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

Can following REST APIs cover your scenario?

http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/document/index.html

- PUT /{db}/{doc}/{attachment}
- GET /{db}/{doc}/{attachment}
- DELETE /{db}/{doc}/{attachment}

**Comment by NitzDKoder** [comment]
@hideki thanks for the links..
Had seen these and able to insert attachments.

Problem:
1) PUT /{db}/{doc}/{attachment} 
here the attachments data is sent as body of the request.
2)Router reads them as  InputStream and writes to CBL DB.

    /**
     * @param contentStream if null, delete attachment. if not null, update attachment
     */
    private Status updateAttachment(String attachment,
                                    String docID,
                                    InputStream contentStream)  

**3)SO the data is floating from JS to Java level.**

**4) When data ishuge it will have performance issue.**

Plan:
1)Have custom header defined ,use coax and put request.
2)Custom Header: URL containing attachment data.
3)Router reads from URL from custom header and store to CBL DB and return the Attachment stored CB URL(getContentURL()) response to JS?
public URL getContentURL() {}



does the design holds good? pls suggest..

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

I understand your concern about the performance. REST API is comes from CouchDB REST API, and it is not designed for local to local. You could change REST API to pass/receive file as URL instead of content.

But I am not sure if we could adapt your changes into the master branch because of public API changes.

Thank you very much for sharing this!

Hideki

**Comment by tjayesh** [comment]
I am trying use REST api to add attachment to CBL. I had tried inline attachment and standalone attachment as explained [here](https://wiki.apache.org/couchdb/HTTP_Document_API#Standalone_Attachments), [here ](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/document/put---db---doc---attachment-/index.html)and [here](https://wiki.apache.org/couchdb/HTTP_Document_API#Inline_Attachments). 
But facing following problems;
1. Inline attachments:
application crashing if tried to add larger media file say 5mb and more. As it need Base64 conversion , attachment size is getting increased by 33%.
2. Standalone attachment:
It creates two revisions one while creating attachment doc other on adding associated content to it.
Which adds to extra traffic as document gets synced with server twice. 

I would like to know best practices to handle attachments regardless of their size.

Thanks in advance!
-Jayesh

P.S.
I am using Sencha-touch and pure javascript  to build iOS and Android app. So I am expecting a solution compatible to that setup.

**Comment by tjayesh** [comment]
Hi Hideki,

Please confirm that, inline attachment does not increase the size of attachment.
I found that, even if content passed as base64, internally Couchbase lite converts it to blob and actual file size remains same.

Thanks,
-Jayesh

**Comment by hideki** [comment]
Note: If we implement this, need to restrict to only localhost.

**Comment by snej** [comment]
I'm not sure I understand what you're asking for, but:

1. To get the contents of an attachment, simply `GET /dbname/docid/attachmentname`. The response is the attachment data. That seems like exactly what you're asking for, a URL whose contents are the attachment.
2. To efficiently store a document with its attachments in one revision, use MIME multipart format in the PUT request. Pretty sure this is documented.

**Comment by djpongh** [comment]
Hopefully @snej  points you in the right direction. If you still see a bug, please reopen with the details.
