### ISSUE TITLE
400 Missing data of attachment while pushing attachments

### ISSUE THREAD

**Issue by ashihaby** [couchbase/couchbase-lite-java-core#1272]
Hi, 
When I add multiple attachments to the same document, the first revision synced to the sync gateway and when I started to sync the rest of the updates that has new attachments the sync gateway stopped receiving this document with this error `_bulk_docs got an error: 400 Missing data of attachment `.  
The issue exists on the master branch and appeared in version 1.2.0, I have tried version 1.1.0 and the issue didn't appear in old versions of couchbase lite.

Thanks

**Comment by ashihaby** [comment]
@hideki please check the fix here #1273

**Comment by hideki** [comment]
Hi @ashihaby,

This issue is critical issue. However I need test case or test scenario to reproduce this. Could you please provide test case or test scenario for this?

Thanks a lot!

**Comment by ashihaby** [comment]
Ok I will try to write the test case today

**Comment by ashihaby** [comment]
@hideki I have added test case here couchbase/couchbase-lite-android#931

**Comment by hideki** [comment]
Hi @ashihaby, 
Thank you for writing the test. I will review it tomorrow.
