### ISSUE TITLE
GrocerySync: Need Open ID connect in Grocery Sync Android for release verification

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1274]

**Comment by pasin** [comment]
Here is the repo: https://github.com/couchbaselabs/GrocerySync-Android/tree/feature/openid
Current status:
1. Both AuthCode and Implicit flow with Google Sign-in were implemented.
2. The AuthCode flow is current blocked by #1315 to start the second replication (push) and the application screen.
