### ISSUE TITLE
CBL(OkHttp) and FIPS compliance.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1278]
Hi Folks,

Currently java CBL(Okhttp) is not default FIPS compliance..
https://en.wikipedia.org/wiki/FIPS_140-2

How to make one and make it working android device? Use JSafe/Spongy Castle java library..

https://rtyley.github.io/spongycastle/
https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/FIPS.html
https://docs.oracle.com/middleware/1213/wls/SECMG/fips.htm#SECMG768

Or use:
C level wolfSSL which is FIPS complaint lib to support both Android/iOS?

https://www.wolfssl.com/wolfSSL/Products-wolfssl.html

Any other Hints..Pls suggest..

Thanks
Nithin

**Comment by NitzDKoder** [comment]
@hideki your insights on this?

**Comment by hideki** [comment]
@NitzDKoder 

I am not familiar with FIPS compliance. 

By switching crypto provider with FIPS compliance OpenSSL or Spongy Castle libraries, HTTPS connection could use FIPS compliance crypto library. But I am not sure if this is enough?

Could you please research the FIPS compliance requirement?  I could help whatever I can to meet your requirements.

Thanks.

**Comment by NitzDKoder** [comment]
@hideki 
We have c level wolfssl ssl library which is fips complaint.
https://www.wolfssl.com/wolfSSL/Products-wolfssljni.html
https://www.wolfssl.com/wolfSSL/fips.html



1) Currently there are 56 instances of javax.net.ssl in OkHttp code.
https://github.com/square/okhttp/search?p=3&q=javax.net.ssl&utf8=%E2%9C%93
 
Im going through OkHttp code to replace with com.wolfssl.

https://www.wolfssl.com/documentation/wolfssl-jni-javadocs/index.html


Thanks
Nithin

 
 
Thanks
Nithin

**Comment by djpongh** [comment]
This is an OkHttp issue. We're glad you're on top of it. I don't see anything for us to do here.
