### ISSUE TITLE
Fail to GET raw attachments via LiteServ

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1280]
Using Android 0.0.0-738

```
http PUT http://localhost:59851/cbl-document1/cbl-document1_0 

with body 

{
    "_id":"cbl-document1_0",
    "text":"Inline text string created by cblite functional test",
    "at":"2016-06-20T19:14:55.747Z",
    "_attachments":{
        "inline.txt":{
            "content_type":"text/plain",
            "data":"SW5saW5lIHRleHQgc3RyaW5nIGNyZWF0ZWQgYnkgY2JsaXRlIGZ1bmN0aW9uYWwgdGVzdA=="}
        }
    }
```

With Android LiteServ
```
http GET http://localhost:59851/cbl-document1/cbl-document1_0/inline.txt
```

```
{"error":"not_acceptable","status":406}
```

With Mac LiteServ
```
http GET http://localhost:59851/cbl-document1/cbl-document1_0/inline.txt
```

```
Inline text string created by cblite functional test
```

**Comment by pasin** [comment]
@sethrosetter Can you post the request header values (especially content type and accept)?

**Comment by sethrosetter** [comment]
`GET http://127.0.0.1:8081cbl-document1/cbl-document1_0/inline.txt`

Request Headers:
```
Host: 127.0.0.1:8081
Connection: keep-alive
```

**Comment by pasin** [comment]
Thanks!

**Comment by sethrosetter** [comment]
@pasin 

Just for comparison:
with Mac OSX, these are the request headers:

```
host: 127.0.0.1:59851
Connection: keep-alive
content-type: application/json
accept: application/json

```

This works

**Comment by pasin** [comment]
If remove content-type and accept from the Mac OSX test, does it return the 406 error?

**Comment by pasin** [comment]
Anyway I was able to reproduce the issue with chrome browser. Investigating now.

**Comment by pasin** [comment]
It seems like there must be some Accept value set to the request header in order to reproduce the issue.

**Comment by pasin** [comment]
@sethrosetter Can you see Accept value shown in the logcat? You should see something like:

`Error 406: Can't satisfy request Accept: <ACCEPT VALUE>`

**Comment by sethrosetter** [comment]
I ran the test and saw `06-22 01:45:04.844 5118-5138/? W/Router: Error 406: Can't satisfy request Accept: application/json`

**Comment by pasin** [comment]
CBL Android validates if the Accept is matched with the content-type of the data or not. In general, it seems to behalf correctly. Can you set the Accept value appropriately? 

Note: CBL iOS only validates the Accept for GET /<db>/<doc id>. CBL Android can follow the same rule.

**Comment by pasin** [comment]
@sethrosetter I have fixed the issue to inline the implementation with CBL iOS. If the test still fails, I recommend to set the Accept value to */* or text/plain for this case.

**Comment by pasin** [comment]
@sethrosetter Can you recheck the 'Accept' header value? If the Accept is set to `application/json`, 406 error is correct.

**Comment by sethrosetter** [comment]
I have just tried this with both headers. 

```
http http://192.168.56.101:5984/ls_db/att_doc/sample_text.txt
```

```
HEADERS = {'Content-Type': 'application/json', 'Accept': '*/*'}
```
and
```
HEADERS = {'Content-Type': 'application/json', 'Accept': 'text/plain'}
```

Expected (Mac OSX and .NET) behavior is to return the attachment:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
``` 
Actual:
```
{
"ok": true
}
```

**Comment by sethrosetter** [comment]
There response code is a 200 now, but the attachment is not being returned in the case of Android.

**Comment by pasin** [comment]
Do you keep the logcat?

**Comment by sethrosetter** [comment]
https://gist.github.com/sethrosetter/96ce6b5dd576e27a6a14efeb97489e7b

**Comment by pasin** [comment]
Somehow there is no CBL logs in the logcat. I will try to test this only local mac.

**Comment by pasin** [comment]
I test android-liteserv with CBL-Android 0.0.0-759, it worked as expected.

Case 1: Accept: text/plain
```
$ curl -X GET -H "Content-Type: application/json" -H "Accept: text/plain" "http://10.0.1.9:5984/cblite-test/doc1/inline.txt"
Inline text string created by cblite functional test 
```

Case 2: Accept:*/*
```
$ curl -X GET -H "Content-Type: application/json" -H "Accept: */*" "http://10.0.1.9:5984/cblite-test/doc1/inline.txt"
Inline text string created by cblite functional test
```

Case 3: No Accept
```
$ curl -X GET -H "Content-Type: application/json" "http://10.0.1.9:5984/cblite-test/doc1/inline.txt"
Inline text string created by cblite functional test
```

Case 4: Accept: application/json
```
$ curl -X GET -H "Content-Type: application/json" -H "Accept: application/json" "http://10.0.1.9:5984/cblite-test/doc1/inline.txt"
{"error":"not_acceptable","status":406}
```

**Comment by pasin** [comment]
We can look at this together tomorrow.

**Comment by sethrosetter** [comment]
When content type is not specified when creating a document, Android inserts a null value whereas mac osx does not create the property. 

Android - Attachment created without attachment type.
```
{
    "_attachments": {
        "sample_text.txt": {
            "content_type": null,
            "digest": "sha1-x6zPGLnfGXxKdGqxUN2YzvFGdho=",
            "length": 445,
            "revpos": 1,
            "stub": true
        }
    },
    "_id": "att_doc",
    "_rev": "1-412393957d27988534221d7f91ebb3cf",
    "channels": [
        "NBC"
    ],
    "content": "{\"sample_key\": \"sample_val\"}",
    "updates": 0
}
```

Mac OSX - Attachment created without attachment type.
```
{
    "_attachments": {
        "sample_text.txt": {
            "digest": "sha1-x6zPGLnfGXxKdGqxUN2YzvFGdho=",
            "length": 445,
            "revpos": 1,
            "stub": true
        }
    },
    "_id": "att_doc",
    "_rev": "1-e7fa9a5e6bb25f7a40f36297247ca93e",
    "channels": [
        "NBC"
    ],
    "content": "{\"sample_key\": \"sample_val\"}",
    "updates": 0
}
```
