### ISSUE TITLE
Add unit test for opening 1.3 databases from iOS/.NET

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1283]
Reference:
https://github.com/couchbase/couchbase-lite-ios/issues/1314
https://github.com/couchbase/couchbase-lite-net/issues/684

**Comment by pasin** [comment]
iOS 1.3.0 database files are here: 
https://github.com/couchbase/couchbase-lite-ios/tree/feature/issue_1314/TestData/replacedb/ios130
https://github.com/couchbase/couchbase-lite-ios/tree/feature/issue_1314/TestData/replacedb/ios130-forestdb

**Comment by hideki** [comment]
- [ ] ios
- [ ] android
- [ ] .NET

**Comment by borrrden** [comment]
.NET are here 
https://www.dropbox.com/s/zlkdrah7id4ynfi/net130-sqlite.zip?dl=0
https://www.dropbox.com/s/399ixkdud87iwca/net130-forestdb.zip?dl=0
