### ISSUE TITLE
Update TodoLite to 1.3

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1288]

**Comment by hideki** [comment]
### Followings ToDoLite Android 1.3.0 branches:
- SQLite: https://github.com/couchbaselabs/ToDoLite-Android/tree/release/1.3.0-sqlite
- SQLCipher: https://github.com/couchbaselabs/ToDoLite-Android/tree/release/1.3.0-sqlcipher
- ForestDB: https://github.com/couchbaselabs/ToDoLite-Android/tree/release/1.3.0-forestdb
- ForestDB with Encryption: https://github.com/couchbaselabs/ToDoLite-Android/tree/release/1.3.0-forestdb-encrypt
