### ISSUE TITLE
Build Procedure: Cordova/PhoneGap + CouchbaseLite + Android Studio.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1313]
Hi Folks,

New to Android studio and gradle world..I have  java APIs(JavaListener and JavaScript) compilation issues..What will be the **dependencies** value to support Phonegap java APIs(JavaListener and JavaScript).
 
**build.gradle** 
https://github.com/couchbase/couchbase-lite-android/blob/master/build.gradle
https://github.com/couchbase/couchbase-lite-java-core/blob/master/build.gradle

This does not cover phonegap/Cordova.
http://developer.couchbase.com/documentation/mobile/current/develop/training/build-first-android-app/get-started-studio/index.html

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,
Could you please describe what kind of compilation issue you have?

**Comment by NitzDKoder** [comment]
"    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.mozilla:rhino:1.7R3'
    compile 'com.couchbase.lite:couchbase-lite-java-javascript:0.0.0-766'
    compile 'com.couchbase.lite:couchbase-lite-java-listener:0.0.0-766'
    compile 'com.couchbase.lite:couchbase-lite-android:0.0.0-766'
"
Added these..seems fine now..how will be production dependencies look like?

**Comment by hideki** [comment]
`0.0.0-xxx` is dev build. Please just replace it to `1.2.1` (latest production version number)

**Comment by NitzDKoder** [comment]
@hideki thanks..but i was talking about **dependencies** above way is right?

**Comment by hideki** [comment]
This two dependencies are required to use REST API which is called from JavaScript(AJAX) in PhoneGap/Cordova App

**Comment by NitzDKoder** [comment]
@hideki right im using these from quite a long time in ecplise..but now moving to android Studio..the details of list **dependencies** is not mentioned clearly anywhere..

**Comment by hideki** [comment]
We don't expect user to use CBL for PhoneGap/Cordova from AndroidStudio or Eclipse.

Do you know any good online tutorial or content that describe how to create or open PhoenGap/Cordova project with Android studio? I am not expert of PhoneGap/Cordova, so I am also struggling to debug CBL with PhoneGap.

**Comment by NitzDKoder** [comment]
Way i debug Cordova apps in eclipse is to have java SRC as part of my code..HTML level using chrome debug/inspect..
https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

Manual merge is a pain..Getting used to ur submodule solution..
https://github.com/couchbase/couchbase-lite-java-core/issues/708#issuecomment-227457670
