### ISSUE TITLE
Replication lastError could return a private API exception (RemoteRequestResponseException)

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1314]
See:
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/auth/OpenIDConnectAuthorizer.java#L294
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/auth/OpenIDConnectAuthorizer.java#L302

**Comment by pasin** [comment]
After reviewing the code, the issue is more at the Replicator level. The error set to the Replicator are mostly RemoteRequestResponseException. We should either : 

1. Translate RemoteRequestResponseException to CouchbaseLiteException OR
2. Come up with a new Exception for Replication OR
3. Come up with a new Error class instead of using Throwable for lastError object type.

I'm changing the name of the issue and move it out of 1.3 as the issue has been there before 1.3 and the scope of changing is large.

**Comment by djpongh** [comment]
Will handle in 2.0 API
