### ISSUE TITLE
Autopruning failing on pull replication

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1319]
Step to reproduce:
Using `Android 1.3.0-8`

1. Start LiteServ
2. Start Sync Gateway
3. Add 1 doc to Sync Gateway
5. Update Doc 100 times on SG
7. Set Up Continuous Pull from SG
```
POST http://<liteserv_url>:5984/_replicate
HEADERS = {'Content-Length': '81', 'Content-Type': 'application/json'}
BODY = {"source": "http://<sg_url>:4985/db", "continuous": true, "target": "ls_db"}	
```
```
{"session_id":"repl001"}
```
8. Wait for replications to finish

Query doc with `revs=true`. 

Expected: Client has 20 revisions
Actual: Client has more than 20 revisions

**Comment by hideki** [comment]
@sethrosetter Can you see any error/Exception in the logcat?
