### ISSUE TITLE
Change tracker stopped during continuous replication error thrown when cookie expires

### ISSUE THREAD

**Issue by swaheed2** [couchbase/couchbase-lite-java-core#1334]
I am using cookie authentication in an ionic app using couchbase lite phonegap plugin. Replication runs fine while active_tasks shows this:

```
[
  {
    "progress": 100,
    "continuous": true,
    "source": "todos",
    "status": "Idle",
    "task": "repl007",
    "change_count": 1,
    "target": "http://.../todos",
    "completed_change_count": 1,
    "type": "Replication"
  },
  {
    "progress": 0,
    "continuous": true,
    "source": "http:/.../todos",
    "status": "Idle",
    "task": "repl008",
    "change_count": 0,
    "target": "todos",
    "completed_change_count": 0,
    "type": "Replication"
  }
] 
```

Then I get another cookie through curl, so the cookie on the mobile side expires. No error is thrown while polling but the active_tasks shows this:

```
[
  {
    "progress": 100,
    "continuous": true,
    "source": "todos",
    "status": "Idle",
    "task": "repl007",
    "change_count": 1,
    "target": "http://...todos",
    "completed_change_count": 1,
    "type": "Replication"
  },
  {
    "progress": 0,
    "continuous": true,
    **"error": [
      400,
      "java.lang.Exception: Change tracker stopped during continuous replication"
    ],**
    "source": "http://.../todos",
    "status": "Idle",
    "task": "repl008",
    "target": "todos",
    "type": "Replication"
  }
] 
```

The call to `_changes`  never returns an error and always returns 200.

I am trying to handle cookie expiration using the rest api.

**Comment by hideki** [comment]
@swaheed2,

> The call to _changes never returns an error and always returns 200.

`/_changes` REST API returns changes in the database. It does not return any status of the replicator.

**Comment by hideki** [comment]
Note to Self:

- Replicator stops by cookie expiration, so `/_active_tasks` should return `"status": "stopped"`.

**Comment by hideki** [comment]
@swaheed2,
`_active_tasks` REST API returns only *Active* replicators. It means the stopped (inactive) replicators are not in the response results. To detect replicator's error status, please call `/_active_tasks` with `feed` parameter with `lonpoll` or `continuous`.

**Comment by SachinGhagare** [comment]
> @swaheed2,
> `_active_tasks` REST API returns only _Active_ replicators. It means the stopped (inactive) replicators are not in the response results. To detect replicator's error status, please call `/_active_tasks` with `feed` parameter with `lonpoll` or `continuous`.

Does `_active_tasks` REST API returns _Active_ replicators, exact status of replicators?. Following is ticket filed
[https://github.com/couchbase/couchbase-lite-java-core/issues/1694]
