### ISSUE TITLE
Need SQLite build for LiteServ in CI

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1366]
From talking with Hideki, we need 2 builds for LiteServ Android
- 1 with SQLite
- 1 with SQLCipher, ForestDB, and ForestDB + Encryption

**Comment by pasin** [comment]
Need to work with @michaelkwok to make change to the CI build script.

**Comment by michaelkwok** [comment]
Currently We are generating 2 packages for SQLite and ForestDB.  So we are rebuilding these 2 packages differently.  We are not adding 2 new packages.  Is that correct?

**Comment by michaelkwok** [comment]
I have updated the builds to generate these 2 packages.

1) couchbase-lite-android-liteserv-SQLite-{version-buildNum}-debug.apk built with the option -Dfeatures=basic
2) couchbase-lite-android-liteserv-SQLite-ForestDB-{version-buildNum}-debug.apk built with the option -Dfeature=full

This takes effect in the next build.

**Comment by hideki** [comment]
We discussed this issue with Slack. Thanks!

**Comment by hideki** [comment]
@michaelkwok finished his part. So I will close this.
