### ISSUE TITLE
Live Query Seems broken with ForestDB

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1367]
Possible Android ForestDB+Encryption - Live Query issue

Using Android `1.3.0-42` ForestDB+Encryption
Using iOS or Android `1.3.0` SQLite 

Steps to repo
- Have 2 devices in the same list view that is shared between the devices
- Check a task on one
- Checkbox does not update on Android list when running FDB+Encryption
- Update related, creating / deleting a new document does not exhibit
- Add image to task without image does not show up as well

**Comment by hideki** [comment]
Following is ToDoLite's map function. Key is `list_id` and `created_at` which is never updated. And value is `null`. This map function always emit same key and same value for same Task document instance.
```java
com.couchbase.lite.View view = mDatabase.getView("tasks");
if (view.getMap() == null) {
    Mapper map = new Mapper() {
        @Override
        public void map(Map<String, Object> document, Emitter emitter) {
            if ("task".equals(document.get("type"))) {
                List<Object> keys = new ArrayList<Object>();
                keys.add(document.get("list_id"));
                keys.add(document.get("created_at"));
                emitter.emit(keys, null);
            }
        }
    };
    view.setMap(map, "1.0");
}
```

ForestDB `IndexWriter::update()` method in `Index.cc` returns `false` if `key` and `value` is same, no matter document is updated. So ForestDB storage does not update index for just document updating.
https://github.com/couchbaselabs/cbforest/blob/d6d38d9f4d98f97f7d57a7a3f3dcdcd440bc566d/CBForest/Index.cc#L144    

`IndexWriter::update()` intentionally skips to index in case key and value are same. So this behavior is as expected. Another problem is behavior difference between SQLite storage and ForestDB storage. SQLite storage does not skip indexing even though key and value are same.

Information from @pasin, ToDoLite iOS emits `doc` for `value`. This makes LiveQuery notify changes. By switch to `null` from `docs`, ToDoLite iOS also behaves same with Android.

**Comment by hideki** [comment]
notes from jens

> In general, LiveQuery only considers the query results to have changed if the keys or the values changed. So if the doc changed but it emitted the same key/value, it won’t notify. The problem is that some apps will display a row by using other properties from the document, in which case the row should update.
The compromise I worked out was to consider the row updated if the emitted value is ‘doc’ and the doc’s sequence changed.
I’m not sure about emitting null … ideally it shouldn’t treat that specially. But maybe SQLite does because there were enough apps that didn’t display correctly otherwise?
The best fix in ToDoLite would be to make the view emit ‘doc’ as the value.
