### ISSUE TITLE
Inconsistency about indexing same key and value between SQLite and cbforest

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1369]
In case of emitting same key and value, cbforet does not index it, however SQLite indexes it. Following is sample `map` function. key and value is never changed whenever document is updated.
```java
com.couchbase.lite.View view = mDatabase.getView("tasks");
if (view.getMap() == null) {
    Mapper map = new Mapper() {
        @Override
        public void map(Map<String, Object> document, Emitter emitter) {
            if ("task".equals(document.get("type"))) {
                List<Object> keys = new ArrayList<Object>();
                keys.add(document.get("list_id"));
                keys.add(document.get("created_at"));
                emitter.emit(keys, null);
            }
        }
    };
    view.setMap(map, "1.0");
}
```

For 1.3.0 release, we fixed this in ToDoLite.
https://github.com/couchbase/couchbase-lite-java-core/issues/1367

**Comment by hideki** [comment]
TODO: Write Unit Test - Correct more info

**Comment by hideki** [comment]
Unit Test: https://github.com/couchbase/couchbase-lite-android/commit/9b78bd99a14ae41debdcb7a1df915a278e33c0e7?diff=unified

Steps: 
1. Create View which map function emit same key and value for unique document.
2. Create Live Query from View
3. Create document
4. Update document

SQLite: Live Query notify twice
ForestDB: Live Query notify once

Reason: ForestDB does not emit if both key and value is same with previous one.

**Comment by borrrden** [comment]
Which behavior would be considered correct?  If the information has not changed, then has the query actually been updated?

**Comment by hideki** [comment]
@borrrden we could discuss this during next sprint planning?

**Comment by djpongh** [comment]
Correct for each DB
