### ISSUE TITLE
Phonegap android 1.3.0 failed to build

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1371]
The aar file names in 1.3.0 binary zip file has `-<build no>` suffix (e.g. couchbase-lite-android-1.3.0-43.aar). Phonegap build doesn't expect the suffix, and this needs to be fixed for phonegap build.

Build error:
```
======== expand android =================================
cp: cannot stat '/home/couchbase/jenkins/workspace/couchbase-lite-phonegap-plugin/download/android/**/couchbase-lite-android-1.3.0.aar': No such file or directory
```

**Comment by pasin** [comment]
CC: @sethrosetter

**Comment by hideki** [comment]
Hi @pasin,
We did not make release build yet. This is expected error. By checking `final build` on Jenkins, Jenkins generates build without build number. I plan to make a build once current build pass with QA testing.

**Comment by pasin** [comment]
Can we do it now so we can test phonegap?

**Comment by hideki** [comment]
http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-master/44/

Build 1.3.0-44 also creates 1.3.0 without build number.

This does not affect QA. But creating final build early makes many confusions. When rebuild the final build, jar files on maven is updated, but maven client does not re-fetch if version number is same.

**Comment by pasin** [comment]
I see.

**Comment by hideki** [comment]
Release build is ready.
http://latestbuilds.hq.couchbase.com/couchbase-lite-android/1.3.0/1.3.0-44/

**Comment by pasin** [comment]
Current status:

```
======== expand android =================================
cp: cannot stat '/home/couchbase/jenkins/workspace/couchbase-lite-phonegap-plugin/download/android/**/couchbase-lite-android-sqlite-default-1.3.0.aar': No such file or directory
Build step 'Execute shell' marked build as failure
```

We need to change jenkins build script to not copy the file as we don't have the dependency to the `sqlite-default` anymore in 1.3.0.

https://github.com/couchbase/build/blob/master/scripts/jenkins/mobile/package_phonegap_plugin.sh#L94

Cc: @michaelkwok

**Comment by pasin** [comment]
@hideki / @michaelkwok who can help us change the jenkins build script?

**Comment by michaelkwok** [comment]
I updated the build script to use sqlite-custom for version 1.3.0 and newer.
