### ISSUE TITLE
Investigate intermittent ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1374]
In the robot tests, `Verify Open Revs With Revs Limit Push Conflict` intermittently fails with with `ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))` 

After looking through the logcat, nothing seems out of the ordinary. I have seen this with 1.2.1-18 and 1.3.0-43. I have not tried other versions. It only happens when LiteServ is under a multithreaded, high revisions load. 10 docs / 100 updates / 2 threads with no delay inbetween updates.

**Comment by hideki** [comment]
duplicated with #1592 ? I will close this.
