### ISSUE TITLE
MultipartDocumentReader: Attachment length cannot be parsed as Integer

### ISSUE THREAD

**Issue by vbenso** [couchbase/couchbase-lite-java-core#1379]
During a pull replication that wasn't progressing I've noticed this:
![screenshot from 2016-08-08 14 13 29](https://cloud.githubusercontent.com/assets/8295627/17489054/8dcb0e0e-5d72-11e6-8c26-cd72e7cf0151.png)

Notice how the length was parsed as double. Now, there is an exception when trying to cast this value to Integer.

This document looks like this:
```
{
_attachments: {
page.html: {
content_type: "text/html",
digest: "sha1-CoMkXqmQDNV0kGqqLNJ9d9Bb7Jo=",
length: 2176548,
revpos: 2,
stub: true
}
},
_id: "04345ae00b456b3282614b921c094b96",
_rev: "1-a76cbf59147da6efa1fcafd7001aaaff",
channels: [
"036.792.879-50"
],
contorno_id: "9b6bea7d7c2767405da7689d0100e536",
lab_id: "a1e1294d6e41780897e4ad187d2bd5fa",
owner: "admin",
type: "book"
}
```

compile 'com.couchbase.lite:couchbase-lite-android:1.3.0-45'
compile 'com.couchbase.lite:couchbase-lite-android-forestdb:1.3.0-45'

**Comment by pasin** [comment]
@vbenso What is the server you are using?

**Comment by sethrosetter** [comment]
@pasin Can you follow up with me on adding a regression / unit test?

**Comment by vbenso** [comment]
Hi, 
My SG version is 
==== Couchbase Sync Gateway/HEAD(nobranch)(962dd53+CHANGES) ====
however the problem disappeared  after I updated another document.
When seen, this problem was affection only the last document in the pull replication.

**Comment by vbenso** [comment]
Just to illustrate that this doesn't affect all document's attachments in the same way.
shape.zip's length is double --> BAD
thumb.png's length is integer --> GOOD
![image](https://cloud.githubusercontent.com/assets/8295627/17749639/e9e2daf4-6494-11e6-8631-2f090da60484.png)

**Comment by pasin** [comment]
If you get the doc from SGW directly, does the attachment lenght in float or integer?

**Comment by vbenso** [comment]
@pasin 
Integer in both attachments
```
{
_attachments: {
shape.zip: {
content_type: "application/zip",
digest: "sha1-7iyWiRJUP13fVg038I8rcib6zoM=",
length: 1135502,
revpos: 8,
stub: true
},
thumb.png: {
content_type: "image/png",
digest: "sha1-tQk8ZdvWGPb6VjeHPLUzu+axnBE=",
length: 3571,
revpos: 9,
stub: true
}
},
_id: "a1c8c3c8d1d9d2c8202920eca9cd2f9d962f71bc",
_rev: "9-2c71cba1ebca8750f676137f55374f85",
area_m2: 197335.74415999948,
channels: [
"247.770.130-49"
],
cliente_id: "3df664d6ac6927e315efbbec0ff435de",
contorno_id: "c41f3748b88ba118cf57daa253bc1f48",
date: 1428150525,
descricao: "15/04/04-12:25:13",
owner: "admin",
raw_farm_cod: "8E9I0000",
raw_field_cod: "8E9I000D",
raw_tag_name: "CARGA 1",
raw_task_cod: "8E9I002G",
shp_filename: "a1c8c3c8d1d9d2c8202920eca9cd2f9d962f71bc",
shp_folder: "/mnt/shared_working_space/shp/",
task_type: "Colh. grão",
type: "tasklog"
}
```

**Comment by pasin** [comment]
We are using jackson to deserialize the JSON so I'm not sure why sometimes the value gets deserialized as float instead of int. Maybe @hideki can answer this better.

One thing is that I searched to see how the other places in the code reads the attachment length value out of the JSON Map. It seems like the other places cast the value into Number first to get the integer value. By doing that, we will not depend on float or int.
