### ISSUE TITLE
Got error status: 412,com.couchbase.lite.replicator.RemoteRequestResponseException: Precondition Failed

### ISSUE THREAD

**Issue by iCRG** [couchbase/couchbase-lite-java-core#1383]
Hi All,

I am using CBLite v1.3.0-37, i was doing create/update documents in local database, in between i got this exception after that i could not able to do any replication(push/pull). FYI, those changes are there in local databases

Here is logs

```
0:02.446 32767-739/com.tests.test.login W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {POST, http://192.168.2.7:5984/com_test_7aa79579-e756-caf2-16ed-73eae16dd4e8/_bulk_docs}: Got error status: 412 for http://192.162.2.7:5984/com_test_7aa79579-e756-caf2-16ed-73eae16dd4e8/_bulk_docs. Reason: Precondition Failed
08-10 17:30:02.546 32767-739/com.tests.test.login W/Sync: PusherInternal{http://192.162.2.7:5984/com_test_7aa79579-e756-caf2-16ed-73eae16dd4e8, push, 81721}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: Precondition Failed
```

What might be reason to cause this issue and how i can solve this problem.

Thanks
Prasanna

**Comment by pasin** [comment]
@iCRG Is this error for phonegap/ REST API, or Native App? What version of Sync Gateway are you using?

**Comment by hideki** [comment]
Hi @iCRG,
I believe 412 (Precondition Failed) is returned from Sync Gateway. Could you please enable sync gateway logging to capture what happening at sync gateway side?
Thanks!

**Comment by hideki** [comment]
Hi @iCRG,
Do you have any additional information about this ticket?
Thanks!

**Comment by hideki** [comment]
As we don't have sufficient information to fix this,  I will close this.
