### ISSUE TITLE
getPendingDocumentIDs() returns a cached version of pendingDocIDs while offline

### ISSUE THREAD

**Issue by terrydhariwal** [couchbase/couchbase-lite-java-core#1396]
Hi Team, the bug is very easy to reproduce ...

Expected results:
1. While offline, if I add new documents to Lite, I expect getPendingDocumentIDs to reflect this by increasing the size of the pendingDocIDs collection

To reproduce the bug:
1. make Lite app go offline
2. add documents to Lite and call getPendingDocumentIDs()
3. the result returned from getPendingDocumentIDs() does not reflect the latest write because it is returning a cached value (the line of code that is responsible is line 473 of src/main/java/com/couchbase/lite/replicator/Replication.java)

**Comment by borrrden** [comment]
I actually coincidentally got the same bug report on .NET (https://github.com/couchbase/couchbase-lite-net/issues/724)

**Comment by pasin** [comment]
Please see the commit or PR from this issue https://github.com/couchbase/couchbase-lite-ios/issues/1132.
