### ISSUE TITLE
Continuous pull replicator doesn't automatically stop when SGW session expires

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1397]
Steps:
1. Start a continuous pull replicator by using POST /_replicate with a SGW session cookie set in the header.
2. Create a document on the SGW to test if the pull replicator works.
3. Delete the session from SGW using reset API
4. Create a new document on the SGW to see if the pull replicator can detect the expired session and stopped or not.

Result:
After step 4, replicator doesn't pull anything but doesn't stop either. Not sure if I didn't wait long enough for any timeout to happen or not.

**Comment by pasin** [comment]
@adamcfraser if the session is expired or is deleted from the SGW, will SGW terminate longpoll/continuous _changes feed (including the case that there are new changes coming to the SGW as well)?

**Comment by adamcfraser** [comment]
Session validation happens on a per-request basis, so a continuous changes request will continue to run until it's closed by the client or times out.

That's just the changes request, though - the bulk_get calls made by the client to retrieve the docs referenced in the changes request are going to fail if they are using an expired session.

**Comment by pasin** [comment]
Thanks @adamcfraser for the information. As the session is validated per request, I don't think this issue is valid. I'm closing the issue now.
