### ISSUE TITLE
Longpoll _changes on Listener does not respect timeout property

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1399]
Using `1.3.0-43`

1. Start Android LiteServ
2. Issue 30 concurrent `/db/_changes` requests with timeout specified
```
POST http://192.168.59.101:5984/ls_db/_changes
with params
{"feed": "longpoll", "style": "all_docs", "since": 0, "timeout": 5000}
```
3. All 30 requests are in 'waiting' state and never timeout

Expected: I would expect the request to timeout after 5 secs
Actual: Request does not timeout

**Comment by pasin** [comment]
This has been implemented in https://github.com/couchbase/couchbase-lite-java-core/commit/f288ed8cd83e0ddf20c3b727f10c994b58840f80 for 1.3.1.
