### ISSUE TITLE
CBL Java on Windows: ViewsTest > testDeleteView FAILED

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1411]
CBL Java on Windows (ForestDB only)
```
com.couchbase.lite.ViewsTest > testDeleteView FAILED
    junit.framework.AssertionFailedError at ViewsTest.java:178
```

**Comment by hideki** [comment]
This could be regression by fixing https://github.com/couchbase/couchbase-lite-java-core/issues/1394

**Comment by hideki** [comment]
Postponed to fix this in 1.4.0

**Comment by hideki** [comment]
Following part of forestDB code does not work with Windows
https://github.com/couchbase/forestdb/blob/stable/src/compactor.cc#L1171-L1172

`FindFirstFile()` method's first parameter requires directory or path, and search pattern. (EX `<directory>/<search_pattern>`).
https://msdn.microsoft.com/en-us/library/windows/desktop/aa364418(v=vs.85).aspx

**Comment by hisundar** [comment]
Thanks for the diagnosis, Hideki! Will try to get it fixed asap.

**Comment by hisundar** [comment]
https://issues.couchbase.com/browse/MB-20738 is meant to track same issue. thanks

**Comment by hideki** [comment]
Issue was in forestdb. Fixed with https://github.com/couchbaselabs/couchbase-lite-java-forestdb/commit/f95a22f6ed4690408f871d62bcd0841962552900
