### ISSUE TITLE
Query with IndexUpdateMode.AFTER could return incorrect result

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1418]
Currently when IndexUpdateMode.AFTER is used, `view.updateIndex()` will be run on a new thread at **the same time** as `view.query()`, which is not correct. 

See: https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L2180-L2194.

**Comment by hideki** [comment]
`ViewsTest.testIndexUpdateMode()` method sometimes fails with `IndexUpdateMode.AFTER` test
```java
        // do a query and force re-indexing, number of results should be +4
        query.setIndexUpdateMode(Query.IndexUpdateMode.BEFORE);
        assertEquals(5, query.run().getCount());

        // do a query which will kick off an async index
        putNDocs(database, 1);
        query.setIndexUpdateMode(Query.IndexUpdateMode.AFTER);
        assertEquals(5, query.run().getCount());
```

**Comment by hideki** [comment]
This might block Jenkins' build because of test failure. I need to work this first.
