### ISSUE TITLE
Replicator.lastError is not reset when restarting replicator.

### ISSUE THREAD

**Issue by vbenso** [couchbase/couchbase-lite-java-core#1421]
I'm using the following pattern to monitor session expiration and other replication error.
```
private Replication.ChangeListener getReplicationChangeListener() {
        return new Replication.ChangeListener() {

            @Override
            public void changed(Replication.ChangeEvent event) {
                Replication replication = event.getSource();
                if (event.getError() != null) {
                    Throwable lastError = event.getError();
                    if(lastError.getMessage()!=null) {
                        Log.e(TAG, lastError.getMessage());
                        if (lastError instanceof RemoteRequestResponseException) {
                            RemoteRequestResponseException responseException = (RemoteRequestResponseException) lastError;
                            Map info = ((RemoteRequestResponseException) lastError).getUserInfo();
                            if (responseException.getCode() == 401 && replication.isPull() && info==null) {
                                onSyncUnauthorizedObservable.notifyChanges();
                                event.getSource().setLastError(null); //or .clearLastError()
                            }
                        }
                    }
                }
                EventBus.getDefault().post(event);
            }
        };
    }
```
Seems that after an authentication failure (error 401), in the next change events, even in the succesful ones, getError() is still returning that previously handled error.
So, I want to clear the error with setLastError(null), after the error is dealt with.
Is it possible to make Replication.setLastError() public?
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/Replication.java#L457-L463

I'm using
cda63bbcbc12d3518992da7145fa160f81085edf libraries/couchbase-lite-java-core (1.3.0-5-gcda63bb)

Related issues: #1327 #1314

**Comment by hideki** [comment]
We might add `clearLasetError()` instead of make `setLasteError(...)` public.

**Comment by pasin** [comment]
> Seems that after an authentication failure (error 401), in the next change events, even in the succesful ones, getError() is still returning that previously handled error.

I haven't checked the current CBL iOS behavior for this but it feels like a bug to me.

**Comment by hideki** [comment]
If CBL reset lastError with every successful operation,  lastError variable could be set `null` just one successful operation.  I believe this is reason lastError is never reset.

**Comment by pasin** [comment]
When the permanent error (e.g. 401) occurs, the replicator will be stopped. If (re)starting the replicator again, the lastError should be reset to null.

Reference: https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLReplication.m#L307-L308

**Comment by hideki** [comment]
I did not have chance to verify that restarting replicator does not work. Restarting replicator could fail because `ReplicagtorInternal.error` is assigned permanent error.
