### ISSUE TITLE
Replicator fails to wake up from offline state

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1425]
Nexus 5 - Android 6.0.1 - CBL Android - 1.3.1-28

Works with 1.3.0

This is mostly a Nexus 5 issue, this works with Nexus 6 according to @hideki 

This requires Toggling Wifi off / on

Steps to reproduce with TodoLite Android
- Turn off wifi on device (make sure device does not have carrier access)
- Create a list with a few tasks
- Share with a few people
- Reenable Wifi
- The replicator will not wake up.

Fixed when restarting the app.

**Comment by sethrosetter** [comment]
@hideki saw this work with 1.3.1-28. Seems intermittent.

**Comment by sethrosetter** [comment]
Just tried 3 more times, worked everytime.

**Comment by hideki** [comment]
ToDo:
- It seem this is environmental issue. I think CBL encountered permanent error, and CBL stopped replicators. We should test this scenario in next week with same condition. If we could reproduce this, we should look into this. But, if we can not, we will close this ticket.

**Comment by sethrosetter** [comment]
We tried the scenario again using `1.3.1-28`. We were unable to reproduce the issue.
