### ISSUE TITLE
createPullReplication how to set the since query param

### ISSUE THREAD

**Issue by igreenfield** [couchbase/couchbase-lite-java-core#1426]
I start listening to PullReplication like that:

``` java
val manager = new Manager(new JavaContext(), Manager.DEFAULT_OPTIONS)
  val sgUrl = new URL("http://test-machine:4984/sync_gateway/")
  val auth =  AuthenticatorFactory.createBasicAuthenticator("ombo", "master1")
  val db = manager.getDatabase("sync_gateway")

  db.addChangeListener(new Database.ChangeListener(){
    override def changed(event: ChangeEvent): Unit = {
      println(event.getChanges)
    }
  })

  val push = db.createPullReplication(sgUrl)
  push.setContinuous(true)
  push.setAuthenticator(auth)
  push.start()
```

it always pull the last seqId and start from there. how I can set it to number I need?

**Comment by hideki** [comment]
Hi @igreenfield,
Your client side code uses default setting. So, I recommend you to check server side setting, Sync Gateway or CouchDB?
Thanks,
Hideki

**Comment by igreenfield** [comment]
Hi @hideki  

I will clarify my question:
The driver save the last revision it fetch, it checkpoint this value to doc in the sync-gateway db. 
when you restart the program it takes this value and continue from there.
the question is: 
When you add changeListenr if it failed to process the change the message still mark as handled so how I can change this behavior?

Thanks
Izek

**Comment by hideki** [comment]
Hi @igreenfield,

As you wrote in your comment, CBL ignore the Exception from `ChangeListener.changed(...)`. 
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L2389-L2400

Current version of CBL does not provide to override this part of code. So you could modify this part of implementation, and build CBL by yourself.

**Comment by hideki** [comment]
Hi @igreenfield,
CBL automatically stores check point value into the database at end of the replication. When replication is launched, new replication skips already pull replicated changes. So, since parameter is not necessary to be exposed as public API.
Thanks!
