### ISSUE TITLE
SQLiteStore.winningRevIDOfDocNumericID always returns outIsConflict as false

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1428]
The condition check on this [line](https://github.com/couchbase/couchbase-lite-java-core/blob/af4d13b089b7885788950ec95d5f4d698493bb43/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L2230) is not correct. It shouldn't check `outIsConflict.get()`.

**Comment by hideki** [comment]
PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1443
