### ISSUE TITLE
Is it possible to make CBL use only IPV6 wifi connection, when the wifi router provides both IPV4 and IPV6 addresses.

### ISSUE THREAD

**Issue by mganeshan** [couchbase/couchbase-lite-java-core#1430]
Hi,
Currently we are developing Android application using CBL library.
We have a requirement where CBL has to use only IPV6 wifi connection when the wifi rotuer provides both IPV4 and IPV6 adresses.
Is it possible to do this?

If yes, please let me know how it can be done.

Regards,
Ganeshan

**Comment by hideki** [comment]
ATTN: @sethrosetter

**Comment by hideki** [comment]
@mganeshan,
Our QA team will test CBL against IPV6. We will share the test result here.
Thanks!

**Comment by sethrosetter** [comment]
@pasin and I have tested TodoLite with IPv6 and CBL worked as expected. I'm not sure about prioritizing IPv6 vs IPv4. @pasin or @hideki. Any thoughts?

**Comment by hideki** [comment]
Hi @mganeshan,
We confirmed that CBL Android works fine with IPv6. But I don't know how to prioritize IPv6.
Thanks!

**Comment by NitzDKoder** [comment]
@hideki 
One way to prioritize ipv6 is to fetch decive ipv6 ip and  bind later create socket..
https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#Socket(java.lang.String,%20int,%20java.net.InetAddress,%20int)

Make sense?,make change in okhttp code?
Thanks 
Nithin

**Comment by hideki** [comment]
@NitzDKoder 

Thank you very much for your inputs. Since 1.3.0, CBL Android/Java uses OkHttp with v3.3.1. We don't modify it, and no plan to modify it.

Thanks!

**Comment by NitzDKoder** [comment]
@sethrosetter @hideki pls share details how the todolite was tested on IPV6? 

Whats does okhttp pick as device IP? Ipv6 or IPv4?

Is it on Celluar data or wifi? How is the wifi router configuration?

Any changes/configuration in syncgateway needed to support ipv6?


Thanks
Nithin

**Comment by sethrosetter** [comment]
@NitzDKoder We tested over Wifi with a test router using internet sharing. See https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html for more details on how to set up.

With regard to okhttp, @hideki can you comment.

Also, there was no requirement for sync_gateway as far as I know, @adamcfraser may have more details regarding this.

**Comment by hideki** [comment]
Comment from OkHttp
```
// Try each address for best behavior in mixed IPv4/IPv6 environments.
```
https://github.com/square/okhttp/blob/988142cfe555547bc1df4370babe12c6be86cf3e/okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.java#L171

I assume OkHttp picks best behavior InetAddress from availables.

**Comment by NitzDKoder** [comment]
@hideki @sethrosetter thanks for the info..will check from ourside and update more..
