### ISSUE TITLE
Encrypted attachments taking really long time to replicate.

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1434]
To be determined:
- Do they eventually replicate or do some error?

POST to LiteServ

[inline attachment](https://gist.github.com/sethrosetter/ef03717755ee05e206a1c92d8c5f16d3)

Using `Sync Gateway 1.3.0-274`

1.3.1-28 - SQLite
```
PUT http://10.0.2.2:9888/db/cbl-replication-attach1_0?new_edits=false
```

Request:
```
Accept: */*
Transfer-Encoding: chunked
Connection: Keep-Alive
User-Agent: CouchbaseLite/1.3 (1.3.1/b38342673a4f490b825b2bb20046f721acbbd335)
Accept-Encoding: gzip, deflate
Content-Type: multipart/related; boundary=fef104a8-bf0c-428d-bb29-5fd6c97a5208
Host: 10.0.2.2:9888
```

Response:
```
Date: Fri, 09 Sep 2016 01:03:17 GMT
Content-Type: application/json
Server: Couchbase Sync Gateway/1.3.0
Content-Length: 87
```

POST Data
```
--fef104a8-bf0c-428d-bb29-5fd6c97a5208
Content-Type: application/json; charset=utf-8
Content-Length: 414

{"_rev":"1-f604d916210e3f1e6d485932d1fc8f6e","_id":"cbl-replication-attach1_0","_revisions":{"start":1,"ids":["f604d916210e3f1e6d485932d1fc8f6e"]},"_attachments":{"IMG_1496.JPG":{"follows":true,"length":2358797,"digest":"sha1-2FtGNMWyFuMMeZM8VQsdiGV7Nlk=","revpos":1,"content_type":"image/png"}},"img":"/Users/sethrosetter/Code/sync-gateway-tests/tests/../tests/data/GGATE_BIG.JPG","at":"2016-09-09T01:03:05.798Z"}
--fef104a8-bf0c-428d-bb29-5fd6c97a5208
Content-Disposition: attachment; filename=IMG_1496.JPG
Content-Type: image/png
```

SQLCipher
```
PUT http://10.0.2.2:9888/db/cbl-replication-attach1_0?new_edits=false
```
Request:
```
Accept: */*
Transfer-Encoding: chunked
Connection: Keep-Alive
User-Agent: CouchbaseLite/1.3 (1.3.1/b38342673a4f490b825b2bb20046f721acbbd335)
Accept-Encoding: gzip, deflate
Content-Type: multipart/related; boundary=742c3981-f9e3-4118-94ff-273e83405741
Host: 10.0.2.2:9888
```
Response:
```
Content-Length: 119
Content-Type: application/json
Connection: close
Date: Fri, 09 Sep 2016 01:18:29 GMT
Server: Couchbase Sync Gateway/1.3.0
```
POST data is empty!!

returns after ~104s - {"error":"Internal Server Error","reason":"Internal error: multipart: Part Read: http: unexpected EOF reading trailer"}

From the sync_gateway logs
```
# cleanup cb bucket
deletion db: http://localhost:8081 cbl-replication-attach1
2016-09-08T18:18:29.284-07:00 HTTP: #009:     --> 500 Internal error: multipart: Part Read: http: unexpected EOF reading trailer  (112465.6 ms)
2016-09-08T18:18:29.284-07:00 HTTP: #009:     --> 500 Internal error: multipart: Part Read: http: unexpected EOF reading trailer  (112465.6 ms)

2016-09-08T18:18:29.289-07:00 HTTP: #011:     --> 500 Internal error: multipart: Part Read: http: unexpected EOF reading trailer  (104306.9 ms)
2016-09-08T18:18:29.289-07:00 HTTP: #011:     --> 500 Internal error: multipart: Part Read: http: unexpected EOF reading trailer  (104306.9 ms)

2016-09-08T18:18:29.292-07:00 HTTP: #013:     --> 500 Internal error: multipart: Part Read: http: unexpected EOF reading trailer  (93218.7 ms)
2016-09-08T18:18:29.292-07:00 HTTP: #013:     --> 500 Internal error: multipart: Part Read: http: unexpected EOF reading trailer  (93218.7 ms)

2016-09-08T18:18:29.295-07:00 HTTP: #015:     --> 500 Internal error: multipart: Part Read: http: unexpected EOF reading trailer  (81863.5 ms)
2016-09-08T18:18:29.295-07:00 HTTP: #015:     --> 500 Internal error: multipart: Part Read: http: unexpected EOF reading trailer  (81863.5 ms)

2016-09-08T18:18:30.006-07:00 CRUD+: Invoking sync on doc "cbl-replication-attach1_0" rev 1-e16fc048fa32c875b96b409ee73ac9d8
```

1. Create 5 images using above the inline image
2. Create continuous replication to sync gateway
3. Monitor the replication process. 

Works well with SQLite but is really slow / errors (needs to be determined) with SQLCipher

**Comment by sethrosetter** [comment]
Tracking ticket - https://github.com/couchbaselabs/mobile-testkit/issues/668

**Comment by tleyden** [comment]
What are the steps to repro?

**Comment by snej** [comment]
>Works well with SQLite but is really slow / errors (needs to be determined) with SQLCipher

FYI this is unlikely to be anything to do with SQLCipher, because attachments aren't stored in the database, they're separate files. When the db is encrypted, the attachments are encrypted via CBL code. Maybe that code in Java is slow?

**Comment by sethrosetter** [comment]
Using `API 19 Nexus 4 armeabi-v7a` stock emulator

**Comment by pasin** [comment]
I understand that the test PUT documents with ~2.3M inline attachment through the liteserv. If that's correct, the attachment will not be in the file. It's possible that the slowness might be because the test is running on of an arm emulator.

**Comment by snej** [comment]
Yeah, encryption is CPU-intensive. Can you try the test on a real device?

**Comment by sethrosetter** [comment]
Running the test using a Nexus api 19 emulator x86, the push of each attachment from from LiteServ to SG is ~3s

**Comment by sethrosetter** [comment]
@snej the node tests do not run on device at the moment. I can try to get it to work.

**Comment by hideki** [comment]
Attachment is should be stored as a file no mater if it is inline or not in REST api request. For this test scenario, each attachments are encrypted to be stored, and decrypted to be sent. There are three possibilities that cause slowness. 1)  As mentioned in previous comment, `armeabi-v7a stock emulator` is slow. 2) In general, encryption API that Android provides is slow. 3) encryption/decryption might consume a lot of memory. For encryption, input data and encrypted data is byte array. So at least it requires twice memory space. As old version of Android allows limited memory, encryption/decryption causes GC frequently, and it makes system really slow.

#### Storing document through REST API:
do_PUT_Document(...) in Router.java
https://github.com/couchbase/couchbase-lite-java-core/blob/44449cb11ea949dc8fc3eee3c0d84069232a8af0/src/main/java/com/couchbase/lite/router/Router.java#L2329
 
Attachments are stored as a file:
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L1007

Encrypting attachment byte array:
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/BlobStore.java#L492-L499

#### Push replication with attachment

RemoteMultipartRequest - Generate multipart request
https://github.com/couchbase/couchbase-lite-java-core/blob/a7910bc03506875ad0aa39eb37ced34a24592652/src/main/java/com/couchbase/lite/replicator/RemoteMultipartRequest.java#L124-L163

Decrypting attachment from encrypted file
https://github.com/couchbase/couchbase-lite-java-core/blob/a1b06b4edb49b450dd1591838c5d5a01389b7ab9/src/main/java/com/couchbase/lite/BlobStore.java#L468-L469

**Comment by snej** [comment]
Usually encryption APIs have an option to operate incrementally, or to stream the data. Is that possible with the Java API?

**Comment by sethrosetter** [comment]
I got the scenario running on device (Nexus 5, API 23) and the attachments are replicating in ~500 ms. It is looking more like an arm related red herring.

**Comment by snej** [comment]
Herrings have arms?! 💪🐟

**Comment by hideki** [comment]
Java supports stream for encryption/decryption. CBL uses stream for decryption, but does not use stream for encryption. We need to enhance the logic.

https://docs.oracle.com/javase/7/docs/api/javax/crypto/CipherInputStream.html
https://docs.oracle.com/javase/7/docs/api/javax/crypto/CipherOutputStream.html
