### ISSUE TITLE
NPE Manager.java upgradeOldDatabaseFiles.  Occasional Null Pointer.

### ISSUE THREAD

**Issue by natgross** [couchbase/couchbase-lite-java-core#1469]
CBL 1.3.1. 
I am getting an NPE from the Manager.java class. It seems to happen when no files to upgrade are found, causing the Files[] array null access.
I have enclosed a screenshot of the debugging session with arrows drawn to the relevant error.
I do not know why I didn't get this error until now, also on empty folders.
Here is the screenshot:
![npe_manager java](https://cloud.githubusercontent.com/assets/8798507/19223447/30e543ba-8e3e-11e6-975c-b9c873cef317.png)

**Comment by hideki** [comment]
Hi @natgross ,

Thank you for reporting the issue.

I have a question. As `directory` value is unfamiliar with me, I am wondering where you installed the application? on SD-CARD?

https://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles(java.io.FilenameFilter)
> An array of abstract pathnames denoting the files and directories in the directory denoted by this abstract pathname. The array will be empty if the directory is empty. Returns null if this abstract pathname does not denote a directory, or if an I/O error occurs.

Thanks!

**Comment by natgross** [comment]
Application is installed normally, in this case via Android Studio ADB.
As far as the directory path goes, this path is normal for many Android devices returned by the Android **Environment.getExternalStorageDirectory()** call.  (I am extending AndroidContext in order to utilize this path.)
Please note that I have many CBL db's , (Sql lite & Forest) using this format without any problem.
Why I am having this problem now, I don't know, but the bug is the Manager.java source regardless.
It is likely I have my own bugs, in this [new] app, but I can't proceed with my debugging due to the npe caused by this issue.

**Comment by hideki** [comment]
@natgross Thank you for your inputs. We will add `directory` parameter value check and also `files` variable `null` check.

**Comment by natgross** [comment]
I thank you much.
nat

**Comment by natgross** [comment]
@hideki For what its worth; root cause found.
If an app targets >= Android 6, but does not utilize the new api to prompt the user for read/write rights, this will cause the aforementioned File[] array to be null.
So, yes this bug is fixed for 1.5 but it would also be extremely useful (open new issue?) for CBL to check if the app/user has os read/write rights to the requested directory, and if not, at least throw a descriptive exception that explains the problem, and/or supply the developer callbacks to gracefully handle it in the code. This would elimenate many related problems in the first place.
Thanks again.
nat

**Comment by hideki** [comment]
@natgross CBL now checks directory argument variable. Following is PR which was already merged. Could you please review it?
https://github.com/couchbase/couchbase-lite-java-core/commit/c21309d07e96aed22a9a26f7cc61c782dd32087f

**Comment by natgross** [comment]
@hideki If you give the user more information on the exceptions it would suffice.

**For example:**

throw new IllegalArgumentException("directory argument is invalid. [Possible access rights issue.]");

throw new IOException(String.format(Locale.ENGLISH, "Error in File.listFiles(): directory=[%s]" + "Access rights?", directory.toString()))

**Comment by hideki** [comment]
@natgross Thank you for your feed back. I will fix it.

**Comment by natgross** [comment]
It's a pleasure.
Thank you.
