### ISSUE TITLE
iOS pull replication from Android

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1470]
Android should return the expected response to a request that contains the `Connection: close` header. Currently it closes the connection.

For that reason, pull replications running on iOS with Android as the remote are currently failing.

See https://forums.couchbase.com/t/issue-when-connecting-to-java-listener-from-couchbase-lite/10291

**Comment by jamiltz** [comment]
Observation:

```
curl -H 'Connection: close' -H 'Content-Type: application/json' -vX POST 'http://localhost:5984/user2' -d '{}'
```

When the `Connection: close` header is present the response is returned to the client before the [setResponse()](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/router/Router.java#L660) method is reached.

**Comment by jamiltz** [comment]
Actually with the `Connection: close` header the connection is closed as soon as this [line is called](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/router/Router.java#L248).

**Comment by hideki** [comment]
Duplicate/Reference: https://github.com/couchbase/couchbase-lite-java-core/issues/1564

**Comment by hideki** [comment]
PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1565
