### ISSUE TITLE
html <img> tag could not access attachment directly

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1474]
Hi,

I am working on a hybrid HTML android(Cordova/Sencha/HTML5) application.
I am trying to display image using HTML img tag by passing following urls.

http://localhost:5984/db_name/doc_id/file_name.jpg 
This returns "406 (Not Acceptable)"

http://127.0.0.1:5984/db_name/doc_id/file_name.jpg
This returns "404 (Not Found)"

However, Ajax GET request for http://localhost:5984/db_name/doc_id/file_name.jpg returns blob.

Also, similar URL workes well in iOS;
http://lite.couchbase./db_name/doc_id/file_name.jpg

Please, suggest me a correct way of accessing image attachments from CBL by directly passing URL to HTML image tag.

Also the any rest request done at JS level will hit Java router code ? Pls confirm.
https://github.com/couchbase/couchbase-lite-java-core/tree/master/src/main/java/com/couchbase/lite/router

Thanks
Nithin

**Comment by jamiltz** [comment]
I've just tried with the phonegap plugin and the image is showing in a `<img src="url_to_attachment" />`. How are you uploading the attachment? You must specify the `Content-type: image/jpg` header in this case since it's an image.

**Comment by hideki** [comment]
@jamiltz, Thank you for debugging this issue.
CBL Android/Java sets `application/octet-stream` if the attachment content-type is unknown. REST request for attachment could not set correct `content-type` for image.

**Comment by NitzDKoder** [comment]
@hideki Also the any rest request done at JS level will hit Java router code ? Pls confirm.
https://github.com/couchbase/couchbase-lite-java-core/tree/master/src/main/java/com/couchbase/lite/router

**Comment by hideki** [comment]
@NitzDKoder 

> Also the any rest request done at JS level will hit Java router code ? Pls confirm.

Yes

**Comment by NitzDKoder** [comment]
@hideki @jamiltz 
**http://:@localhost:5984/db_name/doc_id/file_name.jpg**, this URL format worked..maybe server it was looking for basic auth format.
Also when DB is encrypted, we are able to see the data retrieved and displayed. The decrypted data is passed from native? Yet to debug at Router code.

Thanks
Nithin

**Comment by jamiltz** [comment]
Are you experiencing an issue? If so can you provide all the information for the scenario that isn't working for you? I've tried loading a `jpg` image in an `<img />` and that works fine.

**Comment by NitzDKoder** [comment]
@jamiltz like i explained above "http://:@localhost:5984/db_name/doc_id/file_name.jpg, this URL format worked in html <img> tag " 

Query:Also when DB is encrypted, we are able to see the data retrieved and displayed. The decrypted data is passed from native? 

Thanks
Nithin

**Comment by jamiltz** [comment]
Oh I see, I didn't read your response properly. Glad it works for you now!

> Query:Also when DB is encrypted, we are able to see the data retrieved and displayed. The decrypted data is passed from native?

Encryption APIs are not available to the REST API. Opening an encrypted database through the REST API will return a 401 unauthorized error. Here's what I see in the browser when querying an encrypted database (https://cl.ly/1M073g2O2B3I/Pasted_Image_17_10_2016__09_56.png). There is an open ticket to provide the encryption key through the REST API (https://github.com/couchbase/couchbase-lite-java-core/issues/1445).

You can follow [these steps](http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/couchbase-lite/native-api/database/index.html#database-encryption) to get encryption up and running but keep in mind you won't be able to query the DB from the REST API.
