### ISSUE TITLE
Changes feed skipping changes on rapid long poll

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-java-core#1495]
Using 1.3.1-60, I ran @sethrosetter 's test_peer_2_peer_sanity_pull (using SQLCipher for both) with .NET as the receiver and Android as the sender (i.e. pull from Android to .NET) and discovered that the client often misses documents.  I opened the DB on the .NET side and found that the first missing document was test_ls_db2_160.  I also found that this document never showed up in the changes feed (among others later).  Here is the traffic around the time in question:

```
1) 10:46:00.454409: PUT /ls_db2/test_ls_db2_159 (from test framework)
2) 10:46:00.455935: POST /ls_db2/_changes (from LiteServ .NET, since 159)
3) 10:46:00.458387: 200 response to (2) contains test_ls_db2_159 (last_seq=160)
4) 10:46:00.458396: 201 response to (1)
5) 10:46:00.460067: PUT /ls_db2/test_ls_db2_160 (from test framework)
6) 10:46:00.461837: POST /ls_db2/_all_docs (from LiteServ .NET)
7) 10:46:00.461868: POST /ls_db2/_changes (from LiteServ .NET since 160)
8) 10:46:00.468612: 201 response to (5)
9) 10:46:00.470141: PUT /ls_db2/test_ls_db2_161 (from test framework)
10) 10:46:00.475547: 200 response to (7) *contains test_ls_db_161 only* (last_seq=162)
11) 10:46:00.475556: 201 response to (9)
12) 10:46:00.477242: 200 response to (6) (contains doc data for 106-159)
```

**Comment by hideki** [comment]
@borrrden When you come to MV office, can you explain the issue? Learning from you could be faster to understand the problem.

**Comment by hideki** [comment]
Note to Self:
I am not confident enough about the PR. This requires further review. I cleared milestone.

**Comment by hideki** [comment]
Taken care by the ticket: https://github.com/couchbase/couchbase-lite-java-core/issues/1593
