### ISSUE TITLE
Android Couchbase error getting remote checkpoint

### ISSUE THREAD

**Issue by avadapp** [couchbase/couchbase-lite-java-core#1512]
You can find my issue on [StackOverFlow](http://stackoverflow.com/questions/40380787/android-couchbase-error-getting-remote-checkpoint)

**Comment by hideki** [comment]
Hi @avadapp,
It seems you tries to sync against Yahoo REST API with your application. But Couchbase Lite does not support the replication against Yahoo REST API or other REST APIs. Couchbase Lite provides the replication with Couchbase Server through SyncGateway or CouchDB (including Cloudant).
