### ISSUE TITLE
Socket closed when under high load (P2P)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1518]
Using 1.3.1-91 Android with 1.3.0.1-2 .NET msft

The scenario
- 4 android LiteServs (3 genymotion (Android 6.0.0), 1 Nexus 7 - 6.0.1)
- 2 .NET LiteServs (Windows 10, on same box, different ports)

Start continuous push replications
- Android 1 -> .NET 1, 2
- Android 2 -> .NET 1, 2
- Android 3 -> .NET 1, 2
- Android 4 -> .NET 1, 2
- .NET 1 -> Android 1, Android 2, Android 3, Android 4
- .NET 2 -> Android 1, Android 2, Android 3, Android 4 

Load 10,000 docs to each Listener and verify that the docs replicate to each db and show up in the changes

Scenario - https://gist.github.com/sethrosetter/36bb2bce1331b4831bf55ee8c6122628

Test will blow up with the below exceptions
https://gist.github.com/sethrosetter/d3c3eb4c547fd2532ca932e161d7399a

**Comment by hideki** [comment]
This could be caused by same root cause with #1539 and #1481
