### ISSUE TITLE
CBLite controlled Pull and Push Sync?

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1519]
Hi All,
 Use Case on an android app:
1)Document A with rev1 created by CBLClient with channel CH1. Document A now belongs to User A.
2)Document A is now at CBserver.
3)Application data wipeout/cleared/uninstalled by user now.
4)Again on application is installed and launched , client need to fetch Document A from CSserver first before creating the Document A.

Queries:
1)What are the ways to fetch the document first from the server before client updating/creating it?
2)How to know the number of documents belonging to a user at the server and what is the end point to fetch all documents.?
3)How getCompletedChangesCount and getChangesCount work?
https://github.com/couchbase/couchbase-lite-java-core/blob/ab22e39d6022723d0a1a445f01a17b250fd6a111/src/main/java/com/couchbase/lite/replicator/Replication.java#L443

https://github.com/couchbase/couchbase-lite-java-core/blob/ab22e39d6022723d0a1a445f01a17b250fd6a111/src/main/java/com/couchbase/lite/replicator/Replication.java#L451

4) when client pushes document A before fetching ,Is there a way to drop the document if already exists at CBserver using Sync Gateway?

@hideki pls share your thoughts..

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

> 1)What are the ways to fetch the document first from the server before client updating/creating it?

If your app run pull replicator, the replicator should refetch the doc from sync gateway. Application should block to create new doc till replication is completed.

> 2)How to know the number of documents belonging to a user at the server and what is the end point to fetch all documents.?

CBL does not support this. you might need to query server directly? Sorry I am not familiar with this.

> 3)How getCompletedChangesCount and getChangesCount work?

- getCompletedChangesCount() -> Number of document changes CBL already knows by _changes REST API. If it is middle of replication, this number keeps increasing.
- getChangesCount() -> Number of document changes CBL already replicated. 

> 4) when client pushes document A before fetching ,Is there a way to drop the document if already exists at CBserver using Sync Gateway?

I believe this could create conflicted document. So application need to solve the conflict if necessary.

Hope my answer helps you.

Happy Thanksgiving!

**Comment by NitzDKoder** [comment]
@hideki A very Happy Thanksgiving Day!

"If your app run pull replicator, the replicator should refetch the doc from sync gateway. Application should block to create new doc till replication is completed."

Assume there are 1.....5555 ...9999 documents at server..
5555 doc is already with  server and client need to fetch from server before we create 5555 doc from client..

How can we achieve this?

"I believe this could create conflicted document. So application need to solve the conflict if necessary."

We are looking for solution where in the above scenario there is no conflict. i.e fetch document first from server and then decide on create it or not.

Thanks
Nithin

**Comment by hideki** [comment]
> How can we achieve this?

Simply not allowing to create new document till pull replication is completed could be enough?

**Comment by hideki** [comment]
Hi @NitzDKoder,

Can you solve this problem? Please update.

**Comment by hideki** [comment]
as we don't have detailed information. I will close this ticket. If you are still facing this issue. please reopen the ticket.
