### ISSUE TITLE
494 BAD_ID error when replicating DB with document without id

### ISSUE THREAD

**Issue by MrYoda** [couchbase/couchbase-lite-java-core#1531]
Hi there!

This error happens only for dbs with one strange document, I do not know how it appears in my db, and I can not delete it:
![](http://joxi.ru/zANGdPUBjGRqr9.jpg)
Its source:
```
{
   "db_name": "test",
   "doc_count": 16842,
   "doc_del_count": 0,
   "update_seq": 90339,
   "purge_seq": 0,
   "compact_running": false,
   "disk_size": 831918200,
   "data_size": 829622622,
   "instance_start_time": "1481647979662403",
   "disk_format_version": 6,
   "committed_update_seq": 90339
}
```
Replication "ubuntu couchdb - ubuntu couchdb" works well, even this strange document replicates from master to slave.

I'm using library version 1.3.1 with CouchDB 1.6.0.

Excuse me for so few information. May be anybody know how to fix or to around it.

**Comment by hideki** [comment]
Hi @MrYoda,
Sorry for slow response. Do you still face this issue?
Was the document created by CBL? Could you please provide details?

**Comment by hideki** [comment]
as we don't have detailed information. I will close this ticket. If you are still facing this issue. please reopen the ticket.
