### ISSUE TITLE
Not able to browse the forestDB file when it is encrypted(ForestDB + libcrypto or SQLCipher)

### ISSUE THREAD

**Issue by nsathiyamoorthy** [couchbase/couchbase-lite-java-core#1532]
Hi Folks,

**Android:**

I'm not able to open the ForestDB file when it is encrypted with [ForestDB + libcrypto or SQLCipher](http://developer.couchbase.com/documentation/mobile/1.3/guides/couchbase-lite/tech-notes/cbl-encryption/index.html).
ForestDB file without encryption is browsable using SQLite Browser.

**Android encryption db with [Couchbaseliteviewer](https://github.com/couchbaselabs/CouchbaseLiteViewer):**

DBfile with encryption is not openable using SQLite browser or Couchbaseliteviewer.
DBfile with encryption is greyed out when browsing through this tool

**IOS:**

DB file without encryption is browsable with Couchbaseliteviewer.

**iOS encrytion db with Couchbaseliteviewer:**

Not tested.

Please help us which tool can be used to open forestDb file in android case.

Thanks
N Sathiyamorrthy

**Comment by hideki** [comment]
Hi @nsathiyamoorthy,
I believe  Couchbase Lite Viewer does not support SQLCipher and ForestDB + libcrypto.

**Comment by djpongh** [comment]
Hideki, you are correct. Maybe something for a future release.

**Comment by NitzDKoder** [comment]
@hideki how currently do you see the data inside dB when dB is encrypted?

**Comment by NitzDKoder** [comment]
@hideki pls help on this..

**Comment by hideki** [comment]
@NitzDKoder,
So far, I haven't had a chance to check the data inside the encrypted database.
You could see the data by customizing Couchbase Lite Viewer (https://github.com/couchbaselabs/CouchbaseLiteViewer).
