### ISSUE TITLE
Query by keys won't work in certain cases

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-java-core#1537]
_From @mvysny on December 22, 2016 11:13_

When searching for documents indexed by a composite key (a list of strings), the view in some cases finds no documents. I am attaching a sample project to demonstrate the issue, just run it with ./gradlew - it will run the test and the test should fail (at least it fails for me, on Ubuntu 16.10 x86-64 java 8).

_Copied from original issue: couchbase/couchbase-lite-core#42_

**Comment by borrrden** [comment]
_From @mvysny on December 22, 2016 11:14_

[cblbug.zip](https://github.com/couchbase/couchbase-lite-core/files/668603/cblbug.zip)
I'm using CouchBase Lite 1.3.1 with ForestDB

**Comment by borrrden** [comment]
_From @mvysny on December 22, 2016 11:16_

When I switch to SQLite the test case succeeds, so this looks like a ForestDB issue.

**Comment by hideki** [comment]
Duplicated: https://github.com/couchbase/couchbase-lite-java-core/issues/1536
