### ISSUE TITLE
Small load - ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1539]
Using 1.4-4
Using Sync Gateway 1.3.1-16

Failing test - http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/31/testReport/testsuites.listener.shared.client_sg/test_replication/test_verify_open_revs_with_revs_limit_push_conflict/

Logs - http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/lastSuccessfulBuild/artifact/results/logs/LiteServAndroid-test_verify_open_revs_with_revs_limit_push_conflict-2017-01-03%2015%3A48%3A15.399162.txt

**Comment by hideki** [comment]
LogCat - Out of Memory

https://gist.github.com/hideki/cf835f5305f4eda19f981e7853b76775

**Comment by hideki** [comment]
Maximum memory size per application on Android API 16 with 768x1280 (320dpi) is around 48MB.

**Comment by hideki** [comment]
ref: https://github.com/couchbase/couchbase-lite-java-core/issues/1481
