### ISSUE TITLE
_replicate REST API with one-shot returns immediately.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1540]
_replicate REST API with one-shot should wait till the replication finishes.

This issue is originally reported on the couchbase forum.
https://forums.couchbase.com/t/replication-rest-api-error-handling/11311

**Comment by dieseldjango** [comment]
Just to be clear, I am seeing the request wait until replication finishes, it's just not clear to me how I'm supposed to determine if the replication succeeded, and if it failed, why. When I tested replication against a bogus target URL:

```
curl -v -X POST --header 'Content-Type: application/json' --data '{"source": {"url": "http://localhost:5000"}, "target": "db2", "continuous":false}' --header 'Accept: application/json' 'http://user:password@localhost:5984/_replicate'
```

After the replication finished, the response was simply this:

```
{"session_id":"repl003"}
```

The docs say there should also be an "ok" field. Am I to infer from the fact that it's missing that the replication failed? Should there not be some status code or message to provide more insight into the failure? Meanwhile, CB Lite was logging the error to my console:

```
Jan 05, 2017 4:10:40 PM com.couchbase.lite.util.SystemLogger w
WARNING: RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {GET, http://localhost:5000/_local/ec0f90145377fdd6580162bd2e8320590552e4cc}: executeRequest() Exception: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:5000.  url: http://localhost:5000/_local/ec0f90145377fdd6580162bd2e8320590552e4cc
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:5000
```

**Comment by hideki** [comment]
@dieseldjango, As you wrote, the response should include `ok` field.
https://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/server/post-replicate/index.html
