### ISSUE TITLE
Not all updates propagating while under load

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1572]
https://github.com/couchbase/couchbase-lite-ios/issues/1558
-------------------------
I'm not sure if this issue lives here but just a guess at the moment. 

During testfest today, using @jamiltz's new doc load tool, we found a scenario where doc updates fail to sync intermittently

Using:
- iOS 1.4-29
- Android 1.4-25

Sync Gateway
- 1.4-35 (DI)

Steps to repro:
- Add 5000 docs using the doc loader tool
- Check 5 docs in the list on the iOS device
- Stop doc load and wait for all docs to sync
- The other clients (Android) see 3-4 of the 5 updates.
- Reseting the app allows all the updates to sync. 

Todo:
- [ ] Find where in the system this inconsistency is happening

**Comment by hideki** [comment]
Hi @sethrosetter
- Did QA execute Functional Test with Distributed Index?

**Comment by sethrosetter** [comment]
@hideki We have run the sync gateway and client tests with DI enabled

**Comment by hideki** [comment]
@sethrosetter 
During next TestFest, can we test both without DI and with DI?

**Comment by sethrosetter** [comment]
@hideki. Yes

**Comment by sethrosetter** [comment]
Using Android 1.4-44, iOS 1.4-41, SG 1.4-98, this is not reproducible
