### ISSUE TITLE
[Functional Test] 1.4-30 ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1574]
Using Nexus 6P api 25 Device and CBL Android 1.4-30

ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

Failing test - http://uberjenkins.sc.couchbase.com:8080/job/android-listener-client-sync-gateway/85/testReport/junit/testsuites.listener.shared.client_sg/test_replication/test_client_to_sync_gateway_complex_replication_with_revs_limit/

Failing test adb logcat - http://uberjenkins.sc.couchbase.com:8080/job/android-listener-client-sync-gateway/85/artifact/results/logs/LiteServAndroid-test_client_to_sync_gateway_complex_replication_with_revs_limit-2017-01-27%2017%3A18%3A56.641005.txt

**Comment by hideki** [comment]
@raghusarangapani run the functional test with real device 02/01/2017. And all functional test passed.
http://uberjenkins.sc.couchbase.com:8080/job/android-listener-client-sync-gateway/114/console

If we observed the same failure with future functional test execution, please reopen this ticket.

**Comment by sethrosetter** [comment]
Seeing it in a latest run - http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/116/testReport/junit/testsuites.listener.shared.client_sg/test_replication/test_initial_pull_replication_True_/

**Comment by hideki** [comment]
FYI: @sethrosetter and @raghusarangapani,

I currently run P2P sanity test with using the real device. I could observe `ConnectionError` intermittently. I also run `ping <ip of real device>`, and `ping` returns `Request timeout` for 30 times at the same time. So I believe the device or PC is out of network for  120sec (4sec * 30 times). This network  issue causes `ConnectionError`.

**Comment by raghusarangapani** [comment]
Tried running the test with the device connected to dantest with couchbase-mobile wifi. dantest has genymotion running jenkins jobs and the device interferes with the jobs causing them to fail. Seth and I decided that we will run all jobs on genymotion for now.

**Comment by hideki** [comment]
As we don't execute functional test with real device, I will move this ticket to backlog, and remove the `1.4.0` milestone tag.

**Comment by hideki** [comment]
duplicated with #1592 ? I will close this.
