### ISSUE TITLE
Updates not propagating to SQLite Client

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1599]
Using SG 1.4-91 (di)

API nexus 6p emulator with android 1.4-43 (SQLite)
    - Other user creates list, and tasks
    - Shares with Android
    - Other user checks all tasks
    - List updates not propagating

Maybe an emulator issue? Possibly due to emulator

**Comment by hideki** [comment]
@sethrosetter Same issue with #1572 ?

**Comment by hideki** [comment]
After Feb 16th Test Fest, I installed Todo for Android with SQLite to 2 real devices and 1 emulator (API 19 stack emulator with ARM). And I tested this scenario. But I can not reproduce this.

**Comment by hideki** [comment]
Hi @sethrosetter 
- Did we use Distributed Index for the last TestFest?
- Did QA execute Functional Test with Distributed Index?

**Comment by sethrosetter** [comment]
I'm pretty sure we are hitting this https://github.com/couchbase/sync_gateway/issues/2068 which @adamcfraser thinks may have be exacerbated by https://github.com/couchbase/sync_gateway/pull/2211

**Comment by hideki** [comment]
@sethrosetter Can we close this ticket as we already have the ticket in sync_gateway Issues?

**Comment by sethrosetter** [comment]
I think this can be closed.
