### ISSUE TITLE
Port multiple queries for view test from .NET

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1601]
During test fest, we saw a stale query using Android 1.4-44 (ForestDB). Upon investigation, we saw that multiple queries were created for the view. After fixing the sample app to only create on view, the issue went away.

**Comment by hideki** [comment]
.NET unit test TestMultipleQueriesOnSameView
https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Tests.Shared/ViewsTest.cs#L2136

**Comment by hideki** [comment]
PR: https://github.com/couchbase/couchbase-lite-android/pull/1079

**Comment by hideki** [comment]
The issue is not reproducible by the ported unit test.
