### ISSUE TITLE
1.x: Leftover replication threads prevent application exit.

### ISSUE THREAD

**Issue by HodGreeley** [couchbase/couchbase-lite-java-core#1604]
This issue is consistently reproducible using CBL 1.3.1 on a Macbook Pro running OS X 10.11.6.
Java version 1.8.0_92.

- JavaFX application
- Start a simple continuous replication (client and SG on same machine)
- No replication activity pending
- Stop replication before ending app

Result: App hangs with CBLReplicationExecutor threads in a WAIT state.

OkHttp connection pool threads also hang around, but timeout.
Okio watchdog thread does not exit.
Thread-1 (?) remains in WAIT
Thread-3 (?) shows as RUNNING.

Shutdown code:

    changesMonitor.stop();  // ends changes monitor thread
    liveQuery.stop();             // Ends an all docs live query
    DBService.getInstance().stopReplication();  // Calls stop on push and pull replications
    db.close();
    db.getManager().close();

    Platform.exit();  // JavaFX terminate app

**Comment by tikimcfee** [comment]
Giving this a quick ping as well, as I think it may be related to my issue (#1609). Might be that the thread is holding on to some files and causing the recursive file deletion call to fail.

**Comment by hideki** [comment]
I wrote simple JavaFX app with CBL to reproduce this issue. However, the application exits immediately. CBL version I use is v1.4.0.
https://gist.github.com/hideki/e79bf9426e87b3623340ffdc12fd764b

I will close for now. If the issue is still reproducible, please reopen the ticket.
