### ISSUE TITLE
Database deletion problem (seen in #1498, need a little insight if possible)

### ISSUE THREAD

**Issue by tikimcfee** [couchbase/couchbase-lite-java-core#1609]
Hey guys, happy Friday to ya.

I hate to bring this one back up (#1498) as I see it appears to be closed up in 1.4, but unfortunately I'm running in to this back in 1.3.1. Reproduction is pretty similar to what that ticket mentions, but the problem occurs whenever we're trying to remove a user's set of data so they can be totally signed out. I understand it's unlikely that there'd be a fix for this as you're moving on to 1.4.1+ and 2.0 stuff, but is there any insight we could use to guard against this, or perhaps get this working.

We extensively use:
- A single push replicator
- A single pull replicator
- More than a couple live queries (and absolutely certain they are unsubscribed from)

#1498 seems to mention threads holding up access to the db, so might there be some way to reach in and shut them down? Perhaps force some retries?

**Comment by djpongh** [comment]
I know this doesn't answer your question but 1.4.0 has just been released and is available on our downloads page (https://www.couchbase.com/downloads).

**Comment by djpongh** [comment]
Hopefully you found a workaround for 1.3.1. Unfortunately we don't have plans for another update to 1.3.
