### ISSUE TITLE
push replication filter with REST api in Couchbase Lite Not working.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1610]
CBL 1.4 used.

@hideki we followed the same link(https://wiki.apache.org/couchdb/Replication#Filtered_Replication) and we end up getting.

"No ReplicationFilter registered for filter 'pushfilter/bystate'; ignoring"

error..

REST:

https://developer.couchbase.com/documentation/mobile/1.3/references/couchbase-lite/rest-api/index.html#!/server/post_replicate

filter: "pushfilter/bystate",

Native:
https://developer.couchbase.com/documentation/mobile/1.3/references/couchbase-lite/couchbase-lite/replication/replication/index.html

String filter { get; set; }

REST:
How is DB setFilter handled in Listener when REST request is made?

Native:

https://developer.couchbase.com/documentation/mobile/1.3/references/couchbase-lite/couchbase-lite/database/database/index.html#void-setfilterstring-name-filterdelegate-delegate

void setFilter(String name, FilterDelegate delegate)

We dont see any rest API for the same.. pls confirm..

Example:

 ```
   //design doc

    03-07 04:13:31.279 14314-14837/com.kodiak.ui D/[HTML5LOG]: jscde.ptx.ptxSyncCB()-> processData()-> {"error":null,"data":{"seq":7,"doc":{"_rev": "1-c73ba28c68880272758ebb003ce47e6f",
    "_id": "_design/pushfilter",
    "filters": {
                   "bystate": "function(doc, req) {if(doc.state == \"pending\" || doc.state == \"deletePending\") {return true;} else {return false;}}"
    }
    },"id":"_design/pushfilter","changes":[{"rev":"1-c73ba28c68880272758ebb003ce47e6f"}]}}


    //PUSH Filter 

    03-07 04:14:03.789 14314-14837/com.kodiak.ui D/[HTML5LOG]: cblPtxInterface.syncManager()-> doStartPost()-> Start PUSH Sync = {
                   "source": "ptxdata",
                   "target": {
                                  "url": "https://919986279039:8e599e5c26e9ba5a671885d2064d21da@syncqc7.kodiakhandset.com/ptxdata"
                   },
                   "continuous": true,
                   "filter": "pushfilter/bystate"
    }

    //CBL error

    03-07 04:14:03.879 14314-17603/com.kodiak.ui W/System.err: [03/07 04:14:03.892] [12] Sync: PusherInternal{https://---:---@syncqc7.kodiakhandset.com/ptxdata, push, 2f1a4}: No ReplicationFilter registered for filter 'pushfilter/bystate'; ignoring

```

Thanks
Nithin

.

**Comment by NitzDKoder** [comment]
@hideki Just did a bit of code walk-though/ referencing .

1)Replication setFilter is done here.
https://github.com/couchbase/couchbase-lite-java-core/blob/1.4.0/src/main/java/com/couchbase/lite/router/Router.java#L812
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Manager.java#L687

2) DB set filter  REST _design doc happens here isnt? 
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L532

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L542


PS: Yet to do a DEBUG with a REST request.

Thanks
Nithin

**Comment by NitzDKoder** [comment]
@hideki 
**setFilterCompiler** was not called 
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L201


https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L173
"this.pendingAttachmentsByDigest = new HashMap<String, Object>();"

Called **setFilterCompiler** after above and things are working as intended.

ReplicationFilterBlockRhino methods are hit and filter is applied.

https://github.com/couchbase/couchbase-lite-java-javascript/blob/e4a24843bb5ecfd563d201194722b0daf15d8d80/src/main/java/com/couchbase/lite/javascript/ReplicationFilterBlockRhino.java

Logs:

```
"[03/13 06:15:11.538] [5] Sync: PusherInternal{https://---:---@syncqc7.kodiakhandset.com/ptxdata, push, a40f0}: beginReplicating() called
[03/13 06:15:11.539] [5] Database: getFilter : pushfilter/bystate
[03/13 06:15:11.540] [5] Database: filterCompiler : com.couchbase.lite.javascript.JavaScriptReplicationFilterCompiler@43a8da78
[03/13 06:15:11.542] [5] Database: sourceCode : function(doc, req) {if(doc.state == "pending" || doc.state == "deletePending") {return true;} else {return false;}}
[03/13 06:15:11.543] [5] Database: language : javascript
[03/13 06:15:11.669] [5] Database: setFilter filterName: pushfilter/bystate
[03/13 06:15:11.670] [5] Database: setFilter ReplicationFilter: com.couchbase.lite.javascript.ReplicationFilterBlockRhino@441c7658
[03/13 06:15:11.671] [5] Sync: compilePushReplicationFilter com.couchbase.lite.javascript.ReplicationFilterBlockRhino@441c7658
"
```


Pls share you thoughts why the setFilterCompiler was not called.


Thanks
Nithin

**Comment by hideki** [comment]
@NitzDKoder ,
Can you share how the app set the javascript filter and how the app use it with the replicator? `curl` command is preferable. Thanks!

**Comment by NitzDKoder** [comment]
@hideki 

Database Class java side:
**setFilterCompiler(new JavaScriptReplicationFilterCompiler());**

dependencies {
    compile 'com.squareup.okhttp3:okhttp:3.3.1'
    compile 'com.fasterxml.jackson.core:jackson-core:2.5.0'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.5.0'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.5.0'
    compile 'com.github.oxo42:stateless4j:2.4.0'
   **compile 'com.couchbase.lite:couchbase-lite-java-javascript:1.3.1'**
}

JavaScript side:
 ```
 //design doc

   03-07 04:13:31.279 14314-14837/com.kodiak.ui D/[HTML5LOG]: jscde.ptx.ptxSyncCB()-> processData()-> {"error":null,"data":{"seq":7,"doc":{"_rev": "1-c73ba28c68880272758ebb003ce47e6f",
   "_id": "_design/pushfilter",
   "filters": {
                  "bystate": "function(doc, req) {if(doc.state == \"pending\" || doc.state == \"deletePending\") {return true;} else {return false;}}"
   }
   },"id":"_design/pushfilter","changes":[{"rev":"1-c73ba28c68880272758ebb003ce47e6f"}]}}


   //PUSH Filter 

   03-07 04:14:03.789 14314-14837/com.kodiak.ui D/[HTML5LOG]: cblPtxInterface.syncManager()-> doStartPost()-> Start PUSH Sync = {
                  "source": "ptxdata",
                  "target": {
                                 "url": "https://919986279039:8e599e5c26e9ba5a671885d2064d21da@syncqc7.kodiakhandset.com/ptxdata"
                  },
                  "continuous": true,
                  "filter": "pushfilter/bystate"
   }
```
not sure about curl level..
Thanks
Nithin

**Comment by hideki** [comment]
# How to set the filter function through REST API

### How to set Filter Function by REST API

Example:
```curl
curl -X PUT \
  http://192.168.57.101:5984/cblite-test/_design/myddoc \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 87d9bf60-2c44-1d46-d0dc-9e47b7b7c145' \
  -d '{
	"_id":"_design/myddoc",
	"filters": {
		"myfilter": "function(doc, req) { if (doc.type && doc.type == \"foo\") { return true; } else { return false; } }"
	}
}'
```
Link: https://wiki.apache.org/couchdb/Replication#Filtered_Replication

### How to set filter function to the replicator

Example
```curl
curl -X POST \
  http://192.168.57.101:5984/_replicate \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 717c7fcd-7195-584f-b4c4-68dff597057c' \
  -d '{
	"source":"cblite-test",
	"target":"http://10.17.1.241:4984/db", 
	"continuous": true,
	"filter":"myddoc/myfilter"
}'
```
Link: https://wiki.apache.org/couchdb/Replication#Filtered_Replication

### How to set filter function to `/_changes` REST API

Example:
```curl
curl -X GET \
  'http://192.168.57.101:5984/cblite-test/_changes?filter=myddoc%2Fmyfilter' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: ecd04b05-04ba-b688-57a2-8426958faef2'
```
Link: http://docs.couchdb.org/en/1.6.1/couchapp/ddocs.html#filter-functions


### NOTES:
- CBL does not support to use a view function as a filter function.

**Comment by NitzDKoder** [comment]
@hideki is the fix available we need this feature..

**Comment by hideki** [comment]
Hi @NitzDKoder,
This feature is available since v1.2.1 or 1.3.0.

**Comment by NitzDKoder** [comment]
@hideki Does not work in 1.4.1

We added  below to make it work.Please check.

Database Class java side:
added
setFilterCompiler(new JavaScriptReplicationFilterCompiler());

https://github.com/couchbase/couchbase-lite-java-core/blob/1.4.0/src/main/java/com/couchbase/lite/Database.java#L173


dependencies {
compile 'com.squareup.okhttp3:okhttp:3.3.1'
compile 'com.fasterxml.jackson.core:jackson-core:2.5.0'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.5.0'
compile 'com.fasterxml.jackson.core:jackson-databind:2.5.0'
compile 'com.github.oxo42:stateless4j:2.4.0'
compile 'com.couchbase.lite:couchbase-lite-java-javascript:1.3.1'
}
compile 'com.couchbase.lite:couchbase-lite-java-javascript:1.3.1 dependency added and built couchbase-lite-java-core-1.4.0

**Comment by hideki** [comment]
@NitzDKoder 
I tested this with [LiteServ](https://github.com/couchbase/couchbase-lite-android-liteserv) with 1.4.0 by manual testing. So you don't need to add 1.3.1. (I don't recommend to mix versions.)
Thanks!

**Comment by NitzDKoder** [comment]
@hideki but for us 1.4.0 failed to work..are we missing the context here?

**Comment by hideki** [comment]
@NitzDKoder,
I don't know why the replication filter does not work with the app you are developing.
Could you please verify if the JavaScript filter function, `/_design/{ddoc}` REST API to set filter function, and `/_replicate` REST API work with LiteServ sample app or ToDo PhoneGap sample?
