### ISSUE TITLE
Replication Lifecycle Spec

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-java-core#1619]

**Comment by djpongh** [comment]
In order to plan test scenarios, need a document from dev detailing the following:
- Diagram of the possible replication states for the 2.0 replicator (I.e. Active, Idle …)
- All of the platform notifications that initiate a state change (I.e Endpoint now longer reachable, wifi disabled on device, etc.)

**Comment by hideki** [comment]
transferred to https://github.com/couchbase/couchbase-lite-core/issues/94
