### ISSUE TITLE
1.x: Rev tree pruning inconsistent with SG

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-java-core#1621]
From CBL .Net:
 https://github.com/couchbase/couchbase-lite-net/issues/831

**Comment by hideki** [comment]
I reviewed CBL Java codes. Document pruning codes of CBL Java is equivalent with iOS implementation. Like iOS implementation, CBL Java keeps `maxRevTreeDepth` number of revision history for each leaf node.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L2591-L2600
