### ISSUE TITLE
Adapt to C4Query API changes

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-java-core#1648]
See couchbase/couchbase-lite-core#245 "Remove default columns from query results (docID, body, sequence…)"
This is on a LiteCore branch `feature/c4query_cols` until all CBL platforms are ready to update.

**Comment by hideki** [comment]
https://github.com/couchbase/couchbase-lite-core/commit/1224774d13920f362a6d6caa1dd3e973e368b0e4
