### ISSUE TITLE
NullPointerException in RemoteBulkDownloaderRequest and docs not fetched.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1677]
Hi Folks,

1)
```
[10/25 10:29:48:785] [396] ChangeTracker: ChangeTracker{https://---:---@syncqc3.company.com/ptxdata, OneShot, @7444889}: /changeTrackerReceivedChange: {seq=5858578, id=s916600055010_ptx1508756581520_meta.doc, changes=[{rev=3-ca3fecd92f662c58842a2528253960cb}]}
```

**Changetracker gets some data.**

2)
``` 
Line 3607: [10/25 10:29:48:109] [386] RemoteRequest: com.couchbase.lite.replicator.RemoteBulkDownloaderRequest[/ptxdata/_bulk_get]: executeRequest() Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File com.couchbase.lite.BlobStore.tempDir()' on a null object reference.  url: https://919880611446:e29fb34831fd1209b4bb985def56a3f0@syncqc3.company.com/ptxdata/_bulk_get?revs=true&attachments=true
Line 3612: [10/25 10:29:48:111] [386] Sync: PullerInternal{https://---:---@syncqc3.company.com/ptxdata, pull, fbdb9}: Progress: set error = java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File com.couchbase.lite.BlobStore.tempDir()' on a null object reference
```

RemoteBulkDownloaderRequest executeRequest gets nullpointer exception. **store** seems null.

https://github.com/couchbase/couchbase-lite-java-core/blob/1.4.0/src/main/java/com/couchbase/lite/BlobStoreWriter.java#L98

3) Changetracker goes wait state [396] CBLite: Waiting: true

@hideki pls share your thoughts..this was seen while checking https://github.com/couchbase/couchbase-lite-java-core/issues/1670

Logs:

[Exception.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1474724/Exception.txt)

Thanks
Nithin

**Comment by hideki** [comment]
@NitzDKoder 

`store` variable is `null` because of following line.
``
> [10/25 10:29:25:296] [324] Database: BlobStore: Blob store uses unrecognized encryption ''

https://github.com/couchbase/couchbase-lite-java-core/blob/1ae4c0d1873d1287c725406ceaf8035014fb4927/src/main/java/com/couchbase/lite/BlobStore.java#L111

Empty `ENCRYPTION_MARKER_FILENAME` file could be created following lines.
https://github.com/couchbase/couchbase-lite-java-core/blob/1ae4c0d1873d1287c725406ceaf8035014fb4927/src/main/java/com/couchbase/lite/BlobStore.java#L132-L154

Did you customize encryption related code?

**Comment by NitzDKoder** [comment]
@hideki https://github.com/couchbase/couchbase-lite-java-core/issues/1649
We do this in our app..will check on encryption on update..

**Comment by hideki** [comment]
@NitzDKoder 
FYI: We don't support Encryption with PhoneGap. As CBL is an open source project, could you please customize the codes with own risk?

**Comment by NitzDKoder** [comment]
@hideki encrpytion works for us in most of the devices .in odd devices we see issue..
What do mean enception with phonegap? Do you mean enabling the db encrytion? .

Step 1 Basically we open db at android Platform  level with encrption key.
Step 2 phonegap rest level db access will use that encrypted then on.

Make sense?

Thanks
Nithin

**Comment by hideki** [comment]
@NitzDKoder 
Encryption works with CBL. However, CBL Rest API does not provide to create the encrypted database. We could not provide the same level of help for un-officially supported features.

**Comment by NitzDKoder** [comment]
@hideki

Currently we do

Step 1 Basically we open db at thin android Platform level with encrption key.
Step 2 phonegap rest level open db will use that encrypted db then on.

**Comment by NitzDKoder** [comment]
@hideki 

Same device encryption is working.
**"BlobStore: Blob store uses unrecognized encryption "**

We are seeing this for the first time. And not able to reproduce it again.

**Comment by djpongh** [comment]
Please move issues such as these to the forums.
