### ISSUE TITLE
  CBL pull sync behaviour with syncgateway.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1678]
Hi folks,

1)When CBL(user A) is busy fetching old seq numbered docs.With android continuous pull on.

2)Will the latest pushed docs(It will processed by Syncgateway and belongs to user A) will be part of the changes immediately?
Line 25410: [11/14 17:10:44:653] [1980] CBLite: —> Added: {s919888880032_ptx1510659644491_meta.doc #1-bda4d3a410a0f2934e78397acb1f28d5 @30} as seq 30

**Requirement: Get the latest change belongs to client/User in _changes.**

Android CBL Continous pull is as below.

ChangeTracker{https://---:---@syncqc3.mydomain.com/ptxdata, OneShot, @3e2a4db}: Making request to POST [https://---:---@syncqc3.mydomain.com/ptxdata/_changes?feed=longpoll&heartbeat=90000&style=all_docs&since=8414336&filter=sync_gateway%2Fbychannel]

Does the **descending** filed will help here? Syncgateway is cable of obeying the **descending** ?

"descending (boolean) – Return the change results in descending sequence order (most recent change first). Default is false."
http://docs.couchdb.org/en/2.0.0/api/database/changes.html

Thanks
Nithin

**Comment by djpongh** [comment]
This was asked and answered in the forums.
