### ISSUE TITLE
OutOfMemoryError changeTracker consuming more heap.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1681]
Hi Folks,

1)App design same as below
couchbase/couchbase-lite-java-listener#84.

https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin

2) CBL 1.4.1 EE edition used.
https://github.com/couchbase/couchbase-lite-java-core/tree/release/1.4.1

3)@[12/12 14:55:45:283] [10450] Database: heap memory used by the app in **MB:31**
 

changeTracker changeTrackerReceivedChange is happening and  gets data

4)@ [12/12 14:55:52:073] [10450] **Database: heap memory used by the app in MB:127**
/changeTrackerReceivedChange: {seq=12496379, id=s919888881669_ptx1512490513088_meta.doc, changes=[{rev=7-5ccabfd661984434658bafbe6509f5a7}]}

Changetracker adding changes to inbox ~ 700 changes.

**~100mb growth in 7 secs..**

5)12-12 14:56:10.804 E/AndroidRuntime(23162): FATAL EXCEPTION: Thread-waitForPendingFutures[PusherInternal{https://---:---@locqc3.company.com/ptxdata, push, 1317f}]

12-12 14:56:10.804 E/AndroidRuntime(23162): Process: com.aaa.bbbt, PID: 23162

12-12 14:56:10.804 E/AndroidRuntime(23162): java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

PS: same issue seen in 1.4.0 EE CBL.

Logs added:

[ADB.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1552583/ADB.txt)
[cbl_logs.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1552584/cbl_logs.txt)

@hideki do you see this behaviour in your tests? Please share your thoughts.

Thanks
Nithin

**Comment by hideki** [comment]
@NitzDKoder,

Can you identify which component hold a lot of memory? Router class?

Following is just my assumption. Does the app call /_changes API with `include_docs` parameter true? It could consume a lot of memory.

Thanks,
Hideki

**Comment by NitzDKoder** [comment]
@hideki
Yes
_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}

1)yet to to check alloc or heapdump on router class.
2)java stand alone app no heap spike seen.

Any exiting issue on include docs?

**Comment by hideki** [comment]
With current CBL implementation, Router does not check the used memory size. The router tries to allocate memory as necessary as possible. In case there are too many document changes or each document size is large, it could cause the out-of-memory issue.

**Comment by NitzDKoder** [comment]
@hideki 
http://www.filehosting.org/file/details/714145/CBL_HEAP_HIGH.hprof

Here CBL is consuming more than ~100MB. Please check HROF.

**Comment by hideki** [comment]
@NitzDKoder If this is a critical issue for your product, I advise you to reach us through Couchbase customer support.

**Comment by NitzDKoder** [comment]
@hideki sure..
always seen in 2gb and below devices.

**Comment by hideki** [comment]
try to set limit with low number to _changes api
http://docs.couchdb.org/en/1.6.1/replication/protocol.html#pull-only

**Comment by hideki** [comment]
This issue is tracked by customer support. I will close this ticket.
[CBSE-4591](https://issues.couchbase.com/browse/CBSE-4591)

**Comment by NitzDKoder** [comment]
@hideki 

Did you get to check attached HPROF..please confirm..

**LIMIT set at JAVASCRPIT to 10 fro DB changes:**

ptxdata/_changes?since=34008&include_docs=true&style=main_only&**limit=10**&timeout=240000&feed=longpoll

**Remote SYNC with limit 10:**

ptxdata/_changes?feed=longpoll&heartbeat=90000&style=all_docs&since=13158235&**limit=10**&filter=sync_gateway%2Fbychannel]


Still the memory spike of 100mb seen.

Attaching the HPROF most of the data is of CBL objects.

http://ge.tt/30qD2mn2


We have Sample app and documents to reproduce this..Do you need us to share?

Thanks
Nithin

**Comment by hideki** [comment]
@NitzDKoder,
I strongly recommend you to communicate through Couchbase customer support. They track the issue and help customers.

**Comment by hideki** [comment]
@NitzDKoder 

> We have Sample app and documents to reproduce this..Do you need us to share?

YES
