### ISSUE TITLE
Getting older documents even after Deleting and closing database in Couch base lite

### ISSUE THREAD

**Issue by shyamala-tj** [couchbase/couchbase-lite-java-core#1687]
Hi ,

I am using couch base lite in an application having sign in /sign out support. By considering each user id as channel we are creating the documents.Everything is working fine.

But on sign out and sign in using the new user , I am getting previously signed in user documents also even if I delete and close the database on sign out.Checked by stopping replicators and recreating the views also.But no use.Not getting what went wrong.

I am using couch base lite 1.4.0 version.
Here is the APIs  I am calling when user signs out from the application.

self.pushReplication?.stop()
self.pullReplication?.stop()
self.publicPullReplication?.stop()

self.pushReplication = nil
self.pullReplication = nil
self.publicPullReplication = nil

try self.database.delete()
try self.database.close()

**Comment by hideki** [comment]
@shyamala-tj,
It seems the code is swift. I recommend posting the question to https://forums.couchbase.com/c/mobile .
If this is bug, please make a ticket at https://github.com/couchbase/couchbase-lite-ios/issues ?

In general, after database delete, you can not obtain the document from the database.

**Comment by shyamala-tj** [comment]
@hideki 
Thanks hideki.I will post the question to forums.
