### ISSUE TITLE
sync gateway compatibility

### ISSUE THREAD

**Issue by AliAhmadi93** [couchbase/couchbase-lite-java-core#1689]
I use Lite-Core for C development. I ran a replicator in my code for connection to sync gateway. But i received error 403  (403 Forbidden ). i read some issues and so i realize that my problem is mismatch of lite-core version and sync gateway version. so my questions:
1) what is Lite-Core version?
2) what is Sync Gateway version for compatibility with Lite-Core

**Comment by djpongh** [comment]
Filed against wrong repo. Also we do not support accessing LiteCore directly, only through a Couchbase Lite implementation.
