### ISSUE TITLE
Javascript and Native API to know sync is idle or active.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1694]
Hi,

1) Using Android CBL 1.4.1 EE.

2)What is API to know all the changes are synced from server and sync is idle?

3)Total changes at server is 1000.

4)_changes limit is 100.

https://docs.couchbase.com/sync-gateway/current/admin-rest-api.html#/database/post__db___changes

5)
```
/**
         * Continuous replication is caught up and waiting for more changes.
         */
        REPLICATION_IDLE,
```

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/Replication.java#L90

Does the above REPLICATION state will move REPLICATION_IDLE after all the changes are fetched from server or when changes are just received and yet to be fetched?

6)How does REPLICATION_IDLE work when the limit is set to 100?

Thanks

**Comment by NitzDKoder** [comment]
@pasin please share your thoughts.

**Comment by NitzDKoder** [comment]
@snej  please share your thoughts.
**"We have large amount of document on the SyncGW and client is syncing those documents on startup. We would like to know if there is any definitive way of getting to know when all the documents have been synced to local cbl so that we can stop the sync."**

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.

**Comment by snej** [comment]
…or if you're a Couchbase customer, please go through support channels. Thanks.
