### ISSUE TITLE
Add gzip support

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#172]

**Comment by hideki** [comment]
gzip related ios/sync_gateway tickets

https://github.com/couchbase/couchbase-lite-ios/issues/240
https://github.com/couchbase/sync_gateway/issues/238

* ios
  * gzip request - https://github.com/couchbase/couchbase-lite-ios/commit/7d54535f08d2d9e6f47adae5000873d08d4187a7
  * gzip response - https://github.com/couchbase/couchbase-lite-ios/commit/cb27792d982d4197422828244338ba91cecf240c
* sync_gateway
  * gzip request - https://github.com/couchbase/sync_gateway/commit/50379f549ce396c39a14e0641b608a04973f68fb
  * gzip response -  https://github.com/couchbase/sync_gateway/commit/6d2ddc967829e781e786c963efd221286ad64808
