### ISSUE TITLE
Mismatch in rev id's produced on iOS and Java due to missing canonicaljson

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#178]
As mentioned here:

https://github.com/couchbase/couchbase-lite-java-core/pull/175#issuecomment-41364037

> Merging PR, but it looks like revision ID's may not be identical across iOS and Android for the same content?

> Android has no equivalent of CBLCanonicalJSON, which is called at the end of Database.encodeDocumentJSON.

> // Create canonical JSON -- this is important, because the JSON data returned here will be used
// to create the new revision ID, and we need to guarantee that equivalent revision bodies
// result in equal revision IDs.
> NSData* json = [CBLCanonicalJSON canonicalData: properties];
return json;

couchbase-lite-java needs to port CBLCanonicalJSON in order to have identical rev id's with iOS.  

This should not cause any issues, but rather is an optimization.  See https://github.com/couchbase/couchbase-lite-java-core/issues/164#issuecomment-40771079

**Comment by hideki** [comment]
Note to self:
Because CBL Android/Java does not `canonicalize` json, Revision ID which is generated from json is different from iOS one. Also, different Revision ID causes different winning revision picking.

**Comment by hideki** [comment]
Duplicated #878
