### ISSUE TITLE
Out of memory error while compacting

### ISSUE THREAD

**Issue by nickkitto** [couchbase/couchbase-lite-java-core#199]
We started looking into doing a compact at the startup of the app. This is due to the users believing our app slowed down over time, and worked a lot faster from a fresh install (fresh db copy).

First issue I can see in compact is the call
```
database.update("revs", args, "current=0", null);
```
should change to
```
database.update("revs", args, "current=0 AND json IS NOT NULL", null);
```
Theres no point in updating documents to set json to null when it is already null. This speeds up this call greatly for a large db.

Further on it sometimes can throw an out of memory exception. database.execSQL("VACUUM"); seems to be where it happens.
I'm not sure if this is a good idea to do this. This is very expensive if you have a large db (ours is ~400mb). When it doesn't fail (by luck) it takes about 30minutes to complete.
Can we discuss whether this is a good idea? Maybe we should provide a way to compact without vacuuming.

**Comment by hideki** [comment]
This issue could be solved with v1.2.0 release.
