### ISSUE TITLE
Puller: docs not inserted when some docs fail validation due to nested transaction behavior

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#242]
From [google groups](https://groups.google.com/d/msgid/mobile-couchbase/ea5110f9-19bc-4eb7-b0f9-4570dabc17b3%40googlegroups.com?utm_medium=email&utm_source=footer) discussion:

> This means that if I do a Pull replication and have to process about 100 different documents, if the inner transaction that deals with each document fails validation -- even if it is one document -- then the entire 100 documents are not inserted into the local database. That seems like a bug to me since the outer transaction could have documents that pass the validation and hence should be available to the mobile.

**Comment by tleyden** [comment]
I just found an existing test case for this: https://github.com/couchbase/couchbase-lite-android/blob/42d614c644ca2aae72638dac45c4221f004d7805/src/androidTest/java/com/couchbase/lite/replicator/ReplicationTest.java#L3110

**Comment by tleyden** [comment]
After researching it, the Android nested transactions are working as advertised, but we are misusing them.

From the Android source:

```
    /**
     * ..

     * Transactions can be nested.
     * When the outer transaction is ended all of
     * the work done in that transaction and all of the nested transactions will be committed or
     * rolled back. The changes will be rolled back if any transaction is ended without being
     * marked as clean (by calling setTransactionSuccessful). Otherwise they will be committed.
     * ...
     */
    public void beginTransaction()
```

In our codebase however, we are behaving as if we expect the following test to pass:

```
public void testNestedSQLTransactionRollback() throws Exception {

        String schema = "CREATE TABLE docs ( " +
                "        doc_id INTEGER PRIMARY KEY, " +
                "        val TEXT UNIQUE NOT NULL); ";

        LiteTestContext context = new LiteTestContext();
        String dbName = "testNestedSQLTransactionRollback" + System.currentTimeMillis();
        String path = context.getFilesDir() + File.separator + dbName + Manager.DATABASE_SUFFIX;
        SQLiteDatabase sqlDatabase = SQLiteDatabase.openDatabase(path, null, SQLiteDatabase.CREATE_IF_NECESSARY);

        // install schema
        sqlDatabase.execSQL(schema);

        // start outer transaction
        sqlDatabase.beginTransaction();

        // add a doc -- inner transaction 1: COMMITTED
        sqlDatabase.beginTransaction();
        android.content.ContentValues args = new android.content.ContentValues();
        args.put("doc_id", 1);
        args.put("val", "hello");
        long id = sqlDatabase.insert("docs", null, args);
        sqlDatabase.setTransactionSuccessful();
        sqlDatabase.endTransaction();

        // add a doc -- inner transaction 2: CANCELLED
        sqlDatabase.beginTransaction();
        args = new android.content.ContentValues();
        args.put("doc_id", 2);
        args.put("val", "hello2");
        id = sqlDatabase.insert("docs", null, args);
        sqlDatabase.endTransaction();  // CANCELLED since we don't call setTransactionSuccessful()

        // finish outer transaction
        sqlDatabase.setTransactionSuccessful();
        sqlDatabase.endTransaction();

        CountDownLatch doc1Persisted = new CountDownLatch(1);

        // query db to make sure both docs are there
        android.database.Cursor cursor = sqlDatabase.rawQuery(
                "SELECT * FROM docs", null);
        while (cursor.moveToNext()) {
            int docId = cursor.getInt(0);
            byte[] val = cursor.getBlob(1);
            String.format("docid: %s val: %s", docId, new String(val));
            if (docId == 1) {
                doc1Persisted.countDown();
            }
        }

        assertEquals(0, doc1Persisted.getCount());


    }
```

but it fails, which is inline with the Android API docs.

Specifically, in our codebase:

* PullerInternal.insertDownloads() starts an outer transaction
* For each doc to insert
    * PullerInternal.insertDownloads() calls Database.forceInsert()
    * Database.forceInsert() starts a nested transaction
    * If validation passes, the nested transaction is committed
    * If validation fails, the nested transaction is cancelled / aborted
* PullerInternal.insertDownloads() commits the outer transaction

But if any of the nested transactions are cancelled, then all changes will be rolled back.

**Comment by tleyden** [comment]
@snej can you look at the previous comment and let me know if fmdb nested transactions behave differently?

**Comment by tleyden** [comment]
Related ticket: https://github.com/couchbaselabs/TouchDB-Android/issues/3#issuecomment-3972981

**Comment by tleyden** [comment]
@snej also, can you explain the value-add of having [insertDownloads](https://github.com/couchbase/couchbase-lite-ios/blob/090a27989e9bbdf574f5b84015a8bcc8e4d7c4b4/Source/CBL_Puller.m#L645) wrap everything in an outer transaction?  Was this for performance, or correctness?

The reason I'm asking is because on Android, if I remove that outer transaction it fixes this issue.  And I'm just wondering what the implications of that might be.

**Comment by snej** [comment]
On iOS we're using the SQLITE [`SAVEPOINT`](https://www.sqlite.org/lang_savepoint.html) commands, which allow a nested transaction to be canceled (via `ROLLBACK`) without losing the results of a previously committed nested transaction.

From the description it sounds like Android is using the older non-nesting SQLite transaction API, and just implementing nesting by keeping track of the nesting level. Then when the final transaction ends it either commits or aborts the entire transaction.

Is it feasible to switch to using explicit `SAVEPOINT` commands to implement transactions?

>can you explain the value-add of having insertDownloads wrap everything in an outer transaction?

Performance. Since a bunch of revisions are about to be added, it's much, much faster to do so inside a transaction. (SQLite's overhead per transaction is tens or hundreds of ms.)

**Comment by rajasaur** [comment]
@snej @tleyden : I tried using explicit SAVEPOINT as iOS does, Please see comments at https://github.com/couchbase/couchbase-lite-java-core/issues/242#issuecomment-47262710,  https://github.com/couchbase/couchbase-lite-java-core/issues/242#issuecomment-47307164 and 
https://github.com/couchbase/couchbase-lite-java-core/issues/242#issuecomment-47341764

**Comment by tleyden** [comment]
@rajasaur thanks for the reminder.  We'll definitely take a look at that once we figure out which direction to go with this.

**Comment by tleyden** [comment]
The comment in the SO post [SQLiteDatabase nested transaction and workaround](http://stackoverflow.com/questions/26106237/sqlitedatabase-nested-transaction-and-workaround) is relevant.

**Comment by snej** [comment]
You should call SAVEPOINT directly instead of using Android's fake nested transactions. See the iOS code.=

**Comment by tleyden** [comment]
@snej the problem with that approach, as I understand it: if we do that, we'll run into the original problem reported in https://github.com/couchbaselabs/TouchDB-Android/issues/3 and we'll end up with the `cannot start a transaction within a transaction` error because:

* We call SAVEPOINT
* Inside the Android SQLiteDatabase insert() method, it calls [acquireAndLock()](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.0.4_r2.1/android/database/sqlite/SQLiteStatement.java#112), which in turn calls [beginTransactionNonExclusive()](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.0.4_r2.1/android/database/sqlite/SQLiteStatement.java#247)
* SQLite throws a `cannot start a transaction within a transaction` error.

@rajasaur confirmed this behavior when he tested his [patch](https://gist.github.com/rajasaur/624eb108b358bda9476a) which tries to use SAVEPOINT instead of android's fake nested transactions.

Curious to hear your thoughts -- does it look like to you that the fact that Android SQLiteDatabase insert() method can start transactions makes it impossible to use SAVEPOINT correctly, or do you see a workable approach despite that behavior?

**Comment by Takhion** [comment]
I've just read this issue, and a quick search led to [this](https://code.google.com/p/android/issues/detail?id=38706): maybe using `execSQL` directly would fix it?

**Comment by rajasaur** [comment]
@Takhion : Unfortunately no, See the patch that I attempted at https://gist.github.com/rajasaur/624eb108b358bda9476a which also contains a link to the ticket that you referenced.

**Comment by Takhion** [comment]
@rajasaur what I mean is using `execSQL` also for inserts, instead of `SQLiteDatabase.insert()`, so that as @tleyden said it wouldn't call `acquireAndLock()` and then `beginTransactionNonExclusive()`.

**Comment by snej** [comment]
I don't know the API, but would it be possible to subclass SQLiteDatabase and override the transaction-related methods to use savepoints instead?

**Comment by Takhion** [comment]
Sadly not: `public final class SQLiteDatabase`.

**Comment by hideki** [comment]
Note to self:

ideas to tackle this issue
- Revisit `SAVEPOINT` approach: as @Takhion suggested in previous comment, try `beginTransaction()`/`endTransaction()` for outer transaction and use `SAVEPOINT` for nested transaction
- Call `validateRevision()` before nested transaction. In current code, between `beginTransaction()` and `validateRevision()`, new record is inserted for some scenarios. Need to figure out if it is possible to call `validateRevision()` without insert/update/delete any records.
- Workaround solution: give up outer transaction in case database is set Validation. Need to verify performance.
- Rewrite SQLiteDatabase: it seems this is pretty challenging.

**Comment by hideki** [comment]
Hi @pasin @snej @tleyden @zgramana 

I need your feedback for following approach to fix nested transaction issue on Android.

As @Takhion suggested in previous comment, I tried to apply `SQLiteDatabase.beginTransaction()` and `endTransaction()` for outer transaction, and SQLite's `SAVEPOINT`, `ROLLBACK`, and `RELEASE` for inner transaction. It seems this solution works. Do you have any concern about this approach. Any comments are appriciated. Following is link to code. https://github.com/couchbase/couchbase-lite-java-core/commit/f7fcc93427ffcf1f3b7e2af803b8dc65e08769f8

Mahalo!

**Comment by snej** [comment]
I'm not sure whether SQLite save points are compatible with the older begin/end style transactions. It would be best to look through the SQLite.org website to see if it says anything about that. (It doesn't seem like something a developer would normally do, because normally if you use save points there's no reason to use regular transactions too.)

Aloha!

**Comment by Takhion** [comment]
> I'm not sure whether SQLite save points are compatible with the older begin/end style transactions.

Yes they are! You can read the official documentation [here](https://www.sqlite.org/lang_savepoint.html) and [here](https://www.sqlite.org/lang_transaction.html), but in a nutshell:
> A SAVEPOINT can be started either within or outside of a BEGIN...COMMIT.

**Comment by snej** [comment]
:+1: Sounds good, then!

**Comment by hideki** [comment]
Note to self: Status

#### Note:
SQLite does not support nested transaction. SQLite recommend to use SAVEPOINT for nested transaction: http://sqlite.org/lang_transaction.html

#### Nested transaction:
SQLiteDatabase supports transaction and nested transaction. However it does not behave as we expected.
```
Transactions can be nested. When the outer transaction is ended all of the work done in that
transaction and all of the nested transactions will be committed or rolled back. 
The changes will be rolled back if any transaction is ended without being marked as clean
(by calling setTransactionSuccessful). Otherwise they will be committed.
```
http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#beginTransaction()

#### Nested SAVEPOINT:
With Android API 14 and 15, Nested SAVEPOINT throws Exception. However, this solution works fine with all other Android versions.

#### Combination of SQLiteDatabase transaction and SAVEPOINT:
Based on the test result, it seems this combination works fine. However this is rare combination, so need further investigation.

#### Test result with using Android emulator

Solution  | 2.3.3 (API10) | 4.0 (API14) | 4.0.3 (API15) | 4.1.2 (API16) | 4.4.2 (API19) | 5.0.1 (API21)
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
Transaction for both outer & inner | NG | NG | NG | NG | NG | NG | NG | NG
SAVEPOINT for both outer & inner | OK | NG | NG | OK | OK | OK | OK | OK
Transaction for outer & SAVEPOINT for inner | OK | OK | OK | OK | OK | OK | OK | OK

**Comment by hideki** [comment]
@Takhion Thank you very much for pointing out sqlite documents.

#### Notes from sqlite.org

##### SQLite Transaction and SAVEPOINT are equivalent
```
SAVEPOINTs are a method of creating transactions, similar to BEGIN and COMMIT, 
except that the SAVEPOINT and RELEASE commands are named and may be nested.
```
##### SQLite Transaction does not support nested transaction
```
Transactions created using BEGIN...COMMIT do not nest.
```
##### SQLite SAVEPOINT can be started in Transaction
```
A SAVEPOINT can be started either within or outside of a BEGIN...COMMIT.
```


#### Potential another solution 
* Using SQLite BEGIN...COMMIT for outer transaction is more comfortable than `SQLiteDatabase.beginTransaction()/endTransaction()`. Do experiment the combination of BEGIN...COMMIT and SAVEPOINT...RELEASE.

**Comment by hideki** [comment]
##### Test result of Combination of BEGIN...COMMIT and SAVEPOINT...RELEASE

Solution  | 2.3.3 (API10) | 4.0 (API14) | 4.0.3 (API15) | 4.1.2 (API16) | 4.4.2 (API19) | 5.0.1 (API21)
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
BEGIN...COMMIT for outer & SAVEPOINT...RELEASE for inner | OK | OK | OK | OK | OK | OK | OK | OK

**Comment by hideki** [comment]
Notes from discussion with @pasin

- `SQLiteDatabase.beginTransaction()/endTransaction()` provides lock/unlock. (Thread safe)
- When @pasin worked for CBL Java, he encountered threading issue. He solved it by applying same/similar implementation of Android SQLiteDatabase to Java version.
- Because of  threading issue, it is safer to use SQLiteDatabase.beginTransaction() for outer transaction or 1st level of transaction.
- `SQLiteDabase.beginTransaction()/endTransaction()` internally calls BEGIN...COMMIT...ROLLBACK in SQLiteSession.java

**Comment by hideki** [comment]
Additional Note:
- By switching inner/2nd level transaction to SAVEPOINT...RELEASE from SQLiteDatabase.beginTransaction(), it could improve Database inserting performance for Pull Replication.
