### ISSUE TITLE
Class cast exception in Replication.java

### ISSUE THREAD

**Issue by sluedecke** [couchbase/couchbase-lite-java-core#268]
Hi!

When a new instance of my app connects to the sync_gateway, it logs the class cast exception below.  After restarting the app,   This might not be a bug since it the circumstances are:
- created an attachment (which was too large for the server and it chocked on it when updating views)
- deleted the attachment object itself (_id = sha1-+BNbV0BRAZNtU/IM8oqWUthvfYc=)
  using the REST API (yes, I know it's bad...)
- did not delete the _attachment part in the related document

This is the offending object:

```
{
    "_attachments": {
        "Image 20140801-211302": {
            "content_type": "image/*", 
            "digest": "sha1-+BNbV0BRAZNtU/IM8oqWUthvfYc=", 
            "length": 2832882, 
            "revpos": 2, 
            "stub": true
        }
    }, 
    "_sync": {
        "channels": {
            "6ae70a7a0f7c5994138d93e6852bd7a1": null
        }, 
        "history": {
            "bodies": [
                "", 
                ""
            ], 
            "channels": [
                null, 
                [
                    "6ae70a7a0f7c5994138d93e6852bd7a1"
                ]
            ], 
            "parents": [
                -1, 
                0
            ], 
            "revs": [
                "1-0b2c9c863a16af28e62032dd94362258", 
                "2-4fbe9d22ac16477d0ccb67f639870397"
            ]
        }, 
        "rev": "2-4fbe9d22ac16477d0ccb67f639870397", 
        "sequence": 1473, 
        "time_saved": "2014-08-01T21:13:50.970308714+02:00"
    }, 
    "actionId": "40eb02f7-e470-46b9-9be8-3b8c5c604ec9", 
    "filename": "Image 20140801-211302", 
    "mimetype": "image/*", 
    "owner": "6ae70a7a0f7c5994138d93e6852bd7a1", 
    "size": 2832882.0, 
    "title": "Image 20140801-211302", 
    "type": "Attachment"
}
```

I am using the latest git versions:

  couchbase-lite-android: f4d96e40a24ffafa16c04df21b0f73aa81d335bf
  couchbase-lite-java-core: 4bf559f0151d58e0bfb77248f3d90f64bc096a91

Exception from logcat:

08-06 11:30:03.530    1446-1488/MYPACKAGE.debug E/CBLite﹕ Exception getting status from {error=not_found, id=e7b327ca-6d89-4cf7-98c5-60479688aa54, reason=missing, rev=2-4fbe9d22ac16477d0ccb67f639870397, status=404}
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
            at com.couchbase.lite.replicator.Replication.statusFromBulkDocsResponseItem(Replication.java:1613)
            at com.couchbase.lite.replicator.Puller$5.onDocument(Puller.java:594)
            at com.couchbase.lite.replicator.BulkDownloader.finishedPart(BulkDownloader.java:235)
            at com.couchbase.lite.support.MultipartReader.appendData(MultipartReader.java:171)
            at com.couchbase.lite.replicator.BulkDownloader.executeRequest(BulkDownloader.java:148)
            at com.couchbase.lite.replicator.BulkDownloader.run(BulkDownloader.java:85)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)

**Comment by sergio91pt** [comment]
Seems it was fixed in https://github.com/couchbase/couchbase-lite-java-core/commit/9c8b295b57d4dca0d8ffe277e65db5799ddb0390

**Comment by djpongh** [comment]
closing based on last update.
