### ISSUE TITLE
Null pointer exception because of failing to rebuild view

### ISSUE THREAD

**Issue by hufeng03** [couchbase/couchbase-lite-java-core#285]
CBL version is 1.0.2

I have created several views and all have map.  Everything runs OK for quite long time. And suddenly when updating a doc, all view query staff not working.  Log is as following.

W/View    (21124): Failed to rebuild view CustomersView.  Result code: 500
W/System.err(21124): java.lang.NullPointerException
W/System.err(21124): at com.couchbase.lite.View.updateIndex(View.java:547)
W/System.err(21124): at com.couchbase.lite.Database.queryViewNamed(Database.java:2049)
W/System.err(21124): at com.couchbase.lite.Query.run(Query.java:342)

**Comment by hideki** [comment]
Hi @hufeng03 - could you please  provide steps to reproduce?

**Comment by hideki** [comment]
Hi @hufeng03 As we are not able to reproduce this issue, I will close this ticket. If you will encounter this issue again, please reopen the ticket.
