### ISSUE TITLE
1.x: [Memory] Memory leak in allReplicators

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java-core#290]
Replications get added to allReplicators but the only way to remove them is via forgetReplication and that is both private and never called by anyone.

Why do we have both allReplicators and activeReplicators anyway? Per #288 this just seems like a good excuse to have threading issues.

**Comment by hideki** [comment]
ref: #1212

**Comment by hideki** [comment]
Note to self:
It seems `activeReplicators` actually maintains replicators that `allReplicators` is intended to do. Removing allReplicators variable, and rename activeReplicators to allReplicator could be sufficient.
