### ISSUE TITLE
do_POST_Replication has a race condition that causes replication requests to fail inappropriately

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java-core#291]
# Failure scenario:
1. Issue a replication request via the listener
2. Wait a tiny bit of time
3. Issue a second replication request via the listener that is identical to the request in 1

The second request fails when it should have succeeded.

# Why:
do_POST_replicate will call manage.getReplicator on the first request and get a new replicator object (assuming the system is starting fresh). So the first request runs just fine.

The second request will call do_POST_replicate which will call manager.getReplicator and will get the existing replication request. In my tests the replicator will still be in a running state. The do_POST_replicate code will then call replicator.start() which will see that the replicationInternal is not in null, INITIAL or STOPPED and so will throw a "replicationInternal in unexpected state" exception.

# Proposed Solution:
I'm not completely sure about a solution mostly because there are assumptions made in Replication.start() that I don't understand. 

For example, replication.start() checks if replicationInternal is null. But that isn't possible. initReplicationInternal will set replicationInternal to a non-null value or throw and initReplicationInternal is called in the constructor and in general is the only method allowed to alter replicationInternal's state. So how could it ever be null?

Start() seems to assume that the only two legal states the machine can be in when start is called are INITIAL and STOPPED. But as shown above it's perfectly reasonable for the state machine to be in other states. This is especially the case because the instance that manager.getReplicator() returns in do_POST_replication is available to any thread with access to the manager or the database objects can get a hold of the replicator object and start messing around with it Including calling start().

Furthermore Start() does something really, really weird. It will create a new ReplicationInternal object via initReplicationInternal even after the replication has had stop called on it! Now I can theoretically understand the reason for this, which is to support restart() but then why is it allowed via start()? In other words I would argue that only restart() should be able to call initReplicationInternal, not start()!

Furthermore the ability to call initReplicationInternal of course creates all sorts of race conditions since it's perfectly possible for two calls to initReplicationInternal to be made as a result of the kind of race condition above in which case we can end up with two replicators running with the same settings. This is possible because stateless4j is not thread safe and so state checks are not thread safe.

My suggestion is:
1. Remove restart from Replication, it just confuses things and making restart work will require using some kind of atomic container for replicationInternal to keep it's state from changing under another caller. Mutability and thread safety are not friends. So let's just lose restart. There is only one test (testMockPullerRestart) that even uses it.
2. Turn replicator.start() into a call to replicationInternal.triggerStart() 
3. Add the right ignore rules to the state machine so you can call 'start' in any state and have it ignored (except for initial of course)
4. Change do_POST_replication in Router.java to check if session ID is null before calling await. This gets rid of race conditions where we have a replicator that is already running.

**Comment by tleyden** [comment]
@andreibaranouski can you take a look and see if it's feasible to add a test to [cblite-tests](https://github.com/couchbaselabs/cblite-tests) which reproduces this issue?

**Comment by hideki** [comment]
In `do_POST_replicate()` method in Router.java, check if existing replicator is running state. If not running state, calls `replicator.start();`. Theoretically, this problem is not reproducible with latest codes. 

https://github.com/couchbase/couchbase-lite-java-core/blob/720c8d59fd9136199ffeb3e9823374d896d1554c/src/main/java/com/couchbase/lite/router/Router.java#L642-L654

I will add unit test for this ticket.
