### ISSUE TITLE
total_rows attribute on view query result

### ISSUE THREAD

**Issue by laurent-g** [couchbase/couchbase-lite-java-core#293]
I found something different when I query a view with couchdb and couchbase lite.
It's annoying because total_count is useful for pagination usage (it' important to know in advance the total of documents that we can retrieve)

# Test case 
http://localhost:5984/crm1/_design/companies/_view/by_name?limit=2

# Expected result (couchdb response)

total_rows is the number of documents in the view, whatever the limit and skip options

```javascript
{"total_rows":33,"offset":0,"rows":[
{"id":"12295ce12a5fd2a3e2867efdac00bdce","key":"APPLE","value":{"title":"APPLE","subtitle":"Apple","description":"95014 Cupertino","aside":"électronique","logo":"12295ce12a5fd2a3e2867efdac00bdce/logo-chrom-2.png"}},

{"id":"12295ce12a5fd2a3e2867efdac0091ac","key":"TEST","value":{"title":"TEST","subtitle":"","description":"48105 Ann Arbor","aside":"restaurant","logo":"12295ce12a5fd2a3e2867efdac0091ac/logo-chrom-2.png"}}
]}
```
See http://docs.couchdb.org/en/latest/api/ddoc/views.html

# Actual result (couchbase lite result)

total_rows is the number of documents in the result
```javascript
{"total_rows":2,"offset":0,"rows":[
{"id":"12295ce12a5fd2a3e2867efdac00bdce","key":"APPLE","value":{"title":"APPLE","subtitle":"Apple","description":"95014 Cupertino","aside":"électronique","logo":"12295ce12a5fd2a3e2867efdac00bdce/logo-chrom-2.png"}},

{"id":"12295ce12a5fd2a3e2867efdac0091ac","key":"TEST","value":{"title":"TEST","subtitle":"","description":"48105 Ann Arbor","aside":"restaurant","logo":"12295ce12a5fd2a3e2867efdac0091ac/logo-chrom-2.png"}}
]}
```

# What needs fixing
total_rows has to be the number of document in view / database.

**Comment by hideki** [comment]
Notes for myself:

* Java Core implementation
- View.java does not have variable of totalRows.
- So, in queryDesignDoc() method of Router.java, rows.size() is set instead of totalRows.

* iOS implementation
- in CBLView (CBLView+Internal.h), "@property (readonly) NSUInteger totalRows;" is defined.
- "- (NSUInteger) totalRows" of CBLView.m queries sqlite database.

**Comment by tleyden** [comment]
@andreibaranouski can you retest?
