### ISSUE TITLE
Doc insertion speed is much slower with SQLite 3.8.5 

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#297]
See https://github.com/couchbase/couchbase-lite-ios/issues/487

**Comment by hideki** [comment]
SQLite3 versions on Android

- Version 5.0.0 (lollipop) API 21 - 3.8.6 2014-08-15 11:46:33 9491ba7d738528f168657adb43a198238abde19e
- Version 4.4.4 (Kitkat) API 19 - 3.7.11 2012-03-20 11:35:50 00bb9c9ce4f465e6ac321ced2a9d0062dc364669

Note: version is checked by android emulator (Genymotion) by following command
```
adb shell
sqlite3 --version
```

**Comment by hideki** [comment]
The patch to improve the document insertion speed (https://github.com/couchbase/couchbase-lite-ios/commit/f20387ebfb98fefeb60041056c15dad50a0f57f4) was already applied by @tleyden (https://github.com/couchbase/couchbase-lite-java-core/commit/219a74bd71a77adccc022724353a97b21d3c5b6f#diff-ddbec9e62a53b23c377faa1d1051c0af) to fix other ticket (https://github.com/couchbase/couchbase-lite-android/issues/444).

**Comment by hideki** [comment]
Verification

Compared document insertion performance between version without fix (one commit earlier) (https://github.com/couchbase/couchbase-lite-java-core/commit/d4f96a4ce2655afea652ff0cb4ea0690b2a270f7) and current master (https://github.com/couchbase/couchbase-lite-java-core/commit/8de482e430b246eb286760bfbc3f6ef71a207769)

Test Environment: 4.4.4 (KitKat) and 5.0.0 (Lollipop) on Genymotion Emulator on OSX.  KitKat includes SQLite3 v3.7.11, Lollipop includes SQLite3 v3.8.6.

Test Case: testCreateDocsPerformance() method of Test1_CreateDocs.java  2000 document size and 2000 documents. Measured 3 times each test case.


https://github.com/couchbase/couchbase-lite-java-core/commit/d4f96a4ce2655afea652ff0cb4ea0690b2a270f7 (Before applying fix)
- KitKat - 3697ms, 3871ms, 3993ms
- Lollipop - 1867ms, 1779ms, 1790ms

https://github.com/couchbase/couchbase-lite-java-core/commit/8de482e430b246eb286760bfbc3f6ef71a207769  (After applying fix)
- KitKat - 3458ms, 3519ms, 3520ms
- Lollipop - 1340ms, 1493ms, 1461ms

Result: I observed around 30% performance improvement for Lollipop, and around 10% improvement for KitKat
