### ISSUE TITLE
[Memory] compacting large database memory leak

### ISSUE THREAD

**Issue by hinesmr** [couchbase/couchbase-lite-java-core#301]
I'm running couchbase mobile version 1.0.2 on Android 4.4.2. The size of my database is over 1GB and is a large variety mix of small documents, big documents, and attachments (mostly images and a couple 40MB attachments).
      
When I try to issue the compact() operation in CBL, I watch the memory usage of the application spiral out of control.....Once it reaches over 500MB, the app dies immediately. I can't find any obvious information in the android logcat to explain why it crashed, but I think it's safe to assume that either the Linux android OOM killer got a hold of it or Android decided to kill it. 

This behavior is extremely reproducible with my database.... just keep trying compact() and I can make the leak + crash happen easily.

My app is still running without compaction, so this is not critical, but compaction will be needed soon.....

Thanks.

**Comment by hideki** [comment]
Related https://github.com/couchbase/couchbase-lite-android/issues/687

**Comment by hideki** [comment]
Compact DB performance results

Test Device: Nexus 6 (Android 6.0.1)
Test Codes:  [Test16_CompactDB](https://github.com/couchbase/couchbase-lite-android/blob/feature/db_compact_perormance/src/androidTest/java/com/couchbase/lite/performance/Test16_CompactDB.java)

| storage | size doc | num docs | size attch | num attch | delete attch | num revs | execution time | note |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| sqlite | 1K | 10K | 0 | 0 | false | 0 | **72 sec** | this is base case no deletion happen during compaction |
| forestdb | 1K | 10K | 0 | 0 | false | 0 | 9 sec |  |
| sqlite | 1K | 10K | 100K | 1 | false | 0 | **97 sec** | test if attachment makes impact |
| forestdb | 1K | 10K | 100K | 1 | false | 0 | 25sec  | |
| sqlite | 1K | 10K | 100K | 1 | true | 0 | **131 sec** | test if attachment delete makes impact |
| forestdb | 1K | 10K | 100K | 1 | true | 0 | 34sec  | |
| sqlite | 1K | 10K | 0 | 0 | false | 5 | **239 sec** | check if num revs makes impact |
| forestdb | 1K | 10K | 0 | 0 | false | 5 | 44 sec |  |

Notes
- Read/Write/Delete attachment is common code between SQLite and ForestDB.

**Comment by hideki** [comment]
Compact DB performance results

Test Device: Nexus 6 (Android 6.0.1)
Test Codes:  [Test16_CompactDB](https://github.com/couchbase/couchbase-lite-android/blob/feature/db_compact_perormance/src/androidTest/java/com/couchbase/lite/performance/Test16_CompactDB.java)

Following results are with applying https://github.com/couchbase/couchbase-lite-java-core/commit/0dac2a1df3377b870aa3ff080a8b0209f09367dd

| storage | size doc | num docs | size attch | num attch | delete attch | num revs | execution time | note |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| sqlite | 1K | 10K | 0 | 0 | false | 0 | **19 sec** | this is base case no deletion happen during compaction |
| sqlite | 1K | 10K | 100K | 1 | false | 0 | **35 sec** | test if attachment makes impact |
| sqlite | 1K | 10K | 100K | 1 | true | 0 | **64 sec** | test if attachment delete makes impact |
| sqlite | 1K | 10K | 0 | 0 | false | 5 | **127 sec** | check if num revs makes impact |

**Comment by hideki** [comment]
Compact DB performance results

Test Device: Nexus 6 (Android 6.0.1)
Test Codes:  [Test16_CompactDB](https://github.com/couchbase/couchbase-lite-android/blob/feature/db_compact_perormance/src/androidTest/java/com/couchbase/lite/performance/Test16_CompactDB.java)

Following results are with applying WAL (Write-ahead Log).

| storage | size doc | num docs | size attch | num attch | delete attch | num revs | execution time | note |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| sqlite | 1K | 10K | 0 | 0 | false | 0 | **20 sec** | this is base case no deletion happen during compaction |
| sqlite | 1K | 10K | 100K | 1 | false | 0 | **40 sec** | test if attachment makes impact |
| sqlite | 1K | 10K | 100K | 1 | true | 0 | **66 sec** | test if attachment delete makes impact |
| sqlite | 1K | 10K | 0 | 0 | false | 5 | **131 sec** | check if num revs makes impact |
