### ISSUE TITLE
API: Implement Query.postFilter

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-java-core#303]
Implement the [post-filtering query enhancement](https://github.com/couchbase/couchbase-lite-ios/wiki/Query-Enhancements) that was added on iOS in 1.0.3.

**Comment by tleyden** [comment]
@snej was there any WIP on this?  I don't see any other PR's aside from https://github.com/couchbase/couchbase-lite-java-core/pull/345

**Comment by snej** [comment]
Looks like everything I'd done was pushed into #345. The remaining work would be:
* Decide what public interface to use for predicates.
* Add unit tests.

**Comment by hideki** [comment]
Use JsonPath: https://github.com/jayway/JsonPath for QueryAPI and postFilter.
