### ISSUE TITLE
Identify performance bottlenecks

### ISSUE THREAD

**Issue by jessliu** [couchbase/couchbase-lite-java-core#305]
Specific issues:

> 1. We have about 20-30 views in the application, and indexing the views can be costly, 2-6 seconds per view.  Is there a strategy to index the views together as the data is written, rather than when the view is called?

> 2. Slow update and delete speeds. We're seeing slow speeds (20+ seconds) to delete 200 or so documents.  This is running as a transaction as well.  Is there a strategy to speed up the deletions or updates to the document?

**Comment by hideki** [comment]
Notes to myself:
In this ticket, we will identify bottlenecks. Based on this result, we will tackle specific issues from next sprint.

**Comment by hideki** [comment]
Index update performance measurement result  => https://github.com/couchbase/couchbase-lite-java-core/issues/491#issuecomment-79863629

**Comment by hideki** [comment]
#### View.updateIndex() performance
- With fix of #502,  Test12_IndexView performance test with 10K docs improves from 9sec to 5sec. (Detailed test results => #491)
- Fix for #502 is only effective for JSON string that contains ASCII characters. For international languages, we need native Unicode collator. This will be tracked by #504
- View.updateIndex() is to update single view. But iOS supports multi-view index update. This ticket will be tracked by #501

**Comment by hideki** [comment]
In general, current version of CBL Android/Java is faster than when this issue was reported. I will close this.
