### ISSUE TITLE
post on doc without data returns 404 instead of 405

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#310]
See https://github.com/couchbase/couchbase-lite-ios/issues/499

@andreibaranouski can you add a test in cblite-tests that asserts that a 400 is returned in this case?  (I'm not sure what is currently returned in the case of android-liteserv)

Then re-assign to me to fix the underlying bug.

**Comment by hideki** [comment]
duplicated with https://github.com/couchbase/couchbase-lite-java-core/issues/1193

This is fixed with PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1202
