### ISSUE TITLE
ChangeTracker can run ahead of db insertion and fill up memory

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-java-core#315]
See https://github.com/couchbase/couchbase-lite-ios/issues/502 — the same issue applies on Android (and with the regular ChangeTracker, not just WebSockets.) On the first sync of a remote db with a large number of documents, over a fast network connection the change tracker can read revision metadata much faster than the puller can download and insert those revisions, so it can gobble up a lot of memory. The dev reported that in some cases it caused the app to run out of memory and be killed by the OS.

My fix was to have the puller pause the ChangeTracker while the number of pending revisions exceeds a threshold.

**Comment by hideki** [comment]
This fix was ported almost two years ago.

https://github.com/couchbase/couchbase-lite-java-core/commit/ed4505996f777991e168e88835060e4be49dcaed
