### ISSUE TITLE
We should support installing to mavenLocal()

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java-core#33]
Right now mavenDeployer in build.gradle only supports publishing to a remote maven repository specified by UPLOAD_MAVEN_REPO_URL which is a system environment property.

This is problematic for two reasons. First, it's a real pain to set system properties in a consistent way and so it would be nicer if this value was set using a gradle property.

Second, if one wants to publish to a local maven installation (very useful for quick debugging and development) then the accepted way to do this is to set the repository url to 'file://' + new File(System.getProperty('user.home'), '.m2/repository').absolutePath. But this involves calling gradle functions which can't really be done via a system property.

I would propose that we create a gradle property called something like 'localBuild' and if set to "true" then we would build to the file URL otherwise we would build to the existing maven location.

**Comment by djpongh** [comment]
Closing as dup of: https://github.com/couchbase/couchbase-lite-android/issues/239
