### ISSUE TITLE
Control EXECUTOR_THREAD_POOL_SIZE

### ISSUE THREAD

**Issue by ozomer** [couchbase/couchbase-lite-java-core#343]
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java#L72

The number of threads should be a parameter when a replicaiton object is created.

One reason is that I noticed that each thread makes a PUT request (_local/...) when it's done, to save the lastSequence.
This may be a costly overhead, in case you don't care about the replication speed and the documents are fetched in bulks (using _all_docs or _bulk_get).

**Comment by hideki** [comment]
Currently PR is under review. After PR is merged into master, EXECUTOR_THREAD_POOL_SIZE will be configurable with using ManagerOptions.

```
ManagerOptions options = new ManagerOptions();
options. setExecutorThreadPooSize(10); // set 10 for pool size
Manager manager = new Manager(..., options);
```
