### ISSUE TITLE
Replication restart problem

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#356]
Hello, i set filter to replication. But if i use method restart, filter is lost(((

Example:

```
this.replication.setFilter("app/clientIdAndTablesSchemeDocIdFilter"); 
Map<String, Object> filterParams = new HashMap<String, Object>(); 
filterParams.put("tablesSchemeDocId", this.TablesSchemeDocId);	
this.replication.setFilterParams(filterParams);
```
and

```
this.replication.restart();
```

Library version 1.0.4.1 (Couchbase lite Android)

**Comment by tleyden** [comment]
@hideki I just added two PR's and assigned you to review.

**Comment by jayakrishnan-pm** [comment]
> Thanks for reporting this.
> 
> As a workaround, you can create your own methods:
> 
> ```
> public void startReplicator() {
>   // create replicator 
>   // add filters
>   replicator.start()
> }
> 
> public void restartReplicator() {
>    replicator.stop()
>    startReplicator()
> }
> ```
> so that filters are added every time a replication is started

My doubt:: Replication stops asynchronously right? don't we have to wait for the change listener for that?
