### ISSUE TITLE
REST API need a way to setCookie

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-java-core#360]
It looks like you can't call set cookie from PhoneGap land: https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Manager.java#L582

We need to expose this API. Are there any work-arounds for this now? It seems adding a parse line for the auth data structure would be simple enough but it would need to be coordinated with iOS.

**Comment by hideki** [comment]
Notes to myself:
According to the ticket, https://github.com/couchbase/couchbase-lite-ios/issues/552 , both iOS and Android can be set cookie. But they are different manner.

**Comment by hideki** [comment]
According to the ticket, https://github.com/couchbase/couchbase-lite-ios/issues/552#issuecomment-66951560, the replicator allows to set custom header with cookie manually like below. Relying on phonegap/cordova platform to handling cookie automatically might cause issue in case of different domain/host authentication. @jchris and I consider manual solution could be common solution for all platforms, and this should be documented in somewhere.

```javascript
var remote = {
       url: REMOTE_SYNC_URL
     },
     push = {
       source: appDbName,
       headers: {
         Cookie: cookieName+ cookieValue
       },
       target: remote,
       continuous: true
     },
     pull = {
       target: appDbName,
       headers: {
         Cookie: cookieName+ cookieValue
       },
       source: remote,
       continuous: true
     },
```

**Comment by jchris** [comment]
Should probably be documented here: http://developer.couchbase.com/mobile/develop/references/couchbase-lite/rest-api/server/post-replicate/index.html

**Comment by hideki** [comment]
After further research, both iOS and Android supports explicit custom header for replicator. However, as implementation is different, solution in previous comment does not work with iOS. It seems iOS follows CouchDB REST API ( http://wiki.apache.org/couchdb/Replication#Username_Workaround_.28older_CouchDBs_only.29 ).

sample json request from link:
```
{
   "source":{
      "url":"https://example.net:5984/db","
      headers":{"Authorization":"Basic Ym9iQGV4YW1wbGUuY29tOnBhc3N3b3Jk"}
   },
   "target":"local-db"
}
```

Next step is fix CBL core java implementation

**Comment by hideki** [comment]
As @jchris mentioned previous comment, should update the documentation.
Current documentation does not describe how to set custom header/cookie.

**Comment by hideki** [comment]
Updated the document for POST _replicate - https://github.com/couchbaselabs/couchbase-mobile-portal/pull/164

**Comment by tleyden** [comment]
I had to revert the commit because it was causing [testGetReplicator](https://github.com/couchbase/couchbase-lite-android/blob/8e28c42dc922885f877061ab8929bebcaabc80ad/src/androidTest/java/com/couchbase/lite/replicator/ReplicationTest.java#L2932) to fail.

**Comment by tleyden** [comment]
It was failing on [this assertion](https://github.com/couchbase/couchbase-lite-android/blob/8e28c42dc922885f877061ab8929bebcaabc80ad/src/androidTest/java/com/couchbase/lite/replicator/ReplicationTest.java#L2962)

**Comment by hideki** [comment]
I will review both java core codes and test case.
