### ISSUE TITLE
Jenkins: Wrong artifact name when using a blank BLD_NUM

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#372]
To reproduce:

* Kick off a job on the AWS jenkins with:
    * VERSION: 1.0.4
    * BLD_NUM: <blank>

**Actual**: It will produce maven artifacts in a [1.0.4-](http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.0.4-/) directory, with an aar named couchbase-lite-android-1.0.4-.aar

**Exepcted**: produce maven artifacts in a 1.0.4 directory, with an aar named couchbase-lite-android-1.0.4.aar

**Comment by tleyden** [comment]
Just curious -- is it possible to use "rc1" for the BLD_NUM or that will cause problems since its non-numeric?

**Comment by andreibaranouski** [comment]
should work now without BLD_NUM

with the current implementation we are not able to use "rc1" for the BLD_NUM, it supports only numeric values

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/support/Version.java#L28

**Comment by tleyden** [comment]
Looks good.
