### ISSUE TITLE
Pull replication slow

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#376]
From this [Google Groups Post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mobile-couchbase/RYsjR7w2guc/nTLbNpu6E4EJ):

Hi All,

I have been working the android couch base lite in android.

The pull replication is very slow than comparing with ios and ipad!!

I am working with around 20,000 documents in database each document would be 10 to 20mb based on attachments.

While doing replication from server the pull replication is very slow and also  because  of the replication in background my UI components(when click on) actions are not happening immediately taking time 25sec time in between.

Questions :

1) I think While doing pull replication from server the entire CPU scheduling taking for replication in background, how i can stop that ?
2) And also am using android AsyncTask for background replication, is there any way to achieve the replication in background with out effect to UI ? 

please let me know if you need any furtherer information.

**Comment by hideki** [comment]
Notes to myself:

- By adding gzip support #172, the performance of pull replication will improve.

Tasks:
1. measure pull replication performance
2. Fix #172
3. measure pull replication performance
4. If it is still slow, figure out other bottle necks, and fix them.
5. measure pull replication performance

**Comment by tleyden** [comment]
@hideki I think we should also compare the REST api requests between ios and android on a pull replication to make sure android is not doing a lot of unnecessary work.

**Comment by hideki** [comment]
User Test06_PullReplication for android and Test24_PullReplication for iOS

Note: Sync Gateway and Emulator are on same machine (OSX) to avoid network trafic

- ios 1.0.3 on emulator
```
     docs;    1 B,   1000 B, 
   1 docs;  13.15;   14.73;
1000 docs; 253.34; 1360.41;
```
- android master on genymotion emulator (SDK 5.0.0)
```
     docs;     1 B,   1000 B, 
   1 docs;  536.00;  1567.00;
1000 docs; 5553.00; 27381.00;
```
- android master on genymotion emulator (SDK 5.0.0) with gzip
```
      docs;     1 B,   1000 B, 
   1 docs;  536.00;  1553.00;
1000 docs; 5618.00; 27109.00;
```
Result: Gzip support does not contribute for pull replication performance if we could avoid network

**Comment by hideki** [comment]
Sync-gateway HTTP request log difference between iOS and Android Push & Pull replication

1K docs push & pull (each doc size is 1KB)

iOS
````
// PUSH
18:07:55.610743 HTTP:  #001: GET /db/_local/b3fa1bed9601cc7d5a7584b608b63f82fdbd20ec
18:07:55.619443 HTTP:  #002: POST /db/_revs_diff
18:07:55.620480 HTTP:  #003: POST /db/_revs_diff
18:07:55.620859 HTTP:  #004: POST /db/_revs_diff
18:07:55.621337 HTTP:  #005: POST /db/_revs_diff
18:07:55.621921 HTTP:  #006: POST /db/_revs_diff
18:07:55.624558 HTTP:  #007: POST /db/_revs_diff
18:07:55.625274 HTTP:  #008: POST /db/_revs_diff
18:07:55.626217 HTTP:  #009: POST /db/_revs_diff
18:07:55.626357 HTTP:  #010: POST /db/_revs_diff
18:07:55.639322 HTTP:  #011: POST /db/_revs_diff
18:07:55.751512 HTTP:  #012: POST /db/_bulk_docs
18:07:55.765584 HTTP:  #013: POST /db/_bulk_docs
18:07:55.765741 HTTP:  #014: POST /db/_bulk_docs
18:07:55.765964 HTTP:  #015: POST /db/_bulk_docs
18:07:55.844617 HTTP:  #016: POST /db/_bulk_docs
18:07:55.860798 HTTP:  #017: POST /db/_bulk_docs
18:07:55.862690 HTTP:  #018: POST /db/_bulk_docs
18:07:55.871750 HTTP:  #019: POST /db/_bulk_docs
18:07:55.876168 HTTP:  #020: POST /db/_bulk_docs
18:07:55.886719 HTTP:  #021: POST /db/_bulk_docs
18:07:55.915525 HTTP:  #022: PUT /db/_local/b3fa1bed9601cc7d5a7584b608b63f82fdbd20ec

// PULL
18:07:55.917672 HTTP:  #023: GET /db/_local/3545291eb688e390a5ebc5f7a364324c4680dccc
18:07:55.927092 HTTP:  #024: POST /db/_changes
18:07:55.965025 HTTP:  #025: PUT /db/_local/3545291eb688e390a5ebc5f7a364324c4680dccc
````

Android
```
PUSH
18:06:30.142231 HTTP:  #001: GET /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:30.168179 HTTP:  #002: POST /db/_revs_diff
18:06:30.307325 HTTP:  #003: POST /db/_bulk_docs
18:06:30.437866 HTTP:  #004: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:30.453949 HTTP:  #005: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:30.656741 HTTP:  #006: POST /db/_revs_diff
18:06:30.782637 HTTP:  #007: POST /db/_bulk_docs
18:06:30.852164 HTTP:  #008: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:30.858211 HTTP:  #009: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:31.159057 HTTP:  #010: POST /db/_revs_diff
18:06:31.275747 HTTP:  #011: POST /db/_bulk_docs
18:06:31.347608 HTTP:  #012: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:31.355174 HTTP:  #013: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:31.659564 HTTP:  #014: POST /db/_revs_diff
18:06:31.777016 HTTP:  #015: POST /db/_bulk_docs
18:06:31.852454 HTTP:  #016: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:31.859656 HTTP:  #017: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:32.161959 HTTP:  #018: POST /db/_revs_diff
18:06:32.281771 HTTP:  #019: POST /db/_bulk_docs
18:06:32.345567 HTTP:  #020: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:32.354006 HTTP:  #021: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:32.663892 HTTP:  #022: POST /db/_revs_diff
18:06:32.787571 HTTP:  #023: POST /db/_bulk_docs
18:06:32.860635 HTTP:  #024: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:32.869081 HTTP:  #025: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:33.170424 HTTP:  #026: POST /db/_revs_diff
18:06:33.279219 HTTP:  #027: POST /db/_bulk_docs
18:06:33.344574 HTTP:  #028: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:33.350758 HTTP:  #029: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:33.667297 HTTP:  #030: POST /db/_revs_diff
18:06:33.790039 HTTP:  #031: POST /db/_bulk_docs
18:06:33.865197 HTTP:  #032: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:33.874719 HTTP:  #033: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:34.168511 HTTP:  #034: POST /db/_revs_diff
18:06:34.278044 HTTP:  #035: POST /db/_bulk_docs
18:06:34.338535 HTTP:  #036: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:34.346131 HTTP:  #037: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:34.668891 HTTP:  #038: POST /db/_revs_diff
18:06:34.802269 HTTP:  #039: POST /db/_bulk_docs
18:06:34.888400 HTTP:  #040: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5
18:06:34.896584 HTTP:  #041: PUT /db/_local/a4cb8ee6b5623fcdcf6cdd10fae03e276af797b5

// PULL
18:06:34.909869 HTTP:  #042: GET /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
18:06:34.917709 HTTP:  #043: POST /db/_changes
18:06:35.202378 HTTP:  #044: PUT /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
18:06:35.706871 HTTP:  #045: PUT /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
18:06:36.212592 HTTP:  #046: PUT /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
18:06:36.719384 HTTP:  #047: PUT /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
18:06:37.225017 HTTP:  #048: PUT /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
18:06:37.728784 HTTP:  #049: PUT /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
18:06:38.235888 HTTP:  #050: PUT /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
18:06:38.743255 HTTP:  #051: PUT /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
18:06:39.244841 HTTP:  #052: PUT /db/_local/4bb04e09e6f2abaf9598c99aa14f511bbf6e6e43
```

Insights:
- Both push & pull, Android calls more check point API (/{db}/_local/xxxxxxxxx)
- For Push, iOS is like batch, Android is like chunk processing

**Comment by hideki** [comment]
# difference between iOS and Android
POST /db/_changes are not much different between iOS and Android. The difference is only User-Agent.
All other differences are mentioned in the comment, https://github.com/couchbase/couchbase-lite-java-core/issues/328#issuecomment-71124494

# about test tool
perormance2/Test06_PullReplication does not download any docs from sync_gateway because no doc changes on server side. Need to write test that download docs from SG.
1. create db1 with 200 docs
2. push 200 docs to SG remote db.
3. create db2 with no docs
4. pull docs from SG to db2 from SG remote db

# action item for unnecessary PUT /db/_local/xxxx
perormance2/Test06_PullReplication send unnecessary PUT /db/_local/xxxx request to SG. It seems Android calls PUT /db/_local/xxxx for every 100 docs. This is unnecessary, it needs to call only one PUT /db/_local/xxxx with last sequence number.

**Comment by hideki** [comment]
Difference between iOS and Android for pull replication

Android PULL replication 200 docs (1B/doc)
```
GET  http://10.17.2.82:4984/db/_local/b14f99e704109f8f2ea2a217c596ce577ab28b36
POST http://10.17.2.82:4984/db/_changes
POST http://10.17.2.82:4984/db/_bulk_get?revs=true&attachments=true
POST http://10.17.2.82:4984/db/_bulk_get?revs=true&attachments=true
PUT  http://10.17.2.82:4984/db/_local/b14f99e704109f8f2ea2a217c596ce577ab28b36
```

iOS PULL replication 200 docs (1B/doc)
```
http://10.17.2.82:4984/db/_local/f78bf2eb97b92cb1626b9ee34979d5e70da275cc
http://10.17.2.82:4984/db/_changes
http://10.17.2.82:4984/db/_bulk_get?revs=true&attachments=true
http://10.17.2.82:4984/db/_bulk_get?revs=true&attachments=true
http://10.17.2.82:4984/db/_bulk_get?revs=true&attachments=true
http://10.17.2.82:4984/db/_bulk_get?revs=true&attachments=true
http://10.17.2.82:4984/db/_bulk_get?revs=true&attachments=true
http://10.17.2.82:4984/db/_local/f78bf2eb97b92cb1626b9ee34979d5e70da275cc
```

Observation: the number of handled docs for /{db}/_bulk_get is different between iOS and Android

**Comment by hideki** [comment]
Additional Notes:

Pull replication for 2K docs (2KB/doc)

Android:
```
GET /db/_local/5d65c113a763fbf2113e9c13d3139cc2a0036d5c
POST /db/_changes
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
PUT /db/_local/5d65c113a763fbf2113e9c13d3139cc2a0036d5c
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
PUT /db/_local/5d65c113a763fbf2113e9c13d3139cc2a0036d5c
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
PUT /db/_local/5d65c113a763fbf2113e9c13d3139cc2a0036d5c
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
PUT /db/_local/5d65c113a763fbf2113e9c13d3139cc2a0036d5c
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
PUT /db/_local/5d65c113a763fbf2113e9c13d3139cc2a0036d5c
```
iOS
```
GET /db/_local/538394bdcca525c3b1a6b8f3b6cb555f2a1304cb
POST /db/_changes
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
POST /db/_bulk_get?revs=true&attachments=true
PUT /db/_local/538394bdcca525c3b1a6b8f3b6cb555f2a1304cb
```
Observations:
- Number of docs which are handled by /db/_bulk_get API for iOS is smaller than for Android.
- Number of docs which are handled by /db/_bulk_get API for Android is alwasy 100 docs.
- Android calls /db/_local/xxx every two /db/_bulk_get APIs
- Gzip is applied for Android pull replication.
- Content-Length value of request header for Android is too small.

Action Items:
- Fix unnecessary PUT /db/_local/XXXX calls. Android calls it every 200 docs for pull replication. This is also applicable in case no doc changes on sync gateway.
- Fix HTTP header values

**Comment by tleyden** [comment]
> Fix unnecessary PUT /db/_local/XXXX calls

I think this should be in its own ticket w/ unit test.

**Comment by hideki** [comment]
#394 and #395 might improve pull replication performance. But they can not explain all of slowness of pull replication. Slowness might be caused by database read/write, JSON serialization, or something else. With this ticket, we will keep investigating root cause of pull replication slowness.

**Comment by hideki** [comment]
I found that performance2/Test06_PullReplication create String Array instead of one String as data.
In case doc size is specified with 1000, the generated JSON data is => ["1", "1",..... , "1"].
However, iOS PullReplication test case generates "111111111.....1" which is 1K length String.

So I changed Test06_PullReplication test code to generate the specified sized String, and measured performance again. Following is result.

- ios 1.0.3 on emulator
```
1K docs (1KB/doc) => 1360.41ms
```
- Current android test case (specified sized array) with android master on genymotion emulator (SDK 5.0.0)
```
1K docs (1KB/doc) => 10873.00ms
```
- Updated Android test case (iOS test case compatible/specified sized document) with android master on genymotion emulator (SDK 5.0.0)
```
1K docs (1KB/doc) => 4812.00ms
```

From above results, Because test case generates specified array as data, it makes JSON parser to slow. And pull replication performance gap between CBL for iOS and CBL for Android is around 4 times.

**Comment by hideki** [comment]
I posted following reply for original message:  https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mobile-couchbase/RYsjR7w2guc/nTLbNpu6E4EJ

```
Some questions about your environment:

>> I am working with around 20,000 documents in database each document would be 10 to 20mb based on attachments.

It seems 200GB - 400GB of data on your server. I believe your app downloads part of all documents. How many document could be replicated to each Android device? And How long does it take to download all documents to Android device?

Answer for your questions:

Questions :

>> 1) I think While doing pull replication from server the entire CPU scheduling taking for replication in background, how i can stop that ?

You can stop replicator by calling stop() method. Replicator does not stop immediately, it stop after currently processing HTTP requests. 
http://developer.couchbase.com/mobile/develop/references/couchbase-lite/couchbase-lite/replication/replication/index.html#void-stop

>> 2) And also am using android AsyncTask for background replication, is there any way to achieve the replication in background with out effect to UI ?  

We are using ScheduledExecutorService for Replicator for asynchronous tasks including replicator. 
http://developer.android.com/reference/java/util/concurrent/ScheduledExecutorService.html

Currently Thread priority is default. If you can compile Couchbase Lite for Android by yourself, you can modify thread priority by modifying Manager.java
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Manager.java#L138
```

**Comment by hideki** [comment]
As I answered to customer's question also this ticket is not concrete (detailed), so I closed this ticket . We will create new ticket for pull replication performance.

**Comment by hideki** [comment]
For general  pull replication performance test, we will track by ticket #399
