### ISSUE TITLE
What is Object in Map<String, Object>?

### ISSUE THREAD

**Issue by BraisGabin** [couchbase/couchbase-lite-java-core#379]
The allowed values for `Object` in the method: `Document.putProperties(Map<String, Object>)` are not documentated. Which are?

- `Number` or *just* `Byte`, `Short`, `Integer`, `Long`, `Float` and `Double`?
- `Boolean`
- `String` or `CharSequence`?
- `Collection<T>` or `Iterable<T>` or `List<T>`? (Where `T` is one of this types) Is `T[]` allowed?
- `Map<String, Object>` (Where `Object` is one of this types)

The same happens for the returned types of `Map<String, Object> Document.getProperties()`.

**Comment by tleyden** [comment]
AFAIK it's any Object.  The only limitation is that Jackson needs to be able to marshal it to JSON, so if it's a non-standard object it doesn't know how to marshal it, it won't work.

If you run into problems, go ahead and open a specific ticket and we can drill into it.
