### ISSUE TITLE
Jenkins: attach test results artifact

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#380]
In this build failure https://gist.github.com/tleyden/431a63d6a0026bbe3cee it mentions this file: file:///var/lib/jenkins/jobs/couchbase-lite-java-build/workspace/couchbase-lite-java/build/reports/tests/index.html

but I have no way to see it.  Can it be attached as an artifact?

**Comment by andreibaranouski** [comment]
could be found in artifacts by url like http://JENKINS_URL/job/couchbase-lite-java-build/55/artifact/couchbase-lite-java/build/reports/tests/
