### ISSUE TITLE
Jenkins: add --info --debug when running gradlew test for couchbase-lite-java

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#381]
From skype conversation: 

> I used --debug, --info in gridlew command when run tests from couchbase-lite-java (in https://github.com/couchbase/couchbase-lite-java/issues/43)

**Comment by zgramana** [comment]
Need to work around Jenkins test runner failure to capture verbose log output.

**Comment by andreibaranouski** [comment]
couchbase-lite-java could be run with 3 log levels( as selector parameter in the job):
--quiet ( by default)
--info
--debug
