### ISSUE TITLE
Pull replication not going back into IDLE state 

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#383]
To reproduce:

* Run TodoLite-Android
* Do a pull sync
* Update a document locally

**Actual**: spinny will never stop spinning
**Expected**: it should stop spinning after a short duration

I suspect it may have been caused by https://github.com/couchbase/couchbase-lite-java-core/issues/299

**Comment by tleyden** [comment]
I found the problem:

* In order for a continuous puller to go back into the IDLE state, the [changeTrackerCaughtUp()](https://github.com/couchbase/couchbase-lite-java-core/blob/20fbf1b0952be7df67d8b23c77a1ae701f95d9d6/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L844) method must be called by the ChangeTracker

* Due to broken logic regarding the [caughtUp](https://github.com/couchbase/couchbase-lite-java-core/blob/6380839f274c5aff9f959167eafc1ec97862d2c0/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L344-L349) state flag, since it is never being reset to false, it only calls `changeTrackerCaughtUp()` **once**.  

I'm going to just remove the `caughtUp` flag completely, since it seems to adding no value whatsoever and just causing bugs.  If it needs to be re-added, it should be accompanied with a ChangeTracker unit test to make assertions about the problem its solving.

**Comment by tleyden** [comment]
@hideki please review PR's (the fix is explained in this comment: https://github.com/couchbase/couchbase-lite-java-core/issues/383#issuecomment-69978319)

**Comment by tleyden** [comment]
Re-opening this since testContinuousPullReplicationGoesIdleTwice is failing.

**Comment by tleyden** [comment]
I'm able to reproduce the test failure of testContinuousPullReplicationGoesIdleTwice on my Nexus 5 test device, but not on the genymotion emulator.  Looking into it.

**Comment by hideki** [comment]
@tleyden This is not 100% reproducible. It could depend on timing or something else.

**Comment by tleyden** [comment]
Yes it is definitely a race condition of some sort.

I found out how to reproduce the issue reliably on Genymotion: set number of processors to 4 (same as Nexus 5)

**Comment by tleyden** [comment]
Added a race condition workaround -  08b46d7 -- see commit comments for details.

**Comment by tleyden** [comment]
Possible workaround: https://gist.github.com/tleyden/4b0f84e3edc41c2d0f78

This would fix the problem, but the problem with this is that since `getOrInsertDocNumericID()` writes to the db and is now outside of the nested transaction, it could leave the db in an invalid state.  I didn't investigate whether that invalid state would cause any real problems though.

**Comment by hideki** [comment]
Note to self:

- In case /{db}/_change has response with changes
  - Tasks are created and added in Batcher. [start from here](https://github.com/couchbase/couchbase-lite-java-core/blob/19ac1a29b0fc365abf911637124eef560c4ab893/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L341)
  - Also ChangeTracker calls [changeTrackerCaughtUp()](
https://github.com/couchbase/couchbase-lite-java-core/blob/edf2c135f274258386632552759298a58a1ea5df/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L847) which waits all processes will be done and calls `fireTrigger(ReplicationTrigger.WAITING_FOR_CHANGES);` at end of method.

- `changeTrackerCaughtUp()` method creates Thread and do its process.
  - It seems `changeTrackerCaughtUp()` task finishes before tasks are created in batcher?? <- not make sense

TODO: 
1. When `changeTrackerCaughtUp()` is called, check number of tasks in batcher and pending features
2. if tasks are empty, it needs to wait till tasks are created.
3. if tasks are not empty, needs to figure out why `changeTrackerCaughtUp()`'s Runnable finished before all tasks are completed.

**Comment by hideki** [comment]
Additional Info. By fixing this issue, ToDo Lite spinner issue was also addressed as we expected.
