### ISSUE TITLE
Jenkins: couchbase-lite-java artifact have extra "-" in name when omitting BLD_NUM

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#387]
I kicked off this job: http://172.23.113.52:8080/job/couchbase-lite-java-build/22/ and it ended up with a maven artifact named "couchbase-lite-java-1.0.4-.jar".  (as opposed to couchbase-lite-java-1.0.4.jar)

**Comment by andreibaranouski** [comment]
fixed with changes in the job config:

export MAVEN_UPLOAD_VERSION=${VERSION}-${BLD_NUM}
if [ -z "$BLD_NUM" ]
then
   export MAVEN_UPLOAD_VERSION=${VERSION}
fi
