### ISSUE TITLE
Jenkins: setup functional tests (cblite-tests) on new Jenkins

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#388]

**Comment by zgramana** [comment]
@andreibaranouski can you provide a status update?

**Comment by andreibaranouski** [comment]
this has been done. http://172.23.113.52:8080/job/couchbase-cblite-tests/13/console 

There is only one point for improvement. launch is always green, no matter whether there is a failed tests. I'll improve it and convert cblite tap statistic like
# tests 813
# pass  739
# fail  74
into unit report to provide a clearer info for the run
