### ISSUE TITLE
Let's Query or QueryEnumerator implements Iterable<T>

### ISSUE THREAD

**Issue by BraisGabin** [couchbase/couchbase-lite-java-core#392]
It would be great if we could do this:
```java
for (QueryRow queryRow : query) {
  // Your cool stuff
}
```
or this:
It would be great if we could do this:
```java
for (QueryRow queryRow : queryEnumerator) {
  // Your cool stuff
}
```
I think that the first is better but I'm not sure. What do you think?
I implemented the necesary code for both options:

- Query implements Iterable: https://github.com/BraisGabin/couchbase-lite-java-core/commit/b99ac94da6f024fcc263a38ff438dbc3d7417cfd
- QueryEnumerator implements Iterable: https://github.com/BraisGabin/couchbase-lite-java-core/commit/d518cf17da7acc1945a83d3853da0a0277de02b5

**Comment by hideki** [comment]
@BraisGabin Thank you very much for your proposal! Supporting foreach is great idea.

About first option, I am not sure if it makes sense that query returns results without calling run(), execute() or query() method. For second option, as QueryEnumerator is an iterator, I wonder if it is best practice that QueryEnumerator implements both Iterable and Iterator.

After considering option 1 and 2, also other alternate options, I believe option 2 is acceptable solution.  What do you think?

**Comment by BraisGabin** [comment]
The first option has another problem too. You need to "cast" a `CouchbaseLiteException` to a `RuntimeException`.

"An iterator is iterable." It have sense for me.

I can send a PR, if you want.

**Comment by tleyden** [comment]
@BraisGabin thanks for the PR offer.  Can you please sign our [Contributor License Agreement](https://github.com/couchbase/mobile/wiki/Contributing)?

Sorry about the hassle, we just need to do this to protect against someone contributing code and then suing us for copyright infringement.

**Comment by hideki** [comment]
Hi @BraisGabin 

Could you please also write UnitTest for your changes in https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/ViewsTest.java ?

Thanks!

**Comment by hideki** [comment]
@BraisGabin 
Did you sign the agreement? Please let us know.

**Comment by BraisGabin** [comment]
Yes, I did

**Comment by hideki** [comment]
@BraisGabin  Sorry, I missed your comment in PR.
