### ISSUE TITLE
Fix unnecessary PUT /{db}/_local/XXXX calls for pull replication

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#394]
This ticket is separated from #376 (Pull replication slow)

By analyzing issue of ticket #376 (pull replication), we found CBL for Android calls unnecessary PUT /{db}/_local/xxx REST API to SG for every 200 documents. It is called after every 2 /{db}/_bulk_get REST API calls. It seems 200 is batcher size. Each /{db}/_bulk_get REST API receives 100 docs.

CBL for iOS only calls 1 PUT /{db}/_local/xxxx after all /{db}/_bull_get calls completed.

For more information, please refer #376

**Comment by hideki** [comment]
Fix for #328 , also fix this issue too because of PUT /{db}/_local/xxxx request is shared code of both Pull and Push replication.

I verified the fix with using performance2/Test06_PullReplication

**Comment by pasin** [comment]
Close as https://github.com/couchbase/couchbase-lite-java-core/pull/398 and https://github.com/couchbase/couchbase-lite-android/pull/500 have been merged.
