### ISSUE TITLE
NullPointerException in Document.getProperties()

### ISSUE THREAD

**Issue by Takhion** [couchbase/couchbase-lite-java-core#407]
As previously mentioned in #148 (but was never fixed), in the `Document` class we have:
```java
public Map<String,Object> getProperties() {
    return getCurrentRevision().getProperties();
}
```
But `getCurrentRevision()` can be `null`!

**Comment by hideki** [comment]
@Takhion Thank you for reporting the issue. To understand this issue better, could you please provide detail information with following guideline?
https://github.com/couchbase/couchbase-lite-java-core/blob/master/CONTRIBUTING.md

**Comment by tleyden** [comment]
@hideki in this case, I don't think we need steps to reproduce .. but we do need the version number.  @Takhion is this on the master branch or a previous release?

@hideki I think @Takhion is just suggesting a null check and returning null rather than throwing an NPE.

**Comment by hideki** [comment]
@tleyden thanks for your advise.

**Comment by Takhion** [comment]
@hideki just as @tleyden is saying: a simple null check will fix it!
And yes, it's on [master](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Document.java#L152) (sorry I thought it was implicit).

**Comment by Takhion** [comment]
Oh and if you need "steps to reproduce" simply create a document that wasn't in the database or that it's deleted: the "current revision" will be null.

**Comment by tleyden** [comment]
Awesome.  Yes we'll add a unit test for this.
