### ISSUE TITLE
Should database or replication change event be notified on the same thread used when creating the manager object?

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#412]
Per the subject, should database or replication change be notified from the same thread used when creating the manager object?

For example, in ToDoLite-Android, when getting the replication change event, to update the UI, we need to call Activity.runOnUiThread() method as below:

```Java
runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        Application.SyncProgress progress = (Application.SyncProgress) data;
                        if (progress.status == Replication.ReplicationStatus.REPLICATION_ACTIVE) {
                            setProgressBarIndeterminateVisibility(true);
                        } else {
                            setProgressBarIndeterminateVisibility(false);
                        }
                    }
                });
```

**Comment by Takhion** [comment]
Personally I think developers should have the choice to do so or not, in our example we do as much as we can in background threads and switch to the main thread at the very last moment to update the UI.

**Comment by hideki** [comment]
After consideration, current behavior could be good enough.
