### ISSUE TITLE
NullPointerException in query with setGroupLevel() without reduce function and no data

### ISSUE THREAD

**Issue by Takhion** [couchbase/couchbase-lite-java-core#413]
Following #355, there's still a `NullPointerException` that slipped through!

Inside `View.reducedQuery()` ([currently on master](https://github.com/couchbase/couchbase-lite-java-core/blob/c59086252fa30c4cb77eca62f60577b61c88f1cb/src/main/java/com/couchbase/lite/View.java#L920)):
```java
List<Object> keysToReduce = null;
// ...
if(getReduce() != null) {
    keysToReduce = new ArrayList<Object>(REDUCE_BATCH_SIZE);
    // ...
}
// ...
cursor.moveToNext();
while (!cursor.isAfterLast()) {
    // ...
}
if(keysToReduce.size() > 0) {
```
As you can clearly see from the code above on the last line `keysToReduce` can be `null` when there's no reduce function and the query contains no data, so instead of `keysToReduce.size() > 0` it should be `keysToReduce != null && keysToReduce.size() > 0`.

**Comment by hideki** [comment]
@Takhion Thank you very much for clear bug report. Do you have any sample code to cause NPE that we can use as unit test case?

**Comment by Takhion** [comment]
I can provide code tomorrow, but simply:
1. create a query that would yield no data (without a reduce function)
2. `query.setGroupLevel(1);`
3. `query.run();`

**Comment by hideki** [comment]
@Takhion Thanks for your comment. 

This ticket could be closed during today. So you don't need to write the code.
