### ISSUE TITLE
Test on device running Android API 2.3 on AppThwack device list

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#416]
@andreibaranouski can you update our default AppThwack device list to add one more device which is running API 14?

**Comment by hideki** [comment]
@andreibaranouski  Is it possible to run unit test against all major versions of Android SDK on Jenkins with emulator?

**Comment by tleyden** [comment]
Hold off on that for now, because we are waiting on a change to our AppThwack account limits.

**Comment by tleyden** [comment]
Update: lets use API 14 since we found a specific thing that failed on that version.
