### ISSUE TITLE
Add API to tell which documents haven't been pushed to the server

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#417]
This needs to be ported from upstream iOS implementation:

https://github.com/couchbase/couchbase-lite-ios/issues/442

**Comment by bpolanec** [comment]
I read the IOS topic on the matter. 

Any idea when this will be implemented? I see no milestone set

Scenario in which we need this is to know if there is any documents pending. 
Something like :

boolean somethingPending = pushReplication.hasPendingPushDocuments() 

and like mentioned in other thread to get list of pending documents.

**Comment by pasin** [comment]
It has already been implemented in https://github.com/couchbase/couchbase-lite-java-core/commit/8798881e3fb2e889e3e1944ef31ebd5329b0ea73, and it should be included in the next 1.2 release.

**Comment by bpolanec** [comment]
@pasin I checked in milestones and there is no set date of release. When is the 1.2 release scheduled? Thanks
