### ISSUE TITLE
One shot replicator sends STOPPING state immediately after started replication 

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#435]
- One shot Push Replication sends STOPPING state immediately after started replication.
- One shot Pull Replication sends STOPPING state immediately after ChangeTracker is completed.

Both cases, a replicator is still uploading/downloading documents to/from Sync Gateway or CoudDB.

Expected behavior: STOPPING state should be sent after all replications are completed.

**Comment by hideki** [comment]
TEST was done by simple test app

Following is part of log which app does pull replication with 30K docs from CouchDB. STATE change from RUNNING to STOPPING is displayed after all replication was completed.
```
12-03 16:07:03.937 22075-22486/self.hideki.issue707 I/Issue707: PULL replication event. Source: com.couchbase.lite.replicator.Replication@5281ab64 Total changes: 29997 Completed changes: 29800
12-03 16:07:03.937 22075-22486/self.hideki.issue707 I/Issue707: PULL replication event. Source: com.couchbase.lite.replicator.Replication@5281ab64 Total changes: 29998 Completed changes: 29800
12-03 16:07:03.937 22075-22486/self.hideki.issue707 I/Issue707: PULL replication event. Source: com.couchbase.lite.replicator.Replication@5281ab64 Total changes: 29999 Completed changes: 29800
12-03 16:07:03.937 22075-22486/self.hideki.issue707 I/Issue707: PULL replication event. Source: com.couchbase.lite.replicator.Replication@5281ab64 Total changes: 30000 Completed changes: 29800
12-03 16:07:04.277 22075-22486/self.hideki.issue707 I/Issue707: PULL replication event. Source: com.couchbase.lite.replicator.Replication@5281ab64 Total changes: 30000 Completed changes: 30000
12-03 16:07:04.329 22075-22514/self.hideki.issue707 I/Issue707: com.couchbase.lite.Database$ChangeEvent@52fbab08
12-03 16:07:05.553 22075-22486/self.hideki.issue707 I/Issue707: PULL replication event. Source: com.couchbase.lite.replicator.Replication@5281ab64 Transition: RUNNING -> STOPPING Total changes: 30000 Completed changes: 30000
12-03 16:07:05.569 22075-22486/self.hideki.issue707 I/Issue707: PULL replication event. Source: com.couchbase.lite.replicator.Replication@5281ab64 Transition: STOPPING -> STOPPED Total changes: 30000 Completed changes: 30000
```

**Comment by pasin** [comment]
Total changes: 29997 Completed changes: 29800
Total changes: 29998 Completed changes: 29800
Total changes: 29999 Completed changes: 29800
Total changes: 30000 Completed changes: 29800
Total changes: 30000 Completed changes: 30000

It's weird that the total changes # were increased by 1. Notification or Batcher issue?

**Comment by hideki** [comment]
@pasin
I used CouchDB for this test. I believe CouchDB does not support _bulk_get. I assume it is reason.
