### ISSUE TITLE
ANR java.lang.IllegalStateException

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#445]
During replication error has occurred. The system issues a window ANR.
Couchbase lite version 1.0.4 from maven repo

Log:
02-18 15:06:40.781: E/RemoteRequest(26908): com.couchbase.lite.support.RemoteMultipartDownloaderRequest@4295c600: executeRequest() Exception: 
02-18 15:06:40.781: E/RemoteRequest(26908): java.lang.IllegalStateException: received incomplete MIME multipart response
02-18 15:06:40.781: E/RemoteRequest(26908): 	at com.couchbase.lite.support.MultipartDocumentReader.finish(MultipartDocumentReader.java:74)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:107)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:46)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.lang.Thread.run(Thread.java:841)
02-18 15:06:40.781: E/RemoteRequest(26908): com.couchbase.lite.support.RemoteMultipartDownloaderRequest@42096d68: executeRequest() Exception: 
02-18 15:06:40.781: E/RemoteRequest(26908): java.lang.IllegalStateException: received incomplete MIME multipart response
02-18 15:06:40.781: E/RemoteRequest(26908): 	at com.couchbase.lite.support.MultipartDocumentReader.finish(MultipartDocumentReader.java:74)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:107)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:46)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-18 15:06:40.781: E/RemoteRequest(26908): 	at java.lang.Thread.run(Thread.java:841)
02-18 15:06:40.791: E/RemoteRequest(26908): com.couchbase.lite.support.RemoteMultipartDownloaderRequest@41f0d458: executeRequest() Exception: 
02-18 15:06:40.791: E/RemoteRequest(26908): java.lang.IllegalStateException: received incomplete MIME multipart response
02-18 15:06:40.791: E/RemoteRequest(26908): 	at com.couchbase.lite.support.MultipartDocumentReader.finish(MultipartDocumentReader.java:74)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:107)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:46)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.lang.Thread.run(Thread.java:841)
02-18 15:06:40.791: E/RemoteRequest(26908): com.couchbase.lite.support.RemoteMultipartDownloaderRequest@424d9298: executeRequest() Exception: 
02-18 15:06:40.791: E/RemoteRequest(26908): java.lang.IllegalStateException: received incomplete MIME multipart response
02-18 15:06:40.791: E/RemoteRequest(26908): 	at com.couchbase.lite.support.MultipartDocumentReader.finish(MultipartDocumentReader.java:74)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:107)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:46)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.lang.Thread.run(Thread.java:841)
02-18 15:06:40.791: E/RemoteRequest(26908): com.couchbase.lite.support.RemoteMultipartDownloaderRequest@41ea5f78: executeRequest() Exception: 
02-18 15:06:40.791: E/RemoteRequest(26908): java.lang.IllegalStateException: received incomplete MIME multipart response
02-18 15:06:40.791: E/RemoteRequest(26908): 	at com.couchbase.lite.support.MultipartDocumentReader.finish(MultipartDocumentReader.java:74)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:107)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:46)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-18 15:06:40.791: E/RemoteRequest(26908): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

**Comment by hideki** [comment]
Exception was thrown at https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.0.4/src/main/java/com/couchbase/lite/support/MultipartDocumentReader.java#L74

It seems that Sync_Gateway or CouchDB sends corrupted data or some reason replicated data was corrupted. 

If you have time, could you please investigate what kinds of document was replicated.

**Comment by QRPro** [comment]
If there is again this error, I will write the document.

**Comment by hideki** [comment]
For more than a year, no additional information was provided. I will close this ticket.
