### ISSUE TITLE
Replication and ANR

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#448]
The first time we ran the replication server on the LAN. All was well. Yesterday, the server moved to another city and connection to it not stable. Often lost connection.

ANR posts began appearing. (Application isn't responding. Do you want to close it?)

The app is simple, one pull continuous replication.

Version: couchbase lite 1.0.4

**Comment by hideki** [comment]
Hi @QRPro,

Is it possible to share sample data or app to reproduce this issue?

**Comment by QRPro** [comment]
The test application is later. Noticed that when there is the log gets ANR string:

03-06 14:49:23.737: E/RemoteRequest(21234): com.couchbase.lite.support.RemoteMultipartDownloaderRequest@22527bc0: io exception
03-06 14:49:23.737: E/RemoteRequest(21234): org.apache.http.conn.ConnectTimeoutException: Connect to /IP:80 timed out
03-06 14:49:23.737: E/RemoteRequest(21234): 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:62)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:46)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-06 14:49:23.737: E/RemoteRequest(21234): 	at java.lang.Thread.run(Thread.java:841)

**Comment by QRPro** [comment]
Test app (Eclipse project):
https://yadi.sk/d/V-ufTKemf8wQM

If there is no communication for a long time, we have to do at restart replication. For testing, I set the timer restart 60 seconds. Very often when you restart appears ANR.

**Comment by hideki** [comment]
Hi @QRPro
Thank you very much for sharing test app.

**Comment by hideki** [comment]
Related issue => #449

**Comment by hideki** [comment]
This ticket will be handled by #449. I will close this ticket.
