### ISSUE TITLE
Documents with bad/missing MIME attachments should emit a warning instead of an error

### ISSUE THREAD

**Issue by jcamp1** [couchbase/couchbase-lite-java-core#457]
Greetings,

If a document is missing or has a bad MIME attachment, the java client should emit a warning and continue syncing. Currently it gives an error. On iOS you get the following non-fatal warning:

16:08:40.660‖ WARNING: CBLMultipartDocumentReader[_id="c91aabd3-d7e6-465d-adc9-2606604c5ee2"]: Attachment 'thumbnail' does not appear in a MIME body

On android/java it appears to be a more serious error.

Thanks!
Justin

**Comment by hideki** [comment]
I believe this is duplicated with #791, which was already solved.
