### ISSUE TITLE
Problems with setStartKeyDocId

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#461]
Try to use methods setStartKeyDocId and setStartKeyDocId. But in the end from the database get all the documents and not by the filter.

query.setStartKeyDocId("terminal-1");
query.setEndKeyDocId("terminal-2");

QueryEnumerator rows = null;
try {
  rows = query.run();
} catch (CouchbaseLiteException e) {
  e.printStackTrace();
}     

Version: 1.0.4

**Comment by tleyden** [comment]
@QRPro thanks for the code sample.

There are unit tests for this: https://github.com/couchbase/couchbase-lite-android/blob/77c30879bb751253a6d8812e12478ff7ef84993b/src/androidTest/java/com/couchbase/lite/ViewsTest.java#L618-L666

Can you suggest a test case that can be added that would reproduce your issue?

**Comment by hideki** [comment]
Hi @QRPro,

Thank you for your bug report.

startKeyDocId and endKeyDocId are secondary filter in addition to startKey and endKey. Without setting startKey and/or endKey, startKeyDocId and/or endKeyDocId are ignored. This is spec.

Ticket for iOS (https://github.com/couchbase/couchbase-lite-ios/issues/273) and CouchDB doc for pagination (http://docs.couchdb.org/en/latest/couchapp/views/pagination.html) help you to understand the spec.

I will close the ticket. If I misunderstand the problem. Please let us know. I will reopen the ticket.

Thanks!
