### ISSUE TITLE
setPostFilter Predicate on Query is overiden when LiveQuery is created from this Query

### ISSUE THREAD

**Issue by biokys** [couchbase/couchbase-lite-java-core#462]
When I create Predicate on Query object and run the query, predicate works well. But when I create LiveQuery from this Query, Predicate is removed. I know, i would create Predicate directly on LiveQuery object, but I think it would be nice, if Predicate persist after LiveQuery is made from Query and no predicate is defined on this LiveQuery.

**Comment by tleyden** [comment]
@snej is this in line with the ios behavior?

**Comment by snej** [comment]
Yes, this is a bug. The LiveQuery should inherit all the attributes of the original query.

**Comment by sergio91pt** [comment]
Fixed with #593

**Comment by sergio91pt** [comment]
Fixed with #588

**Comment by hideki** [comment]
Hi @biokys,
Fix for #588 is in master branch. When you have time, could you please verify the fix?
Thanks!
