### ISSUE TITLE
Fail to load android storage in Phonegap app

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#469]
https://github.com/couchbaselabs/TodoLite-PhoneGap/issues/15

**Comment by hideki** [comment]
I tested ToDo Lite for PhoneGap with Nexus 6 (Real device), Standard Android Emulator with Nexus 5 API 21 ARM, and Genymotion API 21. But I could not reproduce this this issue with these three platforms.

I also closed original ticket.
https://github.com/couchbaselabs/TodoLite-PhoneGap/issues/15
