### ISSUE TITLE
Slower pull reaction time (continuous replication)

### ISSUE THREAD

**Issue by biokys** [couchbase/couchbase-lite-java-core#471]
Before I switched from 1.0.4 version to snapshot 0.0.0-498 and higher, pull reaction time was quit fast. I mean pull reaction time as a duration between push from one device and pull on another device. I know that delay is caused by pull replicator. I tested creating object in android device and the time when the object appears on server was quit fast (<1s). When I create object on server, it takes about 10 seconds than pull replication starts to pull this object.

**Comment by hideki** [comment]
#### Replication Round Trip performance test

##### sync_gateway
- version:release/1.0.4, self build
- configuration: almost default configuration except GUEST access.
- host: localhost

##### Android client
- app: simple test app which build with CBL Android release/1.0.4 and master
- logic: app has two database, one for push, the other one for pull.
- measure: Elapsed time between push database change event listener and pull database change event listener
- device: Genymotion emulator Android 4.4.4 (API 19) to avoid network

##### RESULT
branch | 1st | 2nd | 3rd | 4th | 5th
------------ | ------------- | ------------- | ------------- | ------------- | -------------
release/1.0.4 | 2055ms | 37ms | 39ms | 31ms |28ms|45ms
master | 12064ms | 10038ms | 10041ms | 10045ms |10044ms|10039ms

**Comment by biokys** [comment]
It seems very similar

03-22 18:38:16.485  25993-26053/com.droid4you.application.wallet_dev D/Sync﹕ changeTrackerStopped.  lifecycle: CONTINUOUS
03-22 18:38:16.485  25993-26053/com.droid4you.application.wallet_dev E/Sync﹕ Change tracker stopped during continuous replication
03-22 18:38:16.485  25993-26053/com.droid4you.application.wallet_dev W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
03-22 18:38:16.485  25993-26053/com.droid4you.application.wallet_dev D/Sync﹕ Scheduling change tracker restart in 10000 ms

**Comment by hideki** [comment]
@biokys Thank you very much. Your logs give us hints. 

Note to self:

Some reason, ChangeTracker stopped, and it restart after 10 sec.

https://github.com/couchbase/couchbase-lite-java-core/blob/ea142a5c9ef08401980f748ea88737863beb976f/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L763-L806
```
public static int CHANGE_TRACKER_RESTART_DELAY_MS = 10 * 1000;

...
...

String msg = String.format("Change tracker stopped during continuous replication");
Log.e(Log.TAG_SYNC, msg);
parentReplication.setLastError(new Exception(msg));
fireTrigger(ReplicationTrigger.WAITING_FOR_CHANGES);
Log.d(Log.TAG_SYNC, "Scheduling change tracker restart in %d ms", CHANGE_TRACKER_RESTART_DELAY_MS);
workExecutor.schedule(new Runnable() {
    @Override
    public void run() {
        // the replication may have been stopped by the time this scheduled fires
        // so we need to check the state here.
        if (stateMachine.isInState(ReplicationState.RUNNING)) {
            Log.d(Log.TAG_SYNC, "%s still running, restarting change tracker", this);
            startChangeTracker();
        } else {
            Log.d(Log.TAG_SYNC, "%s still no longer running, not restarting change tracker", this);
        }
    }
}, CHANGE_TRACKER_RESTART_DELAY_MS, TimeUnit.MILLISECONDS);
```

**Comment by hideki** [comment]
#### After Fix Replication Round Trip performance test

##### RESULT
branch | 1st | 2nd | 3rd | 4th | 5th
------------ | ------------- | ------------- | ------------- | ------------- | -------------
feature/issue_471_slower_replication | 2058ms | 40ms | 53ms | 1050ms |45ms|53ms
