### ISSUE TITLE
Potenial race condition in Document.update

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#472]
Two key lines were not ported from the iOS codebase into the Java `Document` class. These were fixed in couchbase/couchbase-lite-net#389 and couchbase/couchbase-lite-net#390 as part of couchbase/couchbase-lite-net#388.

**Comment by tleyden** [comment]
@hideki I think it's worth writing a unit test to prove it's a bug first.  In the .net case, the issue was related to stale reads.

**Comment by hideki** [comment]
I wrote UnitTest, DocumentTest.testUpdateConflict().
https://github.com/couchbase/couchbase-lite-android/blob/feature/issue_472_document_update_conflict/src/androidTest/java/com/couchbase/lite/DocumentTest.java#L355-L445

Behavior from this unit test

1. Main thread: Document.update() -> create new Revision, and yield to another thread.
2. Another thread: update by `Document.putProperties()` -> successfully update document 
3. Main thread: Document.update() ->  `newRevision.save()` -> conflict
4. Main thread: Document.update() retry. ->  `newRevision.save()` -> OK

It seems current code works as expected.
Official document - [Updating documents](http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/document/index.html#updating)

TODO: I will port two iOS codes to be compatible with other platforms.
