### ISSUE TITLE
Make Database.close() method public (API Change)

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#476]
According to this change:
https://github.com/couchbase/couchbase-lite-ios/commit/9c38f8b4610b04d6f7a65468fe406068e0d33b30

**Comment by hideki** [comment]
`Database.close()` method is already public method. Only need to change from @InterfaceAudience.Private to @InterfaceAudience.Public .
```
    @InterfaceAudience.Private
    public boolean close() {
        if(!open) {
            return false;
        }
```
