### ISSUE TITLE
Jenkins: trigger new builds upon seeing new github commits 

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#480]
When new commits are pushed to github, it should trigger a new build on http://mobile.jenkins.couchbase.com/ using github webhooks.  (we set this up before, however we lost it when we migrated from ec2 to mobile.jenkins.couchbase.com)

**Comment by hideki** [comment]
@andreibaranouski  Do you have time to work for this ticket?

**Comment by hideki** [comment]
@michaelkwok Did you already implement this?

**Comment by hideki** [comment]
According to @michaelkwok, this is already implemented. I will close this.
