### ISSUE TITLE
Cannot start a transaction within a transaction error in logs

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#481]
While reviewing [TodoLite PR 39](https://github.com/couchbaselabs/ToDoLite-Android/pull/39), I ran into the following error:

```
03-11 19:10:41.853 E/AndroidRuntime( 4874): android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:505)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:416)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at com.couchbase.lite.android.AndroidSQLiteStorageEngine.beginTransaction(AndroidSQLiteStorageEngine.java:78)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at com.couchbase.lite.Database.beginTransaction(Database.java:1253)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at com.couchbase.lite.View.updateIndex(View.java:446)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at com.couchbase.lite.Database.queryViewNamed(Database.java:2166)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at com.couchbase.lite.Query.run(Query.java:395)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at com.couchbase.todolite.MainActivity.getCurrentListId(MainActivity.java:47)
03-11 19:10:41.853 E/AndroidRuntime( 4874): 	at com.couchbase.todolite.MainActivity.onCreateOptionsMenu(MainActivity.java:231)
```

[Full error log](https://gist.github.com/tleyden/c49af7c72ce0a465ad3c)

## Steps to reproduce

* Using master branch of TodoLite, configured to sync with http://ec2-54-161-192-2.compute-1.amazonaws.com:4984/todolite/, login with facebook and 2 lists with 20 records each
* Delete todolite from genymotion
* Switch to branch https://github.com/jamiltz/ToDoLite-Android/tree/display_conflicting_revisions and apply [this commit](https://github.com/couchbaselabs/ToDoLite-Android/commit/62f87e89744d614d99779bdd23d1efcc29ea4ae1), or just use [feature/display_conflicting_revisions](https://github.com/couchbaselabs/ToDoLite-Android/tree/feature/display_conflicting_revisions)
* Run app and login via facebook
* It should give the same error in the logs as above.

**Comment by hideki** [comment]
@tleyden Can you check if ToDo Lite dev branch points to latest master of CBL Android and CBL Java Core?

**Comment by tleyden** [comment]
I thought I had went into the submodules and updated them to the latest master commits.  I'm not 100% sure though.

**Comment by tleyden** [comment]
I tried to reproduce using steps above, but was unable to.  So this seems to be a sporadic error.

**Comment by hideki** [comment]
We are using Android's SQLiteDatabase.beginTransaction() which has own lock mechanism. I am not sure how SQLite's `begin transaction` was executed during middle of `transaction`.

**Comment by tleyden** [comment]
I did include the [Full error log](https://gist.github.com/tleyden/c49af7c72ce0a465ad3c) in case that offers any hints.

**Comment by hideki** [comment]
Duplicated with #484
