### ISSUE TITLE
Ramp up on JSONPath

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#490]

**Comment by tleyden** [comment]
Related to 304.

Task is to read through docs and play with examples.  Evaluate if appropriate to use.

**Comment by hideki** [comment]
I wrote sample app with JSONPath (https://github.com/hideki/couchbase-lite/tree/master/test/JSONPathTest). It seems JSONPath fits well for CBL Android to archive Query sorting, and also post filter enhancement.
