### ISSUE TITLE
Compare view indexing with ios

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#491]

**Comment by tleyden** [comment]
Related to #478

**Comment by hideki** [comment]
Also related to #305

**Comment by hideki** [comment]
### Indexing speed comparison between iOS and Android

#### Test tool
- Android: performance/Test12_IndexView.java -> https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/performance/Test12_IndexView.java
- iOS: Test21_Index.h and Test21_index.m -> https://github.com/couchbaselabs/iOS-WorkerBee/blob/master/Tests/Test21_Index.m

##### Test configuration
- 10000 documents

##### What measure
- Measure elapsed time of `View.updateIndex()` method

#### Test result 
1. iOS6 Emulator & release/1.0.3 => **279ms**
1. Nexus 6 Android 5.0.0 (real device) & release/1.0.4 =>  **8950ms**
1. Nexus 6 Android 5.0.0 (real device) & master =>  **8826ms**
1. Genymotion Android 4.4.4 (API19) & release/1.0.4 =>  **4117ms**
1. Genymotion Android 4.4.4 (API19) & master =>  **3974ms**
