### ISSUE TITLE
All unit tests passing on Jenkins

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#492]

**Comment by hideki** [comment]
03/16/2015 couchbase-lite-android build 81 passed successfully.
LOG: http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/81/console

**Comment by tleyden** [comment]
@hideki I'm seeing failures here:

http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-build/85/console

```
com.couchbase.lite.replicator.ReplicationTest > testGoOffline[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at com.couchbase.lite.replicator.ReplicationTest.testGoOffline(ReplicationTest.java:2627)
```

**Comment by hideki** [comment]
I have observed `ReplicationTest.testGoOfflien()` fails. Not always, but frequent enough. I already filed ticket. #488
