### ISSUE TITLE
onChangeListener called earlier than the completion of the transaction

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#524]
getDatabase().beginTransaction();
......
document.putProperties(map);......

-> onChangeListener -> Document changed

..... sleep
getDatabase().endTransaction(true);

It's normal work? If I do not want to confirm the transaction and will do getDatabase().endTransaction(false); I also got an event(((

**Comment by QRPro** [comment]
version 0.0.0-503

**Comment by hideki** [comment]
Hi @QRPro You don't explicitly need to call Database.beginTransaction() and Database.endTransaction(). CBL Android/Java internally calls it when user saves a document.

**Comment by QRPro** [comment]
We use beginTransaction() and getDatabase().endTransaction(); to roll back the transaction if we have a problem. document.putProperties not always succeeds!

Example:


getDatabase().beginTransaction();
......
Boolean r1 = document.putProperties(map);
Boolean r2 = document.putProperties(map2);

if (r1 && r2)
  getDatabase().endTransaction(true);
else {
  getDatabase().endTransaction(flase);
  ShowReport("Error: try again");
}

**Comment by QRPro** [comment]
try {
   document.putProperties(map);
   return true;
} 
catch (Exception e) {
  return false;
}

**Comment by hideki** [comment]
If app calls beginTransaction() and endTransaction(), it makes nested transaction. I believe it might work, but it is not expected way to use Couchbase Lite.

ChangeListener is not fired from endTransaction(). So if app calls beginTransaction() and endTransaction(), changeEvent could be fired between them.
