### ISSUE TITLE
Missing "contentURL" property on attachments

### ISSUE THREAD

**Issue by jcamp1** [couchbase/couchbase-lite-java-core#547]
Greetings,

On iOS there is a contentURL property on attachments:
@property (readonly) NSURL* contentURL;

 This allows direct access to the attachment content file. This property or any way of getting the absolute path of an attachment blob file is missing in the java version.

Thanks!
Justin

**Comment by hideki** [comment]
contentURL is not documented in the official site. In general, it means the method is not official. In general, we don't recommend to use it.
http://developer.couchbase.com/mobile/develop/references/couchbase-lite/couchbase-lite/attachment/attachment/index.html

For this method, we will port contentURL method from iOS and put @private annotation to the method

**Comment by jcamp1** [comment]
Thanks @hideki!

**Comment by hideki** [comment]
Hi @jcamp1,
Fix is in master branch. If you are using maven, version number is 0.0.0-511.  If you have time, please try it. 
Thanks!
