### ISSUE TITLE
restart of a replication shouldn't hang if the replication is already stopped.

### ISSUE THREAD

**Issue by deanelhard** [couchbase/couchbase-lite-java-core#575]
Calling restart on a replication will hang if the replication is already stopped.  Even if you check before calling restart, there is a race if the replicator stops between the check and the establishment of the listener inside the restart method.

Below is the code in Replication.java.  The restart method needs to check if the replicator is already  stopped before waiting on the countdown latch.

```
    public void restart() {

        final CountDownLatch stopped = new CountDownLatch(1);
        addChangeListener(new ChangeListener() {
            @Override
            public void changed(ChangeEvent event) {
                if (event.getTransition() != null && event.getTransition().getDestination() == ReplicationState.STOPPED) {
                    stopped.countDown();
                }
            }
        });

        stop();

        try {
            stopped.await();
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

        start();
}
```

**Comment by hideki** [comment]
Hi @deanelhard,
Thank you for your bug report. We will fix this as soon as possible.
