### ISSUE TITLE
Changetracker does not automatically login again after expired session

### ISSUE THREAD

**Issue by b-smets** [couchbase/couchbase-lite-java-core#576]
I am currently using custom authentication with OAuth2 to create short sessions of only a few minutes. The idea is that these sessions are automatically refreshed as long as the user is logged in (refresh token is valid). This all works fine until the session cookie on the replication expires.
The change tracker does not make any attempt to login again and just ends up in an endless loop trying to reconnect, failing with a 401 and sleeping for a while:

`W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@52802fb4: started ChangeTracker com.couchbase.lite.replicator.ChangeTracker@528b41dc
E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@528b41dc: Change tracker got error 401
W/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@528b41dc: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@52802fb4
E/Sync﹕ Change tracker stopped during continuous replication`

I would expect the replication to use its registered authenticator to login a second time whenever a 401 is received.

I am using the version 1.0.4 of CouchbaseLite Android to do this.

**Comment by b-smets** [comment]
Some closer examination of ChangeTracker.java revealed that this probably works for basic auth through the form of the BasicAuthenticator#authUserInfo() method returning "username:password". 
This is not possible for any other auth method as we try to avoid sending username/password credentials directly to SG.

**Comment by hideki** [comment]
Hi @b-smets,
Current version of CBL replicator does not automatically update session. With current design, this is client application's responsibility. When the replicator encounters 401 issue, 1) stop replicator, 2) retrieve new session id from an authentication server, 3) set new session id into the replicator, 4) restart replicator.
You might already read this article. It could help you.
http://developer.couchbase.com/mobile/develop/guides/sync-gateway/administering-sync-gateway/authenticating-users/index.html#custom--indirect--authentication
Hope this helps you.
Thanks!

**Comment by b-smets** [comment]
The problem with this approach is that the changetracker 401 is handled completely internally. The only thing we get is a change event in our changelistener indicating a transition from status IDLE to IDLE.
We could check for the replication's last error but this is something like:
`Change tracker stopped during continuous replication`
It seems very wrong to try and parse the exception message and even if we did, we cannot make the assumption that it was stopped either due to an expired session or due to a legitimate stop of the replication.

**Comment by hideki** [comment]
For the custom authentication, the replicator should be given session id. The replicator is not able to know how to authenticate. Retrieving new session id is user's (Couchbase Lite user) responsibility.

I understand the current implementation of CBL Android's replicator's error handling is not developer friendly. Replicator should stop immediately when session id is expired, and calls Replicator.ChangeListener with appropriate error status. We will work for it.

**Comment by b-smets** [comment]
The replicator has the authenticator registered which is used when it is initially started so it definetly knows how to authenticate (See ReplicationInternal#login() on line 398). It currently does a strange hack to automatically reconnect for basic auth (See https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L291) but not for auther auth types and thats why I am confused. It should simply request the login path and login params from the authenticator and login accordingly to renew the session, I think.

At the moment I am using a very dirty hack in my changelistener fetching the last error from the replication and checking the actual error message as this is a generic java.lang.Exception. See 
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L798 lines 798-800. Is there a better workaround possible for now?

**Comment by b-smets** [comment]
This seems to have gotten a bit more annoying in 1.1.0.

The initial authentication and replication works fine until the session expires. When it does, the change tracker receives a 401 error which causes it to stop. PullerInternal is notified of this change but it simply tries to restart the replication (see PullerInternal#processChangeTrackerStopped() for continuous replication).
Aside from a line in the log I get no notification in my client application. No further change-events are sent to my event listener.

Also check the code below (https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L789):
```java
                    String msg = String.format("Change tracker stopped during continuous replication");
                    Log.e(Log.TAG_SYNC, msg);
                    parentReplication.setLastError(new Exception(msg));
```
Even if I got a change event in my change listener, the last error would be completely useless as it contains no information as to why the change tracker was stopped (could be 401 unauthorized, could be one of 1000 other reasons.)

What would be really great to get into the change event as last error (https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L330)
```java
  if (status.getStatusCode() >= 300 && !Utils.isTransientError(status)) {
                    Log.e(Log.TAG_CHANGE_TRACKER, "%s: Change tracker got error %d", this, status.getStatusCode());
                    this.error = new HttpResponseException(status.getStatusCode(), status.getReasonPhrase());
                    break;
                }
```

If we would get the HttpResponseException with the status code, I could take appropriate action (albeit the really dirty workaround by destroying the replication and creating a new one)

**Comment by borrrden** [comment]
Maybe the implementation of IChallengeResponseAuthenticator on .NET will help https://github.com/couchbase/couchbase-lite-net/search?utf8=%E2%9C%93&q=IChallengeResponseAuthenticator (a search for its usage)

**Comment by zgramana** [comment]
The team is reviewing this from an implementation perspective this sprint, and we will review the results at the next sprint planning meeting on Friday.

**Comment by zgramana** [comment]
@snej is going to put a spec together.

**Comment by hideki** [comment]
https://github.com/couchbaselabs/couchbase-lite-api/issues/121

**Comment by snej** [comment]
From reading the discussion, this looks less like an API limitation, and more like an implementation issue with reporting replication errors. I think @hideki's [first comment](https://github.com/couchbase/couchbase-lite-java-core/issues/576#issuecomment-94993157) is sound: the app should get a 401 error from the Replication and respond by updating its token or cookie or whatever, then restarting the replication. It sounds like that's not working correctly in 1.1 on Android.

**Comment by hideki** [comment]
It seems Sync Gateway updates session expired time whenever client access to Sync Gateway. Please see following log messages that starts with `Set-Cookie:`.
In case client or custom authenticator set appropriate `TTL` value for {db}/_session Admin REST API, SyncGateway_SessionID should not be expired during replication. 

```
$ make get_changes
curl -i --cookie "SyncGatewaySession=22b6f950bbf32c99706ebedbc25ffc8c71f70027" -H "Content-Type: application/json" -X GET  http://localhost:4984/db/_changes
HTTP/1.1 200 OK
Cache-Control: private, max-age=0, no-cache, no-store
Content-Type: application/json
Server: Couchbase Sync Gateway/1.1.1
Set-Cookie: SyncGatewaySession=22b6f950bbf32c99706ebedbc25ffc8c71f70027; Expires=Fri, 04  Dec 2015 22:20:55 UTC
Date: Fri, 04 Dec 2015 22:17:55 GMT
Content-Length: 75

{"results":[
{"seq":1,"id":"_user/user1","changes":[]}
],
"last_seq":"1"}
$ 
$ make get_changes
curl -i --cookie "SyncGatewaySession=22b6f950bbf32c99706ebedbc25ffc8c71f70027" -H "Content-Type: application/json" -X GET  http://localhost:4984/db/_changes
HTTP/1.1 200 OK
Cache-Control: private, max-age=0, no-cache, no-store
Content-Type: application/json
Server: Couchbase Sync Gateway/1.1.1
Set-Cookie: SyncGatewaySession=22b6f950bbf32c99706ebedbc25ffc8c71f70027; Expires=Fri, 04 Dec 2015 22:21:49 UTC
Date: Fri, 04 Dec 2015 22:18:49 GMT
Content-Length: 75

{"results":[
{"seq":1,"id":"_user/user1","changes":[]}
],
"last_seq":"1"}
$ 
```

**Comment by hideki** [comment]
1. Sync Gateway periodically returns the response with `Set-Cookie: SyncGatewaySession=xxxx; Expires=xxx` for REST API request with session ID. Couchbase Lite automatically update Cookie with new value and stores it in CookieStore. Once replication starts with successful initial request, Unauthorized Error (401) should not be occurred.

2. In case Unauthorized Error (401) occurs, Replicator will stop immediately with sending `Replication.ChangeEvent` (master or after v1.2.0). Please check error status by calling `Replication.ChangeEvent.getSource().getLastError()`. If the error is caused by expired session, please obtain new Sync Gateway through custom authentication, and re-start the replication. Note: Couchbase Lite does not know about custom authentication server. Obtaining new Sync Gateway Session ID is client application's responsibility.
