### ISSUE TITLE
getAllDocumentsQuery() ignores PrefixMatchLevel

### ISSUE THREAD

**Issue by sergio91pt** [couchbase/couchbase-lite-java-core#583]
QueryOptions#getPrefixMatchLevel is only called on View.java and should also be called from Database#getAllDocs(QueryOptions).

**Comment by hideki** [comment]
Hi @sergio91pt,

Did you have a chance to write unit test for this issue?

**Comment by sergio91pt** [comment]
Not yet. I'll do it tomorrow, for both all docs and views.

**Comment by sergio91pt** [comment]
Hi @hideki,
Only did it for all docs, as there was already a test with views.
