### ISSUE TITLE
toLiveQuery() forgets PrefixMatchLevel

### ISSUE THREAD

**Issue by sergio91pt** [couchbase/couchbase-lite-java-core#585]
Steps to reproduce:
Query query = db.createAllDocumentsQuery();
query.setPrefixMatchLevel(1);
LiveQuery liveQuery = query.toLiveQuery();

**Comment by hideki** [comment]
Hi @sergio91pt,

Did you have a chance to write unit test for this issue?

**Comment by sergio91pt** [comment]
Unit tests for the Query->LiveQuery conversion, to make sure the copy constructor is always used. Didn't even cross my mind, as I always saw it as a setter issue. I'll do it tomorrow.

**Comment by hideki** [comment]
Root cause of this issue could be caused by constructor's setting variable. But we would like to  understand the problem by test. And also,  we would like to make sure the issue will not be reproducible in the future.

**Comment by sergio91pt** [comment]
Hi @hideki,
Just uploaded the unit tests. I took the reflection approach, by comparing every field (even those not exposed) in the Query class. It is a slightly more future proof approach but also more prone to breakage. Is this okay or do you prefer a traditional test?

**Comment by hideki** [comment]
Hi @sergio91pt ,
Thank you for writing unit test. Originally I misunderstood the issue. You reported the issue of constructor. But I considered that code you posted caused the problem. Next time, you don't need to write unit test for constructor as you said.
Thanks!
