### ISSUE TITLE
Handle SQL 'attach' table incompatibility in CBL 1.1

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#596]
Per @snej's guidance:
```
detect whether a database was created on Obj-C-1.1 and if so recreate the ‘attach’ table.

When opening a database, check whether the ‘attach’ table exists. If not:
Create the ‘attach’ table.
Iterate over every revision containing attachments (rows in ‘revs’ whose ‘noattach' column is not 1.)
Parse the revision’s JSON and get the ‘_attachments’ property.
For every item in that map, create a row in the ‘attach’ table. (It may be possible to reuse or at least copy existing Database code, since this is the same thing that happens when adding a revision to the database.)
```

**Comment by hideki** [comment]
Hi @pasin,
Could you please generate a sample database with some attachments using CBL iOS v1.1?
Thanks!

**Comment by pasin** [comment]
Here is an iOS sample DB (100 docs, each doc has 1 attachment).

https://www.dropbox.com/s/tfuqly14ez0xwy5/iosdb.zip?dl=0

Could you please provide a sample db created from android as well?

**Comment by pasin** [comment]
@borrrden could you grab the iOS database above and test it with .NET platform? Also could you post your .NET sample db here for @hideki and me to test?

**Comment by hideki** [comment]
CBL Android v1.1 Database files from TODO Lite sample app

2/3 docs with 2 attachments
https://www.dropbox.com/s/u5ym1sqwvkqpee4/files.zip?dl=0

**Comment by pasin** [comment]
Please ensure that the database can be opened and used (create/update/delete/attachment). Please also try to create a view and query.

**Comment by pasin** [comment]
Please also make sure that the database schema version is synced across platform.

Changes in iOS v1.1.0:

https://github.com/couchbase/couchbase-lite-ios/blob/release/1.1.0/Source/CBL_SQLiteStorage.m#L285-L291

https://github.com/couchbase/couchbase-lite-ios/blob/release/1.1.0/Source/CBL_SQLiteStorage.m#L365-L371

**Comment by pasin** [comment]
I corrected the zip file (removed db from master branch). Please re-download (same link).

**Comment by hideki** [comment]
CBL Android 1.0.4 ToDo Lite Database
https://www.dropbox.com/s/ja0a5fba27g6u9z/files-1.0.4.zip?dl=0

CBL Android 1.1.0 ToDo Lite Database
https://www.dropbox.com/s/c0enni6ywifpk7a/files-1.1.0.zip?dl=0

**Comment by pasin** [comment]
CBL iOS 1.0.4 (10 docs, each doc has 2 attachments).
https://www.dropbox.com/s/nixw5y3f3r32klt/ios104.zip?dl=0

CBL iOS 1.1.0 (10 docs, each doc has 2 attachments)
https://www.dropbox.com/s/ipm54kmdt6j5g7m/ios110.zip?dl=0

**Comment by borrrden** [comment]
CBL .NET 1.0.4 (3 docs, 1 with 1 attachment, 1 deleted, 1 local doc)
https://www.dropbox.com/s/wpu7y6mkkff6pw4/net104.zip?dl=0

CBL .NET 1.1.0 (3 docs, 1 with 1 attachment, 1 deleted, 1 local doc)
https://www.dropbox.com/s/fuusgbiwah3l5iw/net110.zip?dl=0

**Comment by borrrden** [comment]
I've verified all four of the above databases can be imported using .NET

**Comment by pasin** [comment]
Per request by @hideki , I re-made the iOS sample DB.

1 doc (id=doc1), 2 attachments (attachment1 and attachment2)

CBL iOS 1.0.4 
https://www.dropbox.com/s/nixw5y3f3r32klt/ios104.zip?dl=0

CBL iOS 1.1.0
https://www.dropbox.com/s/ipm54kmdt6j5g7m/ios110.zip?dl=0
