### ISSUE TITLE
E/CBLite﹕ Cannot parse version code:

### ISSUE THREAD

**Issue by ntorvik** [couchbase/couchbase-lite-java-core#612]
After recompiling from 1.0.3 to 1.0.4 my app logcat displays this everytime the app starts.

05-05 16:35:18.036    4477-4477/com.projects.xxxxxx E/CBLite﹕ Cannot parse version code:
05-05 16:35:18.036    4477-4477/com.projects.xxxxxx E/CBLite﹕ Cannot parse version code:

**Comment by hideki** [comment]
Hi @ntorvik ,

Some reason VERSION_CODE is non Integer String. Could you please check the value in Version.java file?
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.0.4/src/main/java/com/couchbase/lite/support/Version.java#L37-L42

Thanks,
Hideki
