### ISSUE TITLE
Push a small doc with an attachment failed

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#614]
Pushing a small doc (less than 100 bytes) with an attachment failed.

**Comment by pasin** [comment]
I wrote a fix to unblock P2P testing between Android and iOS here:
https://github.com/couchbase/couchbase-lite-java-core/blob/feature/p2pfix/src/main/java/com/couchbase/lite/replicator/PusherInternal.java#L581-L589

Please note that I understand that iOS doesn't check the size of the JSON document to determine if we will gzip the json document or not. We may consider removing that (See link below):
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Pusher.m#L440-L443

**Comment by hideki** [comment]
CBL iOS check original content length in`- (void) addGZippedData: (NSData*)data`
```
- (void) addGZippedData: (NSData*)data {
    if (data.length >= kMinDataLengthToCompress) {
        NSData* compressed = [NSData gtm_dataByGzippingData: data];
        if (compressed.length < data.length) {
            data = compressed;
            [self setValue: @"gzip" forNextPartsHeader: @"Content-Encoding"];
        }
    }
    [self addData: data];
}
```

**Comment by hideki** [comment]
Hi @pasin,

Following is relatively small document which has one attachment. Length is 288.  It is pretty challenging to create JSON document with attachment which size is smaller than 100 characters. Can you post your test JSON data? I am just curious.
```
{
  "_rev": "1-c9d9592d5e6233c22cf67505211c2728",
  "_id": "doc1",
  "_revisions": {
    "start": 1,
    "ids": [
      "c9d9592d5e6233c22cf67505211c2728"
    ]
  },
  "_attachments": {
    "attachment.png": {
      "length": 519173,
      "follows": true,
      "digest": "sha1-LmsoqJJ6LOn4YS60pYnvrKbBd64=",
      "revpos": 1,
      "content_type": "image\/png"
    }
  },
  "key": "abc"
}
```

**Comment by pasin** [comment]
@hideki , actually it turned out it's not because of the size of the document. It's because canSendCompressedRequests() returns false. Sorry for the confusion.
