### ISSUE TITLE
Multi-part attachment disposition should use attachment name

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#615]
Currently the disposition is using the actual .blob file name when sending an attachment in multi-part requests. Instead the attachment name should be sent.

Current:
```
attachment; filename="23294A2D37BE0623A43EDF1AC3D9873758629696.blob"
```

Correct:
```
attachment; filename="<Attachment name>"
```

This is a showstopper for P2P replication between Android and iOS.

**Comment by pasin** [comment]
To unblock P2P testing between Android and iOS, I have a fix written here:
https://github.com/couchbase/couchbase-lite-java-core/blob/feature/p2pfix/src/main/java/com/couchbase/lite/replicator/PusherInternal.java#L618

Compared with the iOS implementation:
https://github.com/couchbase/couchbase-lite-java-core/blob/feature/p2pfix/src/main/java/com/couchbase/lite/replicator/PusherInternal.java#L618

**Comment by hideki** [comment]
PR #622 covers this issue
