### ISSUE TITLE
Old revisions are not replicated

### ISSUE THREAD

**Issue by sergio91pt** [couchbase/couchbase-lite-java-core#623]
If I make two revisions in the same document, using a transaction, only the last one is replicated.
I'm seeing this on a document with attachments (added in the second revision - multipart push).

The revId is as expected on the server, but it doesn't have the previous version which hinders use cases like filtering attachments.

**Comment by hideki** [comment]
Hi @sergio91pt,
To be honest with you, I am not sure if this is as spec or bug.
Could you please provide us more detailed information? Your detailed expectation and also steps to reproduce this scenario.
Thanks!
