### ISSUE TITLE
PhoneGap: View.updateIndex() is too slow

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#630]
This issue is originally posted on Couchbase Mobile Google Group.
https://groups.google.com/forum/#!topic/mobile-couchbase/urIqcOocmq4

```
Few days back you had given me a updated build of cblite phonegap plugin which improved the view performance for android. I reported that it took around 7 seconds initially to index about 150 docs but then it dropped to milliseconds. 

Seems like i judged it very early and with only a particular type of docs. I changed my document and added a few more fields to make it little big. I added around 100 docs on a click of button to cblite and then performed a view query. It took around 2.2 - 2.5 seconds for android to index that view first and then return the data. This time interval is very long for the users of my application. Every time i add 100 docs and then query the view, it takes about that much time to return the data. 

Now my application involves modules wherein i need to call 2-3 different views after adding about 12 or more docs. Now it takes 400 ms for android to index the view after adding 10 docs (the view which i am talking about here is a simple view with just a emit, no reduce or heavy emit's. If  view has a reduce function or some complex emit structure then the above times mentioned are even more higher). So when all my view are called one after another the time adds up and it takes about 5 seconds for my views with reduce function to return data from cblite.

Also there are many other screens which involve calling multiple views and whenever and significant change is made to db, the first query thereafter to all these views take time and when u add up the time it is in seconds.

Speaking from a user perspective i cannot make the user wait for those many seconds every time they create new records and hence the app becomes unusable on android.

Same app on ios indexes views in milliseconds. Even for 100 docs inserted , a view query takes anywhere between 150 ~ 200 milliseconds to index and return data. 2200 ms and 200ms. Thats a difference of 2000 ms between ios and android. You can check the same in your todo lite phonegap app which i have modified to show my stats. I am attaching the source code dropbox folder link here. You can download the app and run tests on it. 

I know the performance you get on iOS will not be matched on android due to fundamental differences but what i need to find out that is there any way possible to make performance on android relatively close to iOS if not match it. Can we do something to bring the view indexing time down. Are we doing anything fundamentally wrong while working with cblite ? maybe you can look at the ToDoLite code and help us out somewhere.

I am letting my environment know under which i got the view indexing times

FOR ANDROID
Device  - Moto G 1.2 Ghz quad core running android 5.0.2
Ram - 1 gb
view index time for 100 docs - around 2.2 secs
view index time for 10 docs - around 400 ms

FOR IOS
Device  - Iphone 5s with ios 7
view index time for 100 docs - around 150ms
view index time for 10 docs - around 20 ms

The cblite plugin used for above test was taken from the below link which u gave earlier.

http://cbfs-ext.hq.couchbase.com/builds/Couchbase-Lite-PhoneGap-Plugin_1.0.4-47-63.zip

Todo Lite Source code link

https://www.dropbox.com/s/xmiip8fbugh6682/ToDoLite%20%28copy%29.tar.gz?dl=0

Awaiting your feedback !
Thanks !
```

**Comment by hideki** [comment]
Test results:

- Performance measured by ToDo Lite Sample which was modified by customer
https://www.dropbox.com/s/xmiip8fbugh6682/ToDoLite%20%28copy%29.tar.gz?dl=0

- Test platforms: I used iOS simulator and Genymotion simulator

- Measure elapsed time for 100 docs insertion and 100 doc indexing

- Result

| Platform | iOS | Android |
| ------------- | ------------- | ------------- |
| Insert 100 Docs | 27ms | 239ms |
| Index 100 docs | 18ms | **473ms** |

- Sample Document from code
```javascript
{
                    amt: i,
                    channels: "vinaynb@gmail.com",
                    clear: true,
                    createdAt: "2015-05-07T08:11:51.974Z",
                    creditAccount: "Checking",
                    creditAccountKey: "aa019602-da64-4a0f-8dec-5ab18b3f03ff",
                    creditCat: "Cash & Bank",
                    creditSubCat: "",
                    date: "Wed May 13 2015 00:00:00 GMT+0530 (IST)",
                    debitAccount: "Charity",
                    debitAccountKey: "84dbde7b-3165-4c4c-9292-f636cc524093",
                    debitCat: "Expense",
                    debitSubCat: "Activities",
                    isBill: false,
                    memo: "",
                    notificationInfo: {
                        daysBefore: null,
                        notifications: null
                    },
                    parentCycle: null,
                    parentTransactionId: null,
                    repeat: null,
                    split: null,
                    totalAmt: null,
                    tranType: "Expense",
                    type: "trans",
                    unclearedAmt: null,
                    updatedAt: null
}
```
NOTES: JSON's string values contain only ASCII characters. So, slowness might not come from JSON collator.

**Comment by sergio91pt** [comment]
@hideki Have you tried using [traceview](http://developer.android.com/tools/debugging/debugging-tracing.html) to check which functions are taking most time?

Basically you surround the method call with:
```java
// starts tracing to "/sdcard/indexing.trace"
// You need android.permission.WRITE_EXTERNAL_STORAGE
Debug.startMethodTracing("indexing");
view.updateIndex();
Debug.stopMethodTracing();
```
You can open the file with Eclipse or the device monitor.

**Comment by hideki** [comment]
@sergio91pt, Thank you very much for your advise. I have not used TraceView. I will try it.

**Comment by snej** [comment]
:+1: glad to hear there's a good time-profiling tool for Android. I've sped up the iOS/Mac version a lot using similar tools.

**Comment by hideki** [comment]
Note to Self:

#### Actual command we are tackling
##### 10.5.4. /db/_design/design-doc/_view/view-name
- http://docs.couchdb.org/en/latest/api/ddoc/views.html

#### Additional test result

##### Original test tool on Nexus  6

| action | 1st | 2nd |
------------- | ------------- | -------------
100 docs insertion | 332ms | 366ms
100 docs indexing and query | **1981ms** | 1928ms
100 docs query | 71ms | 59ms

##### Applied [PR](https://github.com/couchbase/couchbase-lite-java-javascript/pull/10) on Nexus 6

| action | 1st | 2nd |
------------- | ------------- | -------------
100 docs insertion | 345ms | 338ms
100 docs indexing and query | **325ms** | 315ms
100 docs query | 49ms | 52ms

##### Original test tool on Genymotion
| action | 1st | 2nd |
------------- | ------------- | -------------
100 docs insertion | 272ms | 221ms
100 docs indexing and query | 470ms | 471ms
100 docs query | 58ms | 61ms

##### Applied [PR](https://github.com/couchbase/couchbase-lite-java-javascript/pull/10) on Genymotion
| action | 1st | 2nd |
------------- | ------------- | -------------
100 docs insertion | 261ms | 238ms
100 docs indexing and query | 282ms | 247ms
100 docs query | 53ms | 56ms

#### NOTE
From above test result, applying [PR](https://github.com/couchbase/couchbase-lite-java-javascript/pull/10) makes indexing operation around 6 time faster with the test tool this test is using.

**Comment by vinaynb** [comment]
I noticed you referenced a pull request which has made some improvements and your test result shows them.

@hideki I would just like to know when do you intend to merge the PR and consequently the plugin can be updated. The urgency on my part is partly because the application which is using this plugin is live on the Android Play Store right now and it would help us tremendously on the performance front if we can reduce the indexing time in the app.

Thanks again a lot for the help.

**Comment by hideki** [comment]
Hi @vinaynb,

Accepting community developer's PR might take a time. Meanwhile, you can build from his source codes https://github.com/couchbase/couchbase-lite-java-javascript/pull/10 . 

Thanks,
Hideki

**Comment by vinaynb** [comment]
UPDATE 
I built the source code from the PR and the indexing time are slashed by 6x !!
The plugin seems to be working fine with the modification no issues reported till now.

@hideki thanks for the help..is very much appreciated and i hope the PR is merged so that other developers who are in search of performance can have the updated plugin.

**Comment by hideki** [comment]
Hi @vinaynb,

Thank you for your updates. I am glad to hear your app's indexing speed improved 6 times. We are working for merging the PR. But the process is taking the time.

**Comment by hideki** [comment]
[PR](https://github.com/couchbase/couchbase-lite-java-javascript/pull/10) was merged. JavaScript map/reduce could improve its performance around 6times.
