### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#633]
Hi, we use manual replication (not continious). Replication gets a lot of small objects (>20000). After downloading more than 8,000 objects begins to slow GUI.
05-19 12:07:42.138: D/dalvikvm(13886): GC_FOR_ALLOC freed 6917K, 4% free 306913K/318132K, paused 761ms, total 761ms

Version: 0.0.0-524

**Comment by hideki** [comment]
Hi @QRPro,

Does your application replicate against Sync Gateway or CouchDB?

**Comment by QRPro** [comment]
CouchDB

**Comment by zgramana** [comment]
Duplicates https://github.com/couchbase/couchbase-lite-android/issues/597
