### ISSUE TITLE
Jackson deserialization exception

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#635]
Appears when waiting for changes.
```
E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@242261ec: Exception in change tracker
    org.codehaus.jackson.JsonParseException: Unexpected end-of-input: expected close marker for ARRAY (from [Source: org.apache.http.conn.EofSensorInputStream@1e95fd5f; line: 1, column: 1])
```
The Netscaler proxy between the WAN and SG may potentially be over-aggressively buffering `_changes` feed response stream due to gzip + chunked transfer. @snej dealt with [a similar, if not the same, issue in iOS](https://github.com/couchbase/couchbase-lite-ios/commit/88f59f729ebff0dad7bdd9e1b2c64f80347fa086), which may possibly be helpful. The reporter is going to try to bypass the Netscaler to see if that isolates the issue.

**Comment by hideki** [comment]
@zgramana, Can we ask customer to modify coiuchbase_lite code to print JSON string that Jackson failed to parse?

**Comment by zgramana** [comment]
It's the empty changes feed response when the change tracker times out (without sending "]}").

**Comment by hideki** [comment]
Hi @zgramana,

Log message was written at https://github.com/couchbase/couchbase-lite-java-core/blob/c6e8d2caa5eda805f8e08fba70d154e0f819a919/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L422

The exception was thrown at https://github.com/couchbase/couchbase-lite-java-core/blob/c6e8d2caa5eda805f8e08fba70d154e0f819a919/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L344 or https://github.com/couchbase/couchbase-lite-java-core/blob/c6e8d2caa5eda805f8e08fba70d154e0f819a919/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L374

However ChangeTracker tries to retrieves _changes feed after waiting some amount of time. https://github.com/couchbase/couchbase-lite-java-core/blob/c6e8d2caa5eda805f8e08fba70d154e0f819a919/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L426

I think this is only Error message issue.

Thanks

**Comment by zgramana** [comment]
I think [this check](https://github.com/couchbase/couchbase-lite-java-core/blob/c6e8d2caa5eda805f8e08fba70d154e0f819a919/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L342) should `entity.getContentLength() > 0` since HTTP's [chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding), by the spec, will not include a `Content-Length` header in the HTTP response. 

In the [Note 2 comment](https://github.com/couchbase/couchbase-lite-java-core/blob/c6e8d2caa5eda805f8e08fba70d154e0f819a919/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L340), it indicates a missing `Content-Length` header results in -1. 

Presumably the comment in [Note 1](https://github.com/couchbase/couchbase-lite-java-core/blob/c6e8d2caa5eda805f8e08fba70d154e0f819a919/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L339) applies to return values of -1 as well as 0.

**Comment by hideki** [comment]
Hi @zgramana,

In 1.0.4 that I believe Ryanair uses, [no getContentLength() check](https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.0.4/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L350). 

I added [getContentLength() check](https://github.com/couchbase/couchbase-lite-java-core/commit/45fdea615923ef844335a778216e632c491e5a08#diff-bff8e38770f7eb8f623534cff1a8bbeb) for fixing #383. 

1.1.0 might solve the issue. Is it possible to ask Ryanair to try 1.1.0 developer preview version?

However, if `getContentLength()` is 0, [ChangeTracker will stop](https://github.com/couchbase/couchbase-lite-java-core/blob/c6e8d2caa5eda805f8e08fba70d154e0f819a919/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L359-L363). I am not sure if it is ideal behavior for Ryanair.

**Comment by hideki** [comment]
According to Java doc [HttpEntity.getContentLength()](https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpEntity.html#getContentLength()), method return -1 if unknown. I believe `!= 0` is better.

**Comment by zgramana** [comment]
The problem is when chunked transfer encoding is used. Content length will be unknown, and presumably return `-1`. If you'd rather stay with `!= 0` then you'd need to check [`HttpEntity.isChunked()`](https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpEntity.html#isChunked()) since ultimate stream length will be unknown until the response closes.

Either way, ChangeTracker definitely shouldn't stop.

**Comment by hideki** [comment]
Note to self:

- As @zgramana explained in original comment, the exception was caused by parsing `{"results":[` without receiving `]}`.
- @jens 's comment (https://github.com/couchbase/couchbase-lite-ios/issues/155#issuecomment-26527449) describes this problem clearly.
- [Fix](https://github.com/couchbase/couchbase-lite-ios/commit/88f59f729ebff0dad7bdd9e1b2c64f80347fa086) for couchbase/couchbase-lite-ios/issues/155 is no longer used in current version of CBL iOS. 
- Following link and code snippet are current CBL iOS ChangeTracker retry logic when error occurs.

[Current CBL iOS ChangeTracker retry logic](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/ChangeTracker/CBLSocketChangeTracker.m#L236-L258)
```
        // JSON must have been truncated, probably due to socket being closed early.
        if (_mode == kOneShot) {
            [self failedWithError: [NSError errorWithDomain: NSURLErrorDomain
                                                       code: NSURLErrorNetworkConnectionLost
                                                   userInfo: nil]];
            return;
        }
        NSTimeInterval elapsed = CFAbsoluteTimeGetCurrent() - _startTime;
        Warn(@"%@: Longpoll connection closed (by proxy?) after %.1f sec", self, elapsed);
        if (elapsed >= 30.0) {
            // Looks like the connection got closed by a proxy (like AWS' load balancer) while the
            // server was waiting for a change to send, due to lack of activity.
            // Lower the heartbeat time to work around this, and reconnect:
            self.heartbeat = MIN(_heartbeat, elapsed * 0.75);
            [self clearConnection];
            [self start];       // Next poll...
        } else {
            // Response data was truncated. This has been reported as an intermittent error
            // (see TouchDB issue #241). Treat it as if it were a socket error -- i.e. pause/retry.
            [self failedWithError: [NSError errorWithDomain: NSURLErrorDomain
                                                       code: NSURLErrorNetworkConnectionLost
                                                   userInfo: nil]];
        }
```

TODO:
- Added right ChangeTracker retry logic when `getContentLength()` is 0 or `JsonParseException` is thrown.

**Comment by zgramana** [comment]
Sounds great!
