### ISSUE TITLE
Write Test if not covered: Query not working properly with keys

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#637]
https://forums.couchbase.com/t/query-not-working-properly-with-keys/3901

I am using couch base lite 1.0.4 for android when i running follwoing Query i am getting count is 0 but data is presenet in CBl.

```
com.couchbase.lite.View view = database.getView("getRelated");
if (view.getMap() == null){
    Mapper mapper = new Mapper() {
        @Override
        public void map(Map<String, Object> document, Emitter emitter) {
            java.util.List<Object> keys = new ArrayList<Object>();
            keys.add(document.get("relation"));
            keys.add(document.get("summery"));
            emitter.emit(keys, document.get("_id"));
        }
    };
    view.setMap(mapper, "1");
}
Query query = view.createQuery();
java.util.List<Object> keys = new ArrayList<Object>();
keys.add("text");
keys.add("ok");
query.setKeys(keys);
try {
    QueryEnumerator enumerator =  query.run();
    Log.i(Application.TAG,enumerator.getCount()+"");

} catch (CouchbaseLiteException e) {
    e.printStackTrace();
}
```

**Comment by sergio91pt** [comment]
If `text` and `ok` are the relation, shouldn't it be 
`keys.add(Arrays.asList("text", Collections.EMPTY_MAP))`?

And if `text` is the relation and `ok` is the "summery", shouldn't it be 
`keys = Collections.<Object>singletonList(Arrays.asList("text", "ok"))`?

Since *a* key in this map is `[relation, summery]`, those two keys can never match a compound key...

**Comment by hideki** [comment]
Hi @sergio91pt,  Thank you very much for your comment. CBL Android user could solve his/her issue by your comment.  https://forums.couchbase.com/t/query-not-working-properly-with-keys/3901/3

**Comment by hideki** [comment]
If this case is not covered by unit tests, write it.

**Comment by sergio91pt** [comment]
setKeys must match the key exactly so my first example (the one with the empty map) is wrong, it only works on setEndKey. Sorry about that.

@hideki Regarding unit tests, its covered [here](https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/ViewsTest.java#L610)

**Comment by hideki** [comment]
@sergio91pt Thanks again for your additional comment.

**Comment by hideki** [comment]
Hi @sergio91pt,

I'd like to nominate you for Couchbase Community Champions.

```
Following on from our opening of the Couchbase Developer Expert (CDE) program we're  now looking to have nominations submitted  for the Couchbase Community Champions we are meeting through our engagement.  

Perhaps it's someone you've engaged with them on IRC, Forums, Stack Exchange, or submitted a patch, built something cool using Couchbase. If they are championing bringing in Couchbase into an organisation and steering converations towards Couchbase over other solutions please let us know.

We want to reach out and say thanks and give them a shout out in our newsletter and a small gift! 
```

Can I use your email which is showed in your commits?

Thanks,
Hideki

**Comment by sergio91pt** [comment]
Hi @hideki 
Thanks for the nomination.
Sure, you can use that email.
