### ISSUE TITLE
"Window is Full" during View.updateIndex()

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#654]
Because of memory issue during `View.updateIndex()`, some of documents might be not indexed. Need to investigate.
---------

https://github.com/couchbase/couchbase-lite-android/issues/210#issuecomment-107793827
```
    W/Sync﹕ Error converting lastSequence: null to long.  Using 0
    W/CursorWindow﹕ Window is full: requested allocation 304 bytes, free space 28 bytes, window size 2097152 bytes
    W/CursorWindow﹕ Window is full: requested allocation 72 bytes, free space 48 bytes, window size 2097152 bytes
    I/art﹕ Background partial concurrent mark sweep GC freed 151301(13MB) AllocSpace objects, 2(541KB) LOS objects, 39% free, 7MB/13MB, paused 2.983ms total 104.942ms
    W/SQLiteConnectionPool﹕ The connection pool for database '+data+data+com_xxx+files+xxxx_cblite' has been unable to grant a connection to thread 20710 (CBLRequestWorker-f74e7-0) with flags 0x1 for 4.0 seconds.
    Connections: 0 active, 1 idle, 0 available.
    W/SQLiteConnectionPool﹕ The connection pool for database '+data+data+com_xxx+files+xxxx_cblite' has been unable to grant a connection to thread 20710 (CBLRequestWorker-f74e7-0) with flags 0x1 for 8.001 seconds.
    Connections: 1 active, 0 idle, 0 available.
    Requests in progress:
    executeForCursorWindow started 0ms ago - running, sql="SELECT json FROM revs WHERE sequence=?"
    W/SQLiteConnectionPool﹕ The connection pool for database '+data+data+com_xxx+files+xxxx_cblite' has been unable to grant a connection to thread 20710 (CBLRequestWorker-f74e7-0) with flags 0x1 for 12.002001 seconds.
    Connections: 0 active, 1 idle, 0 available.
```
I see quite a lot "Window is Full" warnings after this.

A bit of backstory to this: I've replicated this database that is around 108k document large. That went well, and after replication i invoke the view creation process (calling some functions for the first time that uses the views that i want created in the setup process), this is where the warnings are coming up.

Most of the documents are quite small, the largest i can tell is about 500kb document (about 2 or them), where the rest are < 10kb. 

I went obtained a copy of the sqlite database, where i can see about 230k rows, to check on "revs" tablet on "json" column to see if there are anything that is more than 2mb in size (there are none). Is this related to this issue?

-------------
https://github.com/couchbase/couchbase-lite-android/issues/210#issuecomment-107820537

There are about 108k documents in the couch database :)

Regarding device, i'm on Samsung Galaxy Tab A actual device, so its a 1.2G machine with 2gb RAM size. I have replicated with smaller databases ranging from 400 documents to 20k documents are doing fine as far as i have seen. 

From your comment, it seems this is to do with the total amount of revision records and not the limit on each record size?

-------------
https://github.com/couchbase/couchbase-lite-android/issues/210#issuecomment-107831652

For sure, the map function as follows:
```
View patientIdView = db.getView(String.format("%s/%s", patientDesignDocName, patientByIdView));
        Boolean check = patientIdView.setMapReduce(new Mapper() {

            @Override
            public void map(Map<String, Object> document, Emitter emitter) {
                Object type = document.get("type");
                if (type != null && type.toString().equals("patient")) {
                    emitter.emit(document.get("_id").toString(), document);
                }
            }
        }, null, "1.0");
```

And my patient document has about 20-25 fields i would think.

**Comment by bundeeteddee** [comment]
Thanks @hideki for helping on this.

**Comment by hideki** [comment]
Hi @bundeeteddee ,

I created simple test app. 

Create 100K docs
```
        for (int i = 0; i < 100; i++) {
            final int fi = i;
            database.runInTransaction(new TransactionalTask() {
                @Override
                public boolean run() {
                    for (int j = 0; j < 1000; j++) {
                        int id = fi * 1000 + j;
                        String ID = String.valueOf(id);
                        Map<String, Object> props = new HashMap<String, Object>();
                        props.put("type", "user");
                        props.put("number", id);
                        for(int k=0; k < 30; k++){
                          props.put("message"+k,"12345678901234567890123456789012345678901234567890");
                        }
                        Document doc = database.getDocument(ID);
                        try {
                            doc.putProperties(props);
                        } catch (CouchbaseLiteException e) {
                            Log.e(TAG, "Failed to Document.putProperties(): ID=" + ID, e);
                        }
                    }
                    Log.i(TAG, "Done x=" + (fi + 1) * 1000);
                    return true;
                }
            });
        }
```

Map/Reduce code
```
        View view = database.getView("users");
        Mapper mapper = new Mapper() {
            @Override
            public void map(Map<String, Object> doc, Emitter emitter) {
                if (doc.get("type") != null && doc.get("type").equals("user")) {
                    emitter.emit(doc.get("name"), doc);
                }
            }
        };
        view.setMap(mapper, "1.0");
```

Query code
```
            View view = database.getView("users");
            Query query = view.createQuery();
            query.setLimit(10);
            QueryEnumerator result = query.run();
            for (Iterator<QueryRow> it = result; it.hasNext(); ) {
                QueryRow row = it.next();
                Log.w(TAG, row.asJSONDictionary().toString());
            }
```

Results:
I observed some `Window is full` messages. However it seems everything are functioning correctly. `Window is full` warning is logged by SQLite or SQLite wrapper of Android. Sometimes it indicates memory issue. But I assume it is just warning for this scenario because total memory usage during View.updateIndex() is not high. 

Note: Your code emits document as value. If full document is not required, just give necessary value(s) or null. It reduce memory usage during indexing and query time.

I will close this. If you have functional problem, please reopen the ticket or let us know!

**Comment by bundeeteddee** [comment]
Hi @hideki , thanks for looking into it. And i agree it is functional still just with those warnings coming up. Cheers!
