### ISSUE TITLE
Creating authenticator with empty password throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#664]
### Given
```
com.couchbase.lite.auth.Authenticator auth = AuthenticatorFactory.createBasicAuthenticator("GUEST", "");
```
### Expected
Empty password sent during HTTP challenge/response.

### Observed
```
java.lang.ArrayIndexOutOfBoundsException: 1
at com.couchbase.lite.support.RemoteRequest.preemptivelySetAuthCredentials(RemoteRequest.java:281)
```
### Note
There's an unchecked array index access after a string split on [line 271](https://github.com/couchbase/couchbase-lite-java-core/blob/733954834d71d7b15426f4c685c8ff002461bbb1/src/main/java/com/couchbase/lite/support/RemoteRequest.java#L271).

### Workaround

In the case of Sync Gateway's GUEST user, no authenticator is used at all. In fact, the GUEST user is the automatic user context for all anonymous, unauthenticated users.

**Comment by hideki** [comment]
NOTE: 70d7781 is set empty password if password is not set. If this does not work, we will add Workaround which is no authenticator for username GUEST.
