### ISSUE TITLE
couchbase-lite-java-core jar Compile issue.Make Attachment.getContentURL public!

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#675]
Trying to make my own couchbase-lite-java-core 1.1.0 jar.
Using latest others supporting jar(Jackson,stateless) files

https://github.com/couchbase/couchbase-lite-java-core/blob/a832e407d4f31f0a0601a1bc8a0e6a48c4fa688e/README.md

Somehow the dependency files are not downloaded during complie.

So end up with below compile error,
 
Description	Resource	Path	Location	Type
The type com.fasterxml.jackson.databind.ObjectMapper cannot be resolved. It is indirectly referenced from required .class files

Same isuue when i add the jar of official load.
http://www.couchbase.com/dl/releases/couchbase-lite/android/1.1.0/couchbase-lite-1.1.0-android_enterprise.zip

Anything to do with POM files here.Using eclipse as IDE.

Pls help.

Note: Wont see this issue in 1.0.4 build.

Also pls make Attachment,getContentURL api public for android.
Thanks
Nitz

**Comment by hideki** [comment]
Hi @NitzDKoder,
Could you please try to build with https://github.com/couchbase/couchbase-lite-android?

**Comment by hideki** [comment]
Hi @NitzDKoder, Can you solve the build issue?

**Comment by NitzDKoder** [comment]
Solved it was some issue with eclipse..both official and custom build jars are working now...
Pls comment on "Also pls make Attachment,getContentURL api public for android."

**Comment by hideki** [comment]
Hi @NitzDKoder,

Thank you for your comment.

I created new ticket for your request. #683

I will close this ticket.
