### ISSUE TITLE
Pulling attachments fail if document got a deleted revision in history

### ISSUE THREAD

**Issue by saubaer** [couchbase/couchbase-lite-java-core#677]
To reproduce:

create a pull replication to a couchdb (1.6.1 in my case)

1. insert a document containing an attachement (rev: 1-x)
2. pull replicate
3. delete the document (rev: 2-x)
4. pull replicate
5. insert the document again, containing the same attachment.(rev: 3-x)
6. pull replicate

The replication from step 6 will query couchdb with atts_since=2-x and couchdb will answer with an _attachment stub containing revpos: 1

CBL inserts the revision (3-x) into the revs table and tries to get the attachment from the parent sequence (2-x).
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L2967

This fails, since the deleted revision doesn't contain the attachment.

When I take a look at the attachments table of sqlite I find the attachment for rev 1-x is there.

I'm not sure what the best way would be to fix this.
Maybe an additional step to find the attachment by the given revpos, somewhere around here: https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L4471-L4478?

**Comment by hideki** [comment]
@saubaer Thank you very much for very clear bug report.

**Comment by saubaer** [comment]
@hideki it would have been a PR if the fix was obvious. :)
This problem is pretty serious to us. If you could outline how you want it to be solved, I can implement it and send a PR. Else I will have to bodge-fix it for our project.

**Comment by hideki** [comment]
Hi @saubaer, If you could send us PR, it is great.

FYI: We are working for removing attachments table. Your PR might not sustain long if issue is related with attachments table.
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_SQLiteStorage.m#L307-L345

**Comment by saubaer** [comment]
To reproduce the issue is actually a bit harder, when you just insert, delete, insert again the reported revpos is the revpos of the last insert. To reproduce you actually need to:

1. insert attachement
2. replicate to remoteDB
3. delete document on remoteDB
4. replicate the delete back to originalDB
5. insert the attachment to the originalDB again

Only then CouchDB reports the revpos of the first insert in the stub response.
In my case the "remoteDB" is a couchbase-lite and as described it gets confused when the document is replicated back after the attachment was inserted again after "5".

**Comment by hideki** [comment]
Hi @saubaer,

Sorry for late reply. We recently update database architecture to remove "attachments" table from SQLite database. For this change, we updated many attachment related codes, and it made your PR not merge-able. 

I tested if master branch code works well with error scenario you wrote in the ticket (https://github.com/couchbase/couchbase-lite-java-core/issues/677#issuecomment-122527475). But I could not reproduce it. Do you have a chance to test with latest master branch?

Thanks,
Hideki

**Comment by hideki** [comment]
Hi @saubaer,

I tried to reproduce this issue with 1.0.4, 1.1.0 and master branches, however I can not reproduce the issue with following your instruction 1 and 2.

I think there is hidden tricks to reproduce this issue. Is it possible to provide simple sample app or detailed instruction to reproduce this issue?

Thanks,
Hideki

**Comment by saubaer** [comment]
Hi @hideki 

Created a gist to reproduce the state of CouchDB. https://gist.github.com/saubaer/d2c09fcc83da3636b1c3
In my case DB2 is a continuous replicating CBL (push and pull) but this is not the cause of the problem.
It fails as soon it "sees" the 2nd insert, because the revpos is lower than the deleted revision.
I will also add a CouchDB Jira ticket, just to clarify if this is expected behavior of CouchDB.

regards,
Stefan

P.S.: Couldn't figure out how unit testing works, so postponed it and didn't find the time yet. :/

**Comment by hideki** [comment]
Hi @saubaer,
Thank you very much for providing script. Finally I could reproduce the issue.
