### ISSUE TITLE
NullPointerException sometimes occurs when instantiating Manager

### ISSUE THREAD

**Issue by popy** [couchbase/couchbase-lite-java-core#679]
Hi,

I have some crash reports from my app that indicates a NullPointerException from Manager class when instantiating it. The cause seems to be in method "upgradeOldDatabaseFiles" in the "for" loop declaration line. Investigating this, I saw that "File[] files = directory.listFiles(..." can in some cases return null, even if I don't know why in my case.

It occured on Sony XPeria SP (C5303) with Android 4.3, but it doesn't always crash.

**Comment by hideki** [comment]
Hi @popy,

Do you have any additional information for this issue? 

Thanks!

**Comment by zgramana** [comment]
@popy, we'll keep this one open for another week. Can you provide any other information?

**Comment by popy** [comment]
@hideki @zgramana 
Sorry but I don't have any additionnal info on this. I'm unable to replicate it myself, I can just see that my app sometimes crash on this for some users, without any explanation ...

**Comment by zgramana** [comment]
@popy Can you confirm that you have the following in your Android manifest?
```
uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE
```

**Comment by popy** [comment]
@zgramana I just checked and this permission is not in my manifest ! So it might be the reason of my NullPointerException. I'll confirm it when this fix will be tested with our users, but it won't be before some few weeks.

**Comment by hideki** [comment]
I will close this ticket. If `uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"` does  not work, please reopen this ticket.
