### ISSUE TITLE
Replicators should have independent cookie storage

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#694]
This is a parity feature with iOS. This is under assumption that getting replications with exact same parameters returns the same (internal) replicator object.

Issue:
https://github.com/couchbase/couchbase-lite-ios/issues/543

PR:
https://github.com/couchbase/couchbase-lite-ios/pull/609

**Comment by NitzDKoder** [comment]
@pasin  is this fix available in 1.2? or as hot fix in 1.2+?

**Comment by hideki** [comment]
Hi @NitzDKoder,
This could be in 1.3 release. I believe this will not be ready by next hot fix release.

**Comment by NitzDKoder** [comment]
@hideki any update on this fix?is it available?how complex is this? will try to contribute if you me the design details..

**Comment by hideki** [comment]
@NitzDKoder,
This ticket is still in the backlog queue. We have planed to implement by 1.3 release.
If you could implement this feature, easiest way is to port from CBL iOS.
Thanks,
hideki

**Comment by hideki** [comment]
Hi @NitzDKoder,
We move to OkHttp from HttpClient. CookieStore is tied with Http client library. So I recommend you to wait for a while.

**Comment by hideki** [comment]
For Cookie storage, needs to use java.net.CookieManager? Instead of using OkHttp CookieJar
http://stackoverflow.com/questions/24263921/how-to-implement-cookie-handling-on-android-using-okhttp

**Comment by NitzDKoder** [comment]
@hideki the above change is part of this?
https://github.com/couchbase/couchbase-lite-java-core/issues/708#issuecomment-222848657
pls confirm..

**Comment by hideki** [comment]
Independent cookie storage is not implemented yet.

**Comment by NitzDKoder** [comment]
@hideki is it not possible in 1.3 release?

**Comment by hideki** [comment]
@NitzDKoder, From current schedule, I can not implement this during 1.3 timeline. Sorry.

And also, I need to double check the spec with other platforms to be consistent. CBL iOS switch to cookie storage per database. <- I need to verify.
