### ISSUE TITLE
Add replicator support for remote dbs with varying URLs

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#695]
This is a parity feature with iOS.

Issue: https://github.com/couchbase/couchbase-lite-ios/issues/733
Commit: https://github.com/couchbase/couchbase-lite-ios/commit/2a75f83c1fd04410c9dde44a817f5e708492dd6c

**Comment by pasin** [comment]
In term of API, iOS implements this by using a custom property called, `remoteUUID` that users can set.
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLReplication.h#L93
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Replicator.h#L105-L112

CBL Android doesn't have the custom properties API. We could implement this as a normal get/set method for remoteUUID or we start to have a customProperties (with one property, `remoteUUID` supported). 

@zgramana How do you want the API for this feature implemented in CBL Android?

**Comment by zgramana** [comment]
Normal get/set please.
