### ISSUE TITLE
Support for CBLReplication.pendingDocumentIds

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#696]
This feature has been implemented in iOS and was recently fixed to return the result even when the replication is not running. It's returned the document ids that haven't been pushed to the server.

Issue: https://github.com/couchbase/couchbase-lite-ios/issues/807

**Comment by k10kumbhare** [comment]
Is there any specific date to fix this issue. Or can we increase the priority of this issue.I am stuck with the implementation of Purging the document when successfully synced with the Couchbase DB.

**Comment by hideki** [comment]
Hi @k10kumbhare, This issue should be fixed in this sprint (week).

**Comment by k10kumbhare** [comment]
Thanks hideki for this information. I will plan my implementation accordingly.
