### ISSUE TITLE
Inserting multiple attachments fails when push replication is active.

### ISSUE THREAD

**Issue by b-smets** [couchbase/couchbase-lite-java-core#699]
Using CouchbaseLite v1.1.0 on Android, we run into an error in Database#installAttachment 
when adding multiple reasonably sized attachments (big enough to trigger the "follows" behaviour)
in a database with a continuous push replication active.

(Correct me if I'm wrong: )
When adding an attachment to a document in Couchbase Lite, the data is written in background 
by a BlobStoreWriter. The Database keeps track of all pending attachments by means of a hashmap
mapping an MD5 Hash of the BlobStoreWriter to the actual writer.
When adding the attachment, a new revision of the document is also put in the database using
Database#putRevision() which in turn calls Database#getAttachmentFromRevision() 
(https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/Database.java#L4252).
This last method checks if the "follows" attribute of the attachment is set to "true", and
if this is the case, Database#installAttachment() is invoked which installs the actual
attachment from the list of pending attachments. In order to do this, the digest of the
attachInfo dictionary should be the MD5 hash identifying the BlobStoreWriter.

The problem, however, is that the pusher updates amongst others the attachments dictionary in the 
actual revision (RevisionInternal) when processing its inbox of changes to push.
More specifically in Database#getAttachmentsDictForSequenceWithContent(), the digest is 
updated to a SHA-1 hash (L3135) and for big attachments, the follows attribute is set to
true (L3167).

Here is the catch: The revision being updated by the pusher is the same java object as the 
one used in the document used to create the attachments. The document is cached in the 
database document cache so requesting the document again from the database does nothing
to fix this. The only workaround I have found is to clear the docCache in the database
but this is an internal method and seems like a bad idea in its own.

So basically what happens:
- Big attachment is inserted fine.
- Pusher runs and updates the big attachments' digest and follows attribute
- Next attachment is inserted but installAttachments cannot find the now SHA-1 hash in the list
of pending attachments.

Reproducible case:

- Create a database with a continuous push replication to some remote Syncgateway instance.
- Add a large attachment (let's say at least 1 MB) on some document in the database.
- Wait for the pusher to kick in and finish processing its inbox.
- Add another attachment on the same document (I don't think size matters this time).
Results in this stack:
```
com.couchbase.lite.CouchbaseLiteException
at com.couchbase.lite.Database.installAttachment(Database.java:2948)
at com.couchbase.lite.Database.getAttachmentsFromRevision(Database.java:4285)
at com.couchbase.lite.Database.putRevision(Database.java:4063)
at com.couchbase.lite.Database.putRevision(Database.java:3923)
at com.couchbase.lite.Document.putProperties(Document.java:420)
at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:107)
at com.couchbase.lite.Document.update(Document.java:281)
```

**Comment by hideki** [comment]
Test codes to reproduce this issue. https://github.com/hideki/couchbase-lite/tree/master/test/Issue699

**Comment by hideki** [comment]
I tested this problem with latest master branch of couchbase-lite-android and couchbase-lite-java-core. Problem is no longer reproducible. I believe that migration to new SQLite database architecture could solve this problem.

To confirm the fix, please following codes. This app includes couchbase libraries as submodule.
https://github.com/hideki/couchbase-lite/tree/issue_699_master_20151116/test/Issue699

**Comment by orenyodfat** [comment]
When v1.2.0 will be released?
Can I found a patch for this issue somewhere?

**Comment by hideki** [comment]
@orenyodfat 

> When v1.2.0 will be released?

Currently v1.2 release is scheduled in middle of January.

> Can I found a patch for this issue somewhere?

Can you compile from source code by yourself? https://github.com/couchbase/couchbase-lite-android
