### ISSUE TITLE
How to link my own.pem in Android CB lite.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#705]
Below is the implementation for to link my own.pem in Android CB lite for SSL.

Logger.d(TAG, "-------- initializeCbSSL start---------");
AssetManager am = OwnApplication.applicationContext.getAssets();
	    InputStream is = am.open("own.pem");
	    
	    // Load CAs from an InputStream 
	    CertificateFactory cf = CertificateFactory.getInstance("X.509");
	    InputStream caInput = new BufferedInputStream(is);
	    Certificate certificate; 
	    try { 
	        certificate = cf.generateCertificate(caInput);
	    } finally { 
	        caInput.close();
	    } 
	    // Create a KeyStore containing our trusted CAs 
	    String keyStoreType = KeyStore.getDefaultType();
	    KeyStore keyStore = KeyStore.getInstance(keyStoreType);
	    keyStore.load(null, null); 
	    keyStore.setCertificateEntry("own", certificate); 
	    
	    SSLSocketFactory socketFactory = new CouchBaseSSLSocketFactory(keyStore); 
	    //CBLHttpClientFactory.INSTANCE.setSSLSocketFactory(sf); 
	    CouchbaseLiteHttpClientFactory couchbaseLiteHttpClientFactory = new CouchbaseLiteHttpClientFactory(CouchBaseLiteManager.getInstance().getCBDatabase().getPersistentCookieStore());
	    couchbaseLiteHttpClientFactory.setSSLSocketFactory(socketFactory);
	    Manager.getSharedInstance().setDefaultHttpClientFactory(couchbaseLiteHttpClientFactory);

	
	public CouchBaseSSLSocketFactory(KeyStore keyStore) throws KeyManagementException, UnrecoverableKeyException, NoSuchAlgorithmException, KeyStoreException {
		
		super(keyStore);
		
		TrustManager trustManager = new X509TrustManager() {

			@Override
			public void checkClientTrusted(X509Certificate[] chain,
					String authType) throws CertificateException {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void checkServerTrusted(X509Certificate[] chain,
					String authType) throws CertificateException {
				// TODO Auto-generated method stub
				
			}

			@Override
			public X509Certificate[] getAcceptedIssuers() {
				// TODO Auto-generated method stub
				return null;
			}
			
		}; 

		 SSLContext context = SSLContext.getInstance("TLS");
		 context.init(null,new TrustManager[] { trustManager },null);
	}
 I get java.security.cert.CertificateException :

com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

Anyone encountered this? using own bundled certificate in android CB lite environment. Am i doing all ok here pls help.

Thanks
NitZ

**Comment by hideki** [comment]
Hi @NandishAndDev,

it seems certificate file formatting issue. see following link.

http://stackoverflow.com/questions/21138485/certificateexception-opensslx509certificatefactoryparsingexception

**Comment by NitzDKoder** [comment]
@hideki yeah the cert content was not liked by the api.. now its resloved and cblite is able to do https connections..
