### ISSUE TITLE
Apache HTTP Client Removal/Deprecated in Android M.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#708]
Hi,
We know that in android m the Apache HTTP Client is removed/deprecated.
Workaround is to have this in the gradle.

 
"To continue using the Apache HTTP APIs, you must first declare the following compile-time dependency in your build.gradle file:"
android {
    useLibrary 'org.apache.http.legacy'
}
https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

What are the insights the Couchbase team taken for this change from android team.I think "apache.http.client" widely in used "couchbase-lite-java-core".

How will be the future of coucbaselite if its removed natively completely? Use as jar is option and will it work all ok?

http://developer.android.com/sdk/api_diff/23/changes.html

https://github.com/couchbase/couchbase-lite-java-core/search?utf8=%E2%9C%93&q=org.apache.http.client&type=Code

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder ,
Thank you very much for your post.
We plan to migrate from HttpClient to HttpURLConnection or alternative. However, in short term, we need to keep using HttpClient.
Thanks!
Hideki

**Comment by tikimcfee** [comment]
Hey there guys, just wanted to put a +1 on this issue. Our application has a number of requirements in mean if java-lite-core doesn't move to an alternative, we can't feasibly upgrade to build with the latest tools.

**Comment by RicardoBelchior** [comment]
+1

**Comment by anisart** [comment]
+1

**Comment by ddash1** [comment]
+1

**Comment by ddash1** [comment]
Any update on this plan yet?

**Comment by lulicheng** [comment]
牛逼

**Comment by hideki** [comment]
As short term solution, we might includes HttpClient with different package name in Couchbase Lite. For long term solution, we will eliminate HttpClient.

**Comment by zgramana** [comment]
We're going to do this, but we just can't get it in 1.2 given there's a workaround at the moment.. Definitely the next release it will get high priority.

**Comment by vitas** [comment]
+1, it will reduce size of the app too

**Comment by reisub** [comment]
I think you should use OkHttp - it's a fast, modern, standards compliant http client and it has a much nicer API than HttpURLConnection.
The only downside is that it adds 2k new methods to the apk for android apps. Alternatively, you could use some kind of wrapper like https://github.com/reisub/HttPizza (disclaimer: I wrote it).

**Comment by zgramana** [comment]
This sprint: putting together the steps for the transition.

**Comment by hideki** [comment]
Libraries:
- [OkHttp](http://square.github.io/okhttp/)
- [HttpURLConnection](http://developer.android.com/intl/es/reference/java/net/HttpURLConnection.html)

Pros/Cons:
- Both Android and Java provides java.net.HttpURLConnection by Java runtime. By using HttpURLConnection, final application file size is smaller than depending OkHttp. 
- It seems OkHttp is easier to use than HttpURLConnection.
- OkHttp: We could use always latest library of OkHttp for all version of Android OSs.

Notes:
- Android's implementation of HttpURLConnection uses OkHttp internally.

Files imports HttpClient:
- BulkDownloader.java
- ChangeTracker.java
- ChangeTrackerClient.java
- PullerInternal.java
- CouchbaseLiteHttpClientFactory.java
- HttpClientFactory.java
- RemoteMultipartDownloaderRequest.java
- RemoteMultipartRequest.java
- RemoteRequest.java

**Comment by reisub** [comment]
One more pro of OkHttp is that you get SPDY / HTTP2 support on all android versions. HttpURLConnection does not have that support AFAIK and if it's added at some point it won't be backward compatible.

**Comment by NitzDKoder** [comment]
@hideki  any plans on web sockets?
https://github.com/couchbase/sync_gateway/wiki/WebSocket-Based-Changes-Feed

**Comment by hideki** [comment]
@reisub, 
Thank you very much for your input!

@NandishAndDev,
Ticket for WebSocket: https://github.com/couchbase/couchbase-lite-java-core/issues/493 As CBL iOS and .NET support WebSocket already, so we'd like to support WebSocket as soon as possible. It depends on priority.

**Comment by NitzDKoder** [comment]
@hideki available to try and test? pls confirm..

**Comment by hideki** [comment]
Hi @NitzDKoder,
With Jenkins's environment issue, build is not available yet.
If you can compile from source code, please clone from master branch of couchbase-lite-android and its submodules.

**Comment by hideki** [comment]
@NitzDKoder,
If you have a chance, could you please try 0.0.0-720 which was built from master branch?
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-720/

**Comment by jehy** [comment]
Guys, there is nothing bad with using Apache's modules. Google just made a big mess of it because they failed to make successful fork. As you can see on the [official page][1] of Apache components, there is a fresh 4.5 version, compatible with all of Android versions.

You simply can add dependency from maven (or download release from [github][2]):

`dependencies {
  compile "cz.msebera.android:httpclient:4.4.1.2"
}`

and then replace `org.apache.http` with `cz.msebera.android.httpclient`, so your imports will look like

    import cz.msebera.android.httpclient.Header;
    import cz.msebera.android.httpclient.HttpHost;
    import cz.msebera.android.httpclient.HttpResponse;

Yeah, you can continue using apache libraries without hours of rewriting of working code!

By the way, I tried alternatives like URLConnection - those are not even close to apache's power and simplicity.

  [1]: https://hc.apache.org/httpcomponents-client-4.5.x/android-port.html
  [2]: https://github.com/smarek/httpclient-android

**Comment by hideki** [comment]
Hi @jehy,

Thank you very much for your inputs. We replaced HttpClient with [OkHttp](http://square.github.io/okhttp/). If OkHttp solution does not work, we will consider to use non-google version of HttpClient.

Thanks!

**Comment by NitzDKoder** [comment]
@hideki 
How stable is Okhttp based CBL?
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-738/

Used above build and i see puller issue..yet to analyse logs..

Whats your UT results on Okhttp..??

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

OkHttp version can pass our Unit Test and also our functional test. But it is not widely tested because new version of CBL that includes OkHttp is not yet released. If you observe any replication issue, please file the ticket.

Thanks!

**Comment by NitzDKoder** [comment]
@hideki 
pls point me to stable Source of CBL+OKHTTP+ForestDB? Whats the good way to merge the src(CBL java core+OKHTTP+ForestDB+Android+Listener+Javascript etc) compile and debug myself?

**Comment by hideki** [comment]
To debug CBL library from App, I usually set CBL libraries as a submodule.
Please refer https://github.com/couchbaselabs/GrocerySync-Android/tree/dev/master
Thanks!

**Comment by NitzDKoder** [comment]
@hideki pls paste the build.gradle which you are using in your IDE?

**Comment by hideki** [comment]
Sorry, repo of GrocerySync does not includes submodule solution.

Followings are example of LiteServ with submodule solution.

https://github.com/couchbase/couchbase-lite-android-liteserv/blob/dev/submodules/couchbase-lite-android-liteserv/build.gradle

https://github.com/couchbase/couchbase-lite-android-liteserv/blob/dev/submodules/settings.gradle

**Comment by NitzDKoder** [comment]
@hideki 

Okhttp moved to 3.4.2

http://square.github.io/okhttp/

CBL is with 3.3.1..Hows is the plan of okhttp and CBL integration.. .Pls confirm..

https://github.com/couchbase/couchbase-lite-java-core/blob/1.3.1/build.gradle#L28


Reason for ask is we have changes in SSL module of Okhttp..

https://github.com/couchbase/couchbase-lite-java-core/issues/1278

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

I created the [ticket](https://github.com/couchbase/couchbase-lite-java-core/issues/1520) for OkHttp migration.

Thanks,
Hideki
