### ISSUE TITLE
401 status from server not being propagated to CBLReplication.lastError

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#723]
iOS: https://github.com/couchbase/couchbase-lite-ios/issues/900

**Comment by hideki** [comment]
from @anisart 

https://github.com/couchbase/couchbase-lite-android/issues/703#issue-117791470

Hi all,

I use couchbase-lite-android 1.1.0 via gradle and Sync Gateway/1.1.0(28;86f028c). Solution flom #540 works only for push replucation.

For example, I create user "foo" with password "bar" and login with this in ToDoLite sample app. I create new task in list. After sync I change user password via REST API and change task in Sync Gateway /_admin. I see many ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@42b1659: Change tracker got error 401 in logcat but unautorized callback is not called. It's called only if I make some changes in app.

**Comment by swaheed2** [comment]
Is this also fixed in the rest api for _changes? I am unable to catch 401 on the mobile side.

**Comment by hideki** [comment]
@swaheed2,
If you have this problem with REST API, could you please file new ticket with detailed information.
Thanks!

**Comment by swaheed2** [comment]
I filed it here https://github.com/couchbase/couchbase-lite-java-core/issues/1334

**Comment by hideki** [comment]
@swaheed2 
Thank you.
