### ISSUE TITLE
Java doesn't support generating 256 bits key

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#748]
Standard Java doesn't support PKCS7Padding algorithm and advises to use PKCS5Padding instead. Another issue is that by default standard Java supports up-to 128 bit keys not 256 bit keys. To use 256 bit keys, the new JCE Unlimited Strength Jurisdiction Policy is required to be installed at a certain JRE/lib/security location.

**Comment by pasin** [comment]
From @snej , "128-bit AES keys are insufficient for good security (or FIPS compliance.)" So we may consider using 128-bit on standard java.

**Comment by zgramana** [comment]
Need to throw an exception if the JCEUS JP cannot be found, and a short summary of to how to resolve the problem.
