### ISSUE TITLE
Long wait time in RounterTests.testCallContinuousReplicateTwice

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#751]
I have noticed that RounterTests.testCallContinuousReplicateTwice has twice 20 seconds (total = 40 seconds) waiting for replicator to become idle inside the code. We need to review if we could bring that waiting time down.

**Comment by hideki** [comment]
@pasin
This issue is fixed by [PR](https://github.com/couchbase/couchbase-lite-android/pull/668) .
Please confirm.
