### ISSUE TITLE
Reimplement ForestDBStore to use CBForest C API and Make all unit tests pass against FDB storage engine

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#762]

**Comment by hideki** [comment]
TODOs
- [ ] Reimplement ForestDBStore to use C API binding instead of CBForest C++ binding
- [ ] Fix all issues that caused by C API binding till all tests pass

**Comment by hideki** [comment]
Implementation Tasks
ForestDBStore
- [ ] databaseExists
- [ ] open
- [ ] close
- [ ] setDelegate
- [ ] getDelegate
- [ ] setMaxRevTreeDepth
- [ ] getMaxRevTreeDepth
- [ ] setInfo
- [ ] getInfo
- [ ] getDocumentCount
- [ ] getLastSequence
- [ ] inTransaction
- [ ] compact
- [ ] runInTransaction
- [ ] getDocument
- [ ] loadRevisionBody
- [ ] getParentRevision
- [ ] getRevisionHistory
- [ ] getAllRevisions
- [ ] getPossibleAncestorRevisionIDs
- [ ] findCommonAncestor
- [ ] findMissingRevisions
- [ ] findAllAttachmentKeys
- [ ] getAllDocs
- [ ] changesSince
- [ ] add
- [ ] forceInsert
- [ ] purgeRevisions
- [ ] getViewStorage
- [ ] getAllViewNames
- [ ] getLocalDocument
- [ ] putLocalRevision

ForestDBViewStore
- [ ] getName
- [ ] getDelegate
- [ ] setDelegate
- [ ] close
- [ ] deleteIndex
- [ ] deleteView
- [ ] setVersion
- [ ] getTotalRows
- [ ] getLastSequenceIndexed
- [ ] getLastSequenceChangedAt
- [ ] updateIndex
- [ ] regularQuery
- [ ] reducedQuery
- [ ] dump
- [ ] setCollation

**Comment by hideki** [comment]
Tests need to pass with new ForestDB Store

- [ ] ApiTest (Needs to implment View first)
- [ ] AttachmentsTest (testGetAttachmentBodyUsingPrefetch needs View)
- [ ] AuthTest
- [ ] Base64Test
- [ ] BlobstoreWriterTest
- [ ] CacheTest
- [ ] ChangesTest
- [ ] CollationTest
- [ ] CRUDOperationsTest
- [ ] DatabaseTest
- [ ] DocumentTest
- [ ] LocalDocsTest
- [ ] ManagerTest (failings are replaceXXX)
- [ ] MiscTest
- [ ] MultipartReaderTest
- [ ] RevisionsTest
- [ ] RevTreeTest
- [ ] RouterTest
- [ ] SequenceMapTest
- [ ] SimpleCRUDTest
- [ ] ValidationsTest
- [ ] ViewsTest
- [ ] replicator.PushReplicationTest
- [ ] replicator.ReplicationTest ()
- [ ] replicator.Replication2Test
- [ ] replicator.BulkDownloaderTest
- [ ] replicator.ChangeTrackerTest
- [ ] supports.*
- [ ] util.*
- [ ] store.SQLiteStoreTest
