### ISSUE TITLE
Experiment with SQLCipher Performance

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#786]
Reivew multiple SQLCipher compiler options and encryption libraries.

**Comment by pasin** [comment]
## Nexus 4 (Android 5.1.1)

Measuring times taken in MS.

#### Test1_CreateDocs

| num docs | doc size | libTomCrypt | libCrypto |
| ------------- | ------------- | ------------- | ------------- |
|100|1K|427|406|
|100|10K|646|593|
|100|100K|2662|2418|

#### Test3_ReadDocs

| num docs | doc size | libTomCrypt | libCrypto |
| ------------- | ------------- | ------------- | ------------- |
|100|1K|178 |172|
|100|10K|306|285|
|100|100K|1399|1186|

**Comment by pasin** [comment]
Assigned to @zgramana for reviewing.

**Comment by pasin** [comment]
Note: I could find an instruction to enable NEON on OpenSSL website / wiki. I found the compile options as above from http://processors.wiki.ti.com/index.php/Cortex-A8.

**Comment by pasin** [comment]
Look like I might understand it wrong that Nexus 4 supports NEON. I will test NEON on Nexus 6 when I have a chance.

**Comment by zgramana** [comment]
Fantastic!

**Comment by pasin** [comment]
How Android NDK enables NEON :

```
-mfpu=neon -DHAVE_NEON=1 -I/Users/pasin/Library/Android/sdk/ndk-bundle/sources//android/cpufeatures
```

The cpufeatures is proprietary to Android and I couldn't find much information about HAVE_NEON. Note that there is no `mcpu` option set.

**Comment by pasin** [comment]
Another post about enabling NEON: https://community.arm.com/thread/4691

**Comment by pasin** [comment]
Close this ticket by creating a new ticket specifically for NEON.
