### ISSUE TITLE
Couchbase LITE Replication design(when network down and up / when Replication is stopped and started)?

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#790]
Hi Folks,

Trying to understand this use case behaviour in Couchbase Lite and SGW.

1)Insert a big doci.e 10 mb, replication is ongoing and 5b is reached SGW.
2)Pull a big doci.e 10 mb, replication is ongoing and 5b is reached CBLite.
3)Now networks goes down and comes up or.
4)Replication is stopped and restarted.

On # 3 and # 4 what does replications module do?Does it

" Before it starts the transfer/Download does it do a full hash check to find out which parts of the file it needs to get/put.Hence not syncing available data?

Note:yet to analyse CBL logs or code work through.

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,
Current version of Couchbase Lite Android/Java does not support chunk (partial) download. It will retry from beginning.

**Comment by NitzDKoder** [comment]
@hideki thanks..any fix planned?

**Comment by zgramana** [comment]
@nitzdkoder we will have some ways of addressing these kinds of scenarios in future releases. Not sure if it will make it into 1.3 though.
