### ISSUE TITLE
Replication Problems with Ionic

### ISSUE THREAD

**Issue by lucapale** [couchbase/couchbase-lite-java-core#794]
Hi,
I have a Ionic/Angular app that is using Facebook for the login.
The replication works fine with the iOS version of the app, but when I run it on Android the replication works only from remote to the server, and not the opposite.
I have noticed that Sync_Gateway logs do not show _facebook POST, like it happens when I run the same app on iOS.
There should be a bug in the requests that are sent to the server.
I can send all code if necessary.

**Comment by hideki** [comment]
@nraboy, Do you have time to look into this issue?

**Comment by nraboy** [comment]
What do your device logs say for Android?  With the application installed and running on your device or simulator you can run the following in your Terminal:

```
adb logcat
```

It will be messy, but it should put us on the right path.

**Comment by lucapale** [comment]
I have made a couple of weeks ago for James a separate app to replicate the issue. You can find the source codes here:
https://github.com/lucapale/couchbaseIonicLogin
You can run it with iOS and Android simulators and you will see the differences.

**Comment by nraboy** [comment]
Let me pull @jamiltz into this as well.  We'll take a look at what you've done and get back to you.

Best,

**Comment by lucapale** [comment]
Hi @nraboy / @jamiltz,
any new for this issue?
Thanks

**Comment by jamiltz** [comment]
I'll have a look tomorrow and try to provide easy steps to reproduce.

**Comment by jamiltz** [comment]
Here are two screenshots of replications with facebook login for iOS and Android.
iOS
<img width="1436" alt="1444221601" src="https://cloud.githubusercontent.com/assets/2589337/10791548/c799323c-7d80-11e5-8d64-4bbe671e9ce0.png">
Android
<img width="1436" alt="1444221685" src="https://cloud.githubusercontent.com/assets/2589337/10791557/d1ffbec6-7d80-11e5-8f14-d8f792ea4cf2.png">

So it looks like Android isn't calling /_facebook after /_session on the remote db. The [checkSession](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java#L358) method might be relevant here. I haven't looked at the source on iOS. It seems to be a feature that's available on iOS only (@hideki can you confirm?).

There is a workaround that would be to use an app server to create a user via the admin rest api and replicate as that user (I think facebook login was added initially to make it simpler but it doesn't scale as we'd have to add every oauth provider out there, the app server approach should be used if possible). Here's a [blog post](http://blog.couchbase.com/2015/october/adding-google-sign-in-with-node.js-to-a-couchbase-mobile-application) that explains how to do it for Google Sign In.

**Comment by hideki** [comment]
@jamiltz  Thank you very much for investigating issue.

CBL Java/Android support [FacebookAuthorizer](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/auth/FacebookAuthorizer.java). However ToDoLite-Android does not use FacebookAuthorizer (https://github.com/couchbaselabs/ToDoLite-Android/search?utf8=%E2%9C%93&q=FacebookAuthorizer&type=Code). It could be reason ToDoLite-Android does not call `/<db>/_facebbok`.

**Comment by pasin** [comment]
ToDoLite-Android is using FacebookAuthenticator.

https://github.com/couchbaselabs/ToDoLite-Android/blob/bcd87faa4c68a7cee075468b08da55c8041830a7/ToDoLite/src/main/java/com/couchbase/todolite/Synchronize.java#L55-L63

I'm not sure if this issue is related to ToDoLite-Android though.

**Comment by pasin** [comment]
@hideki FacebookAuthorizer is deprecated. Facebook Authentication is based on TokenAuthenticator.

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/auth/AuthenticatorFactory.java#L26-L30

**Comment by lucapale** [comment]
Hi everybody and thank you for taking the time to follow this issue.
My previous release of the app, which is also published on the Android store, was using the original code of ToDo-Lite for phonegap (https://github.com/couchbaselabs/TodoLite-PhoneGap), with some implementation for Ionic/Angular. This code, together with the previous version of the phonegap plugin (1.0.4) was replicating correctly the database both in Android and in iOS.
In my last release I have used the code proposed in the Ionic/Couchbase tutorial, with the additional implementation of Facebook login (this is what you can find in my GitHub repo). This last version has problems with Android, but not with iOS.
I suppose there was some "trick" in the original code of ToDoLite-Phonegap, that allowed the replication to work correctly. Unfortunately I was not able to find this "trick" (if any). Or maybe there has been some modification between the previous plugin and the actual one that cause the error?
In any case I definitely need to have Facebook login in my application, because any other work-around would not be feasible.
Let me know if I can help in any way.
Cheers,
Luca

**Comment by jamiltz** [comment]
My bad, looked into it again and it appears to be working fine. @lucapale you can use the following to test it out. Let us know if this works for you.

#### Sync Gateway config file
```js
{
  "log": ["*"],
  "facebook": {"register": true},
  "databases": {
    "cityapp": {
      "server": "walrus:",
      "users": {
        "GUEST": {"disabled": true}
      },
      "sync": 
  	`
      function(doc, oldDoc) {
        if (doc.user_type == "facebook") {
          channel(doc.city);
          access(doc.user_id, doc.city);
        }
      }
    `
    }
  }
}
```

#### Delete database
curl -X "DELETE" "http://localhost:5984/cblite-test" \
	-H "Content-Type: application/json"

#### Create database
curl -X "PUT" "http://localhost:5984/cblite-test"

#### Register facebook user (replace with your access token and email)
curl -X "POST" "http://localhost:5984/_facebook_token" \
	-H "Content-Type: application/json" \
	-d "{\"access_token\":\"CAAHIIPKDh6....5J4U9eiIl\",\"email\":\"james.nocentini@couchbase.com\",\"remote_url\":\"http://localhost:4984/cityapp\"}"

#### Add documents (replace with your user's Facebook ID)
curl -X "POST" "http://localhost:5984/cblite-test/_bulk_docs" \
	-H "Content-Type: application/json" \
	-d "{\"docs\":[{\"city\":\"new-york\",\"user_id\":\"chef123\",\"user_type\":\"basic_auth\"},{\"city\":\"london\",\"user_id\":\"120318268328551\",\"user_type\":\"facebook\"},{\"city\":\"san-francisco\",\"user_id\":\"120318268328551\",\"user_type\":\"facebook\"}]}"

#### Push replication (replace with access token and facebook email)
curl -X "POST" "http://localhost:5984/_replicate" \
	-H "Content-Type: application/json" \
	-d "{\"target\":{\"url\":\"http://localhost:4984/cityapp\",\"auth\":{\"facebook\":{\"email\":\"james.nocentini@couchbase.com\"}}},\"source\":\"cblite-test\"}"


--> Check in the admin UI for the pushed documents (http://localhost:4985/_admin/)

#### Delete the local database
curl -X "DELETE" "http://localhost:5984/cblite-test"

#### Create the local database
curl -X "PUT" "http://localhost:5984/cblite-test"

#### Register FB user (replace with your email and access token)
curl -X "POST" "http://localhost:5984/_facebook_token" \
	-H "Content-Type: application/json" \
	-d "{\"access_token\":\"CAAHIIP...I95PSb5J4U9eiIl\",\"email\":\"james.nocentini@couchbase.com\",\"remote_url\":\"http://localhost:4984/cityapp\"}"


#### Pull replication
curl -X "POST" "http://localhost:5984/_replicate" \
	-H "Content-Type: application/json" \
	-d "{\"source\":{\"url\":\"http://localhost:4984/cityapp\",\"auth\":{\"facebook\":{\"email\":\"james.nocentini@couchbase.com\"}}},\"target\":\"cblite-test\"}"

#### Get documents
curl -X "GET" "http://localhost:5984/cblite-test/_all_docs" \
	-H "Content-Type: application/json" \
	-d "{\"source\":{\"url\":\"http://localhost:4984/cityapp\",\"auth\":{\"facebook\":{\"email\":\"james.nocentini@couchbase.com\"}}},\"target\":\"db\"}"


--> The response should contain only 2 documents out of the 3 that you pushed earlier because this user only has access to two channels.

**Comment by lucapale** [comment]
I am pretty sure this would work, because it's what I already do with my app and works with iOS.
But I don't get how this should affect the Android problem that I have. Can you elaborate better?
Thanks

**Comment by jamiltz** [comment]
The requests above are pushing documents and then via the sync function pulling them again. Because the user authenticated, all docs are pushed and mapped to their channel and the pull replication only retrieves the channels the user has access to. So it's showing that push replication with authentication is working as expected. Wasn't that the issue you were describing?

**Comment by jamiltz** [comment]
Also, I ran those requests against a CBLite db on Android with http://github.com/couchbase/couchbase-lite-android-liteserv on branch release/1.1.0

**Comment by lucapale** [comment]
Sorry, but the problem is in the authentication/replication only when the Ionic app is deployed with Android. The same app deployed with iOS replicates correctly.
I need the app to run in the same way, using Couchbase-phonegap plugin and deploying on both Android and iOS.

**Comment by jamiltz** [comment]
I had a chance to do some pairing with @lucapale and worked around the issue by adding the db name in the `remote_url` field when registering the facebook token. Filed an issue with the steps to reproduce in https://github.com/couchbase/couchbase-lite-java-core/issues/803.

**Comment by hideki** [comment]
We track this issue by https://github.com/couchbase/couchbase-lite-java-core/issues/803
