### ISSUE TITLE
Build space-optimized libcrypto

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#795]

**Comment by pasin** [comment]
I have created a new repo: https://github.com/couchbaselabs/couchbase-lite-libcrypto.

Current status:

All of the binaries are currently working. However there are two issues:
1. On OSX, make depend doesn't work and get skipped. I would like to spend a bit more time to see if this can be resolved or not.
2. On Windows, I saw rekey test failed so I will need to verify if it's related to the binary or not.

**Comment by pasin** [comment]
Regarding to the OSX make depend issue, `make depend` shows warning messages as below:

```
$ make depend
making depend in crypto...
makedepend: warning:  cannot open "x86_64"
makedepend: warning:  cryptlib.c (reading cryptlib.h, line 62): cannot find include file "stdlib.h"
    not in ./stdlib.h
    not in ../stdlib.h
    not in ../include/stdlib.h
    not in /usr/include/stdlib.h
makedepend: warning:  cryptlib.c (reading cryptlib.h, line 63): cannot find include file "string.h"
    not in ./string.h
    not in ../string.h
    not in ../include/string.h
    not in /usr/include/string.h
makedepend: warning:  cryptlib.c (reading ../e_os.h, line 468): cannot find include file "unistd.h"
    not in ./unistd.h
    not in ../unistd.h
    not in ../include/unistd.h
    not in /usr/include/unistd.h
makedepend: warning:  cryptlib.c (reading ../e_os.h, line 473): cannot find include file "sys/types.h"
    not in ./sys/types.h
    not in ../sys/types.h
    not in ../include/sys/types.h
    not in /usr/include/sys/types.h
makedepend: warning:  cryptlib.c (reading ../include/openssl/crypto.h, line 120): cannot find include file "stdlib.h"
    not in ./stdlib.h
    not in ../stdlib.h
    not in ../include/stdlib.h
    not in /usr/include/stdlib.h
makedepend: warning:  cryptlib.c (reading ../include/openssl/crypto.h, line 125): cannot find include file "stdio.h"
    not in ./stdio.h
    not in ../stdio.h
    not in ../include/stdio.h
    not in /usr/include/stdio.h
...
```

From homebrew github issue [#28677](https://github.com/Homebrew/homebrew/issues/28677) that shows the same issue, the issue was closed as the warning messages are harmless. As the binary is built and useable, I will ignore the warning messages.

**Comment by pasin** [comment]
For the rekey test failure, it happens to be a unit test error that doesn't close a FileInputStream. I will issue a fix for that.

**Comment by pasin** [comment]
Let now make header for each platform as the global one works just fine.
