### ISSUE TITLE
Run Android functional test with using ForestDB

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#796]

**Comment by andreibaranouski** [comment]
https://github.com/couchbase/couchbase-lite-android-liteserv/issues/29 blocker for me

**Comment by hideki** [comment]
https://github.com/couchbase/couchbase-lite-android-liteserv/issues/29 was closed.
Could you please run functional test with ForestDB?

**Comment by hideki** [comment]
Note to self:
repo: https://github.com/couchbaselabs/sync-gateway-tests
script: https://gist.github.com/sethrosetter/8f3e439652341d63361e#file-gistfile1-txt-L138-L175

**Comment by hideki** [comment]
Android Functional Test on Jenkins: http://qa.sc.couchbase.com/view/mobile/job/sync-gateway-mobile-functional-tests-android-walrus/
