### ISSUE TITLE
/db/_changes with filter=_view parameter does not work as expected

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#799]
Need to fix this in Router.java
See http://docs.couchdb.org/en/1.6.1/api/database/changes.html#view

Also following issue should be fixed
https://github.com/couchbase/couchbase-lite-java-javascript/issues/11

**Comment by zgramana** [comment]
Closing this out as it's more important to implement canonical filter functions for the `_changes` feed. That will tracked in https://github.com/couchbase/couchbase-lite-java-javascript/issues/11.
