### ISSUE TITLE
Replace JNI-based JSON collation with ICUC

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#801]
Currently TDCollator will only handle ASCII chars on the C side, and delegates to Java for all other chars. This is very slow.

Instead, replace the custom C + JNI/Java compare with the official Unicode UCIC library to handle all collation comparisons: http://userguide.icu-project.org/collation/api

--- NOTE from @hideki
Replace the custom C + JNI/Java with custom C + ICU4C

**Comment by zgramana** [comment]
Ref https://github.com/couchbase/couchbase-lite-java-native/blob/master/src/main/c/sqlite_json_collator.c#L295

**Comment by pasin** [comment]
We can look at here as an example as well.
https://github.com/sqlcipher/android-database-sqlcipher/blob/master/external/Android.mk

**Comment by hideki** [comment]
Test Result of updateIndex Performance Improvement by ICU4C

Test tool is Test12_IndexView
Number of records: 10000

| DEVICE | Java Collator | ICU4C | Improvement |
| --- | --- | --- | --- |
| NEXUS 9 | 4381.0ms | 3563.0ms | +22.96% |
| NEXUS 6 | 11787.66ms | 8032.0ms  | +46.76% |
| NEXUS 4 | 16911ms | 11297ms  | +49.69% |


Raw result
```
formula to calculate improvement => (old value - new value)/new value

Nexus 9

Use Java TextCollator through JNI
IndexViewPerformance:testViewIndexPerformance,4763,10000
IndexViewPerformance:testViewIndexPerformance,4233,10000
IndexViewPerformance:testViewIndexPerformance,4147,10000

AVE 4381.0

Use ICU4C
IndexViewPerformance:testViewIndexPerformance,3809,10000
IndexViewPerformance:testViewIndexPerformance,3450,10000
IndexViewPerformance:testViewIndexPerformance,3430,10000

AVE 3563.0

+22.96%

Nexus 6

Use Java TextCollator through JNI
IndexViewPerformance:testViewIndexPerformance,11868,10000
IndexViewPerformance:testViewIndexPerformance,11721,10000
IndexViewPerformance:testViewIndexPerformance,11774,10000

AVE 11787.66

Use ICU4C
IndexViewPerformance:testViewIndexPerformance,8121,10000
IndexViewPerformance:testViewIndexPerformance,8062,10000
IndexViewPerformance:testViewIndexPerformance,7913,10000

AVE 8032.0

+46.76%

Nexus 4

Use Java TextCollator through JNI
IndexViewPerformance:testViewIndexPerformance,17068,10000
IndexViewPerformance:testViewIndexPerformance,16955,10000
IndexViewPerformance:testViewIndexPerformance,16710,10000

AVE: 16911ms

IndexViewPerformance:testViewIndexPerformance,11379,10000
IndexViewPerformance:testViewIndexPerformance,11251,10000
IndexViewPerformance:testViewIndexPerformance,11262,10000

AVE: 11297ms

+49.69
```

**Comment by hideki** [comment]
PR for this ticket: https://github.com/couchbase/couchbase-lite-android/pull/691

**Comment by hideki** [comment]
### Final performance result of updateIndex() performance to index 10K records on Nexus 6

| DEVICE | Java Collator | ICU4C | Improvement |
| --- | --- | --- | --- |
| NEXUS 6 | 8100ms | 5494 ms  | +47.43% |

```
ICU4C: IndexViewPerformance: PerformanceStats: 5494 msec (10000)
JAVA:  IndexViewPerformance: PerformanceStats: 8100 msec (10000)
```
