### ISSUE TITLE
HttpMime library source code integration in couchbase breaks existing code

### ISSUE THREAD

**Issue by popy** [couchbase/couchbase-lite-java-core#81]
The httpmime library sources are included in the couchbase library, but have been modified (https://github.com/couchbase/couchbase-lite-java-core/commit/1e68229e6ad5bcde17b72059eeae3bfe5ad7d035). The result is my android app using the same library not working anymore, because it needs to send multipart form data as "multipart/form-data" and not "multipart/related". I can't keep the jar file I was using since classes exists in couchbase lib, so the only solution was to include the library source code myself with a different package name to be able to use a version with "multipart/form-data". 

I think that couchbase lib should rename the package for it's modified version of httpmime, to let existing apps using httpmime working without modifications.

**Comment by hideki** [comment]
This issue should be solved by #314
