### ISSUE TITLE
Support encryption in ForestDB storage engine

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#811]
ForestDB [Support cross-platform encryption options] (http://review.couchbase.org/#/c/56361/) is still in review.

**Comment by hideki** [comment]
NOTE: This ticket is for cbforest level encryption. Need to work ForestDBStore level encryption integration

**Comment by hideki** [comment]
- PRs for this ticket:
https://github.com/couchbaselabs/couchbase-lite-java-forestdb/pull/16
https://github.com/couchbaselabs/couchbase-lite-java-forestdb/pull/17

- CBForest level test passed

- Further work required for forestdb encryption support: https://github.com/couchbase/couchbase-lite-java-core/issues/827
