### ISSUE TITLE
manager.getDatabase(DB_NAME) returns null

### ISSUE THREAD

**Issue by niravbsoftweb** [couchbase/couchbase-lite-java-core#822]
Hello,

I stuck on blocker issue with retrieving database.

I used manager.getDatabase(DB_NAME) to retrieve instance of database, but it returns null.

Don't have specific steps to reproduce it, but getting issue multiple times.

Help will be appreciated.

**Comment by hideki** [comment]
Hi @niravbsoftweb,

Could you please verify database exist in your application folder by `adb` or Android Device Monitor?
I guess the specified database does not exists.

Thanks!
Hideki

**Comment by niravbsoftweb** [comment]
Yes Hideki,

I have verified it and its exits.

**Comment by niravbsoftweb** [comment]
Attached Screen shot from debug mode, if its help to educate issue.

![db_manager](https://cloud.githubusercontent.com/assets/14075594/11272232/631e9978-8ef1-11e5-83ac-4e9835443134.png)
![managerissue2](https://cloud.githubusercontent.com/assets/14075594/11272236/6aa68430-8ef1-11e5-921f-fdd18978ac44.png)

**Comment by hideki** [comment]
Hi @niravbsoftweb,

From the codes, https://github.com/couchbase/couchbase-lite-java-core/blob/67ba2b0da5937ae2a12a15ca6006534c789859af/src/main/java/com/couchbase/lite/Manager.java#L485-L504, `getDatabase(String name, boolean mustExist)` does not return null except if name is null   or empty, or if mustExists is true and database file does not exists. As your codes uses getDatabae(String name), mustExist is false. So second case is not applied. Please check if database name is null or empty before calling `Manager.getDatabae(String name)`?

If `getDatabase()` return null with proper database name, could you please provide detailed steps to reproduce this problem?

Thanks!
Hideki

**Comment by hideki** [comment]
Note to Self:
- Needs to review codes what might return null.

**Comment by hideki** [comment]
Hi @niravbsoftweb,

I reviewed our codes again,  `Database getDatabase(String name, boolean mustExist)` does not return `null` except the `name` parameter is `null` or `empty`. All other scenarios, the method should throw exception such as `NullPointerException`. Could you please review if the app calls `getDatabase()` method with a proper `name` parameter? 

My team member suggested that app is installed on SD CARD or is moved to SD CARD. And SD CARD is removed or has write protection. Is your app installed on SD CARD? Please check this too.

Thanks!

**Comment by hideki** [comment]
As we did not receive additional information, I will close this ticket. Please let us know if this issue is still reproducible. Thanks!
