### ISSUE TITLE
setMaxRevTreeDepth not working as intended after Compaction is called.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#823]
Hi Folks,

 1)Set DB setMaxRevTreeDepth to 3.
 2)UPSERT a documents 10 times.
 3)Rev size now is 10.
 4)Call Compaction on the DB.

Observed.
in revs table The the old revision ids are maintained and last revision has the json body.
Expected:
only 3 Revisions with with 3 json body. 

   /**
     * Set the maximum depth of a document's revision tree (or, max length of its revision history.)
     * Revisions older than this limit will be deleted during a -compact: operation.
     * Smaller values save space, at the expense of making document conflicts somewhat more likely.
     */
    protected void setMaxRevTreeDepth(int maxRevTreeDepth) {
        if (store != null)
            store.setMaxRevTreeDepth(maxRevTreeDepth);
    }

  /**
     * Compacts the database file by purging non-current JSON bodies, pruning revisions older than
     * the maxRevTreeDepth, deleting unused attachment files, and vacuuming the SQLite database.
     */
    @InterfaceAudience.Public
    public void compact() throws CouchbaseLiteException {
        // Can't delete any rows because that would lose revision tree history.
        // But we can remove the JSON of non-current revisions, which is most of the space.

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java

Thanks
Nithin

**Comment by ddash1** [comment]
* Smaller values save space, at the expense of making document conflicts somewhat more likely.

Need more clarity on how is a smaller value for the maxRevTreeDepth make conflicts more likely?

**Comment by hideki** [comment]
Hi @NitzDKoder,

We have unit test for `setMaxRevTreeDepth()`. And we can not reproduce the problem.
https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/DatabaseTest.java#L21-L42

Can you provide code snippet to reproduce the problem?

**Comment by hideki** [comment]
Additional comment: `setMaxRevTreeDepth()` is not public API.
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/database/database/index.html

With CBL Android v1.1.0, `setMaxRevTreeDepth()` is marked as `public`. However, it is not recommend to use `setMaxRevTreeDepth()`.

**Comment by NitzDKoder** [comment]
@hideki why is it not recommended? https://github.com/couchbase/couchbase-lite-java-core/issues/825 can you help here?

**Comment by hideki** [comment]
@NitzDKoder,

With v1.1.0, default value of max revisions is maximum number of integer. It is not applicable number for app that might have many revisions. 
```private static final int DEFAULT_MAX_REVS = Integer.MAX_VALUE;```
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/Database.java#L74

From v1.2.0, default value is set to 20. And `setMaxRevTreeDepth()` will be **NON-public API**.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L1781

I think around 20 could be reasonable number for app that uses CBL v1.1.0.

Thanks,
Hideki

**Comment by ddash1** [comment]
@hideki 

2 questions:

1. https://forums.couchbase.com/t/version-depth-and-sync-meta-data/4867
From the link, you can see @snej advising to use the Database.maxRevTreeDepth property. Has that understanding changed?
We really do not want to keep more that 1-5 revisions, if possible.

2. If from ver 1.2.0 this is going to be set at 20 by default and this is not a public api, what kind of restrictions we need to have on the max_revs limit on the server side? Do we need to at least have max_revs set to 20 or more?

3. Can you please explain how smaller values can cause more conflicts ?
From https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java
 /**
* Set the maximum depth of a document's revision tree (or, max length of its revision history.)
* Revisions older than this limit will be deleted during a -compact: operation.
<<<<* Smaller values save space, at the expense of making document conflicts somewhat more likely.>>>>
*/
This will help us understand why we need to follow the 20 default depth.

**Comment by hideki** [comment]
Hi @ddash1,

1) `Database.setMaxRevTreeDepth()` method is not documented, and also our internal private API doc does not document it. However, CBL iOS supports it https://github.com/couchbase/couchbase-lite-ios/blob/release/1.2/Source/API/CBLDatabase.m#L234-L245 . It could be public API. I need to verify it.

2) I guess this is documentation error. it should be `public API`.

3)  In scenario of two devices with 3 max rev depth, one device has revision 1, 2 and 3, the other device has revision 5, 6, 7.  When replicating the doc, it could make conflicts.

Thank you very much for your comments!!!

**Comment by hideki** [comment]
Ticket for CBL Android/Java: https://github.com/couchbase/couchbase-lite-java-core/issues/826

**Comment by ddash1** [comment]
@hideki 

Thanks. So setMaxRevTreeDepth() can be public and lets say we use it to set the depth to 20.
For #2 above, what kind of restrictions we need to have on the max_revs limit on the server side? Do we need to at least have max_revs set to 20 or more to avoid sync/conflict issues?

Also, for #3 above, not clear how setting the value to 20(larger vs 3) would avoid conflicts. It just may push it to later in your example. Can you please confirm this understanding is right or wrong?

**Comment by hideki** [comment]
Hi @ddash1 

> For #2 above, what kind of restrictions we need to have on the max_revs limit on the server side? Do we need to at least have max_revs set to 20 or more to avoid sync/conflict issues?

Please see `revsLimit` section of document: http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/sync-gateway/configuring-sync-gateway/config-properties/index.html

- This is also another documentation error, correct name should be **`revs_limit`**.

I believe large enough number that could be good to avoid conflict. It depends on application.

> Also, for #3 above, not clear how setting the value to 20(larger vs 3) would avoid conflicts. It just may push it to later in your example. Can you please confirm this understanding is right or wrong?

During replication, client asks sync gateway if local revision id exists in the server. If not, client pushes these revision. That causes conflict if revision history is missing.

**Comment by hideki** [comment]
Hi @NitzDKoder and @ddash1,
I fixed the Database.compact() issue and sent PR for master branch. If you need fix for v1.1.0, can you apply https://github.com/couchbase/couchbase-lite-java-core/pull/828/files, and build by yourself? This fix will be included in v1.2.0 release.
As original issue was fixed, I will close this ticket.

**Comment by NitzDKoder** [comment]
@hideki 
Tied to make build, below is the code used..

Android jar:
https://github.com/couchbase/couchbase-lite-android

SQLite support .SOs:
https://github.com/couchbase/couchbase-lite-android/tree/master/jniLibs/armeabi

Java core master:

https://github.com/couchbase/couchbase-lite-java-core/tree/master

Not able to load library, any reason?

[11/27 06:20:01.349] [1] Database: Cannot load native library
[11/27 06:20:01.353] [1] Database: Cannot load native library

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder 

Do you have log or stacktrace that indicates which native library can not be loaded?

Recently, we added https://github.com/couchbase/couchbase-lite-java-native as submodule of couchbase-lite-android. (https://github.com/couchbase/couchbase-lite-android/tree/master/libraries )

Please try `git submodule update`?
