### ISSUE TITLE
Compaction impact on replication when rev_limit is enabled.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#825]
Here is the setup:

Client CBL has the setMaxRevTreeDepth set to 3 and sync GW has the revs_limit set to 5. Compaction is set to run every 1 hr on client CBL and every 24 hrs on CB database.

Can somebody clarify what will be the behavior in the below scenarios:
1. The CBL compaction runs every 1 hr and after a day, when the server side compaction has run, we see a push replication is trying to send old revisions form the client to the server. Per our understanding we should not be sending the older revisions. Is this correct behavior?

Lets say for Doc1 :
CBL revision tree = 1-2-3-[4 replaces 1]-[5 replaces 2]-[6 replaces 3]-[7 replaces 4] = 5-6-7
SG-CB revision tree = 1-2-3-4-5-[6 replaces 1]-[7 replaces 2] = 3-4-5-6-7

Client goes offline for couple of hrs. Server side more updates happen:

CBL tree by eod: 5-6-7
SG-CB tree at eod: 8-9-10-11-12
at this time compaction runs on server side along with the hourly compaction run on the CBL.

After this when the push-replicator is invoked we see it reporting:
5 - missing
6 - missing
7 - missing
and the replicator trying to push the 5-6-7 revisions to the sync gw(these revisions were removed as part of compaction and revs_limit setting to 5)

This is causing a document conflict and replication failure. Is this the expected behavior? We were expecting to see it do nothing for a push as the 5-6-7 WAS already there on the server side and had been compacted.

Please advise.
Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder 

We are investigating this scenario. In this scenario, both client and Sync Gateway also involves. It could take time.

For short term solution, Could you please use big enough number for max revs that allows both client and server could have common ancestor revision in both side revision history. 

CBL v1.1.0's default max revs value is maximum number of Integer.  I understand it is too large for your app. Please analyze your application to find out best configuration for your app?

Hope this helps you.

Thanks!
Hideki

**Comment by ddash1** [comment]
@hideki 

How can this make sure both the client and the server have a common ancestor. Please advise.

**Comment by hideki** [comment]
Hi @ddash1,
Suitable number of maxRevsTreeDepth depends on application. If your app frequently updates document, higher value could be good. If your app does not update document frequently, smaller value could be fine.

**Comment by ddash1** [comment]
@hideki 

Can you please advise on the investigation results, if any:
      "We are investigating this scenario. In this scenario, both client and Sync Gateway also involves. It could take time."

**Comment by hideki** [comment]
@ddash1, Sorry I did not have chance to look into this issue yet.

In case `rev_limit` value is too small on Sync Gateway for your application, please use large enough value for `rev_limit`.

**Comment by ddash1** [comment]
@hideki 

I can try the large enough value but what is a large enough value? I don't know. Can you please suggest a large enough value. This may be a workaround for time being.

What I really need to know is: if this scenario is handled for replication after compaction on server side and if so what is the behavior.

**Comment by hideki** [comment]
@ddash1,

It depends on your application. You can try 20, 100, 500, 1K, 5K,.... till find best number to avoid conflict.

However, even though document conflict occurs, the replication should not stop. And the revision that has higher revision ID automatically wins. I assume it should not cause serious problem.

**Comment by ddash1** [comment]
@hideki 

So you agree that document conflict will occur in this scenario.

I think the bulk docs api used in the push replicator should not replicate the compacted revisions at all.

**Comment by hideki** [comment]
> So you agree that document conflict will occur in this scenario.

I am not 100% sure as I did not reproduce this problem yet. But I assume this scenario cause conflict or unexpected behavior.

> I think the bulk docs api used in the push replicator should not replicate the compacted revisions at all.

yes. compacted revision does not exist in database.

**Comment by ddash1** [comment]
Not sure I followed: compacted revision does not exist in database.

Are you confirming that after compaction on server side, the push replicator should not push the compacted revisions back from CBL to Sync GW. If so, thats what we are observing in the logs. So, is this a bug?

**Comment by hideki** [comment]
@ddash1,
I did not confirmed this yet.

comment from server side engineer
```text
I wouldn't have expected the client to try to push 5-6-7 again, if the doc hadn't changed on the client
But if the client has actually never pushed 5-6-7, this is the expected case.  Question would be - do 5-6-7 match server 5-6-7?  If so, how did client obtain?
```

For this case, I expected client does (can) not push revisions.

**Comment by ddash1** [comment]
@hideki 
Ok, lets wait on the investigation results. Thank you for all your help.

On the comment from the server side engineer,
The doc did not change on client side. The document was completely synced prior to the compaction operations. So, 5-6-7 matches on both sides. The client got all the revisions as part of a mutation-sync workflow between the client and the server.

Let me know if I can help anymore with clarifying the scenario.

**Comment by hideki** [comment]
Hi @ddash1 and @NitzDKoder,
Thank you very much for your patience. I am confirming this scenario with our architects. We will answer this as soon as possible.

**Comment by snej** [comment]
@NitzDKoder : 
>the replicator trying to push the 5-6-7 revisions to the sync gw(these revisions were removed as part of compaction and revs_limit setting to 5) This is causing a document conflict and replication failure. Is this the expected behavior?

Yes. Basically you've made the server's revs_limit too small, and the side effect is false conflicts.

>We were expecting to see it do nothing for a push as the 5-6-7 WAS already there on the server side and had been compacted.

But the server doesn't know that it used to have revisions 5,6,7, because its revision history has been pruned and the metadata of those revisions no longer exists in the doc's revision tree.

I think you're mixing up the concepts of _compaction_ and _pruning_. Compaction is when the bodies of obsolete revisions get removed (but their metadata, i.e rev ID and parent rev, remains.) Pruning is when the revision tree itself is edited to remove the  oldest revisions and no trace is left of their metadata.

After compaction, SG still knows that it used to have revisions 5,6,7. After pruning, it doesn't.

**Comment by ddash1** [comment]
@snej 

Thanks for clarifying that. We are doing both pruning and compaction.
So, what is the advised solution to avoid this issue? Go higher revs_limit.
What would be a good number for the revs_limit to avoid the false conflicts assuming a mutation rate of 1 every 15 seconds for a doc.

Thanks

**Comment by hideki** [comment]
Test results with CBL Android `master` branch and Sync Gateway 1.1.1

NOTE: revs_limit = 5 on sync gateway configuration.

Test scenario and results:
```
1. CBL create document and update it twice => Revision history at CBL: [1-xxxx, 2-xxxx, 3-xxxx] and SG []
2. Push document to Sync Gateway => Revision history at CBL: [1-xxxx, 2-xxxx, 3-xxxx] and SG: [1-xxxx, 2-xxxx, 3-xxxx]
3. Update document seven times at Sync Gateway (Update from Admin UI) => Revision history at CBL: [1-xxxx, 2-xxxx, 3-xxxx] and SG: [6-xxxx, 7-xxxx, 8-xxxx, 9-xxxx, 10-xxxx]
4. Push document to Sync Gateway => No Changes to update => Revision history at CBL: [1-xxxx, 2-xxxx, 3-xxxx] and SG: [6-xxxx, 7-xxxx, 8-xxxx, 9-xxxx, 10-xxxx]
5. Pull document from Sync Gateway => Revision history at CBL: [6-xxxx, 7-xxxx, 8-xxxx, 9-xxxx, 10-xxxx] and SG: [6-xxxx, 7-xxxx, 8-xxxx, 9-xxxx, 10-xxxx]
```

In CBL database, eight revision records exist. A parent of 1-xxxx and 6-xxxx is NULL. This is reason `Document.revisionHistory()` methods return [6-xxxx, 7-xxxx, 8-xxxx, 9-xxxx, 10-xxxx]

Test codes: https://github.com/hideki/couchbase-lite-android-test/tree/issues/javacore/825


@NitzDKoder
> This is causing a document conflict and replication failure. Is this the expected behavior? We were expecting to see it do nothing for a push as the 5-6-7 WAS already there on the server side and had been compacted.

From my test result, your expectation is correct. conflict and replication failure should not be caused.

@ddash1 
> I think the bulk docs api used in the push replicator should not replicate the compacted revisions at all.

You are correct. 

Thanks!

**Comment by snej** [comment]
>What would be a good number for the revs_limit to avoid the false conflicts assuming a mutation rate of 1 every 15 seconds for a doc.

Well, it would be (max time you expect a client to be offline between replications) ÷ 15sec.

Updating documents that often isn't really a good fit for a version-tracking system.

**Comment by ddash1** [comment]
@snej 
Thanks Jens. Need advise to understand a fundamental aspect. We are trying to use the CB Mobile stack for updating some user data which is transient and needs frequent updates. Although we can use the CBLite <-> Sync GW Db replication to sync the updates to the server side, are you suggesting that CB Mobile stack is not a good fit for these kind of use cases due to the frequent nature?

**Comment by snej** [comment]
Correct. Because the system tracks the history of all revisions, huge numbers of changes will either cause the bookkeeping data (rev history) to become very large, or cause false conflicts if the doc doesn't remember enough past rev IDs to connect the dots between the local and remote history.

We do plan to improve this in the future. For example, I've been working on a utility library to help with time-series data, where a client generates frequent small data-points that are immutable. It's not magic; the library just collects the data until it has a large enough amount, then generates a single document containing an array of all the data values. This obviously adds latency to the replication, but vastly cuts down the number of docs/revisions. (For example, the device might capture a sensor reading every 5 seconds, but send them to the server in blocks of 1000, i.e. about once an hour.)

Anyway, this is probably better discussed on the Google group or Couchbase forum rather than a bug report…
