### ISSUE TITLE
SQLiteStore not support auto compact

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#840]
Currently SQLiteStore doesn't support auto compact mode. Need to verify if iOS supports it or not.

**Comment by hideki** [comment]
iOS Implementation: https://github.com/couchbase/couchbase-lite-ios/pull/936

**Comment by hideki** [comment]
Note: iOS implementation: SQLiteStore does not support auto compact feature. To be consistent with ForestDB, SQLiteStore supports same method signature. But no implementation.
