### ISSUE TITLE
Cookie is not set for /{db}/_revs_diff with one shot push replication

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#852]
Steps to reproduce
1. Create user and generate Sync Gateway session ID by curl comand
2. Start One Shot Push replication after setting cookie with session ID which is obtained by step 1.
3. /{db}/_revs_diff fails with HTTP 401.

Screen Shot from HttpScoop
<img width="1022" alt="screen shot 2015-12-07 at 11 03 30 pm" src="https://cloud.githubusercontent.com/assets/15889/11649769/518b0c88-9d37-11e5-9129-6494321f6cc2.png">

Sync Gateway Log
```
2015-12-07T23:01:30.241-08:00 Cache: Received #1 ("_user/user1")
2015-12-07T23:01:30.241-08:00 Cache+:   Ignoring duplicate of #1
2015-12-07T23:03:03.373-08:00 HTTP:  #003: GET /db/_local/3cdc24237984c949d114ce7a797562b036e1a7dd  (as user1)
2015-12-07T23:03:03.373-08:00 HTTP: #003:     --> 404 missing  (0.3 ms)
2015-12-07T23:03:03.918-08:00 HTTP:  #004: POST /db/_revs_diff
2015-12-07T23:03:03.918-08:00 HTTP: #004:     --> 401 Login required  (0.2 ms)
```

NOTE: Cookie value is not set only first `/{db}/revs_diff` request. From second request, cookie is set in HTTP header.

**Comment by hideki** [comment]
Note to self:

Flow:
1. In cookie store, SG Session is stored with path, `/db`
2. `/{db}/_local/xxxx` is requested with Session ID. In response from SG, `Set-Cookie` with updated session ID is responded.
3. SG cookie in cookie store is updated with path `/db/_local` because previous request's URL is `/{db}/_local`.
4. `/{db}/_revs_diff` is requested without Session ID as cookie's path and request URL path does not match.

```
12-08 15:11:48.103 22288-23339/self.hideki.cbltestapp E/Sync: [COOKIE STORE]
12-08 15:11:48.107 22288-23339/self.hideki.cbltestapp E/Sync: cookie: [version: 0][name: SyncGatewaySession][value: e799bc375acf65323f47b7a4692787ebfe4d4ced][domain: 10.17.2.82][path: /db][expiry: Tue Dec 08 15:16:48 EST 2015]

12-08 15:11:48.631 22288-23339/self.hideki.cbltestapp E/Sync: [COOKIE STORE]
12-08 15:11:48.631 22288-23339/self.hideki.cbltestapp E/Sync: cookie: [version: 0][name: SyncGatewaySession][value: e799bc375acf65323f47b7a4692787ebfe4d4ced][domain: 10.17.2.82][path: /db/_local][expiry: Tue Dec 08 15:16:47 EST 2015]

12-08 15:11:48.635 22288-23339/self.hideki.cbltestapp E/RemoteRequest: Got error status: 401 for http://10.17.2.82:4984/db/_revs_diff.  Reason: Unauthorized
12-08 15:11:48.635 22288-23339/self.hideki.cbltestapp E/Sync: com.couchbase.lite.replicator.PusherInternal@52886c0c: Progress: set error = org.apache.http.client.HttpResponseException: Unauthorized
12-08 15:11:48.635 22288-22803/self.hideki.cbltestapp E/CBLTestApp: REPLICATION ERROR
```

**Comment by hideki** [comment]
Note to self:

Asterisk `*` for Cookie path can not solve this issue.

**Comment by pasin** [comment]
What is the path value in Set-Cookie? If the path set to `/db/_local`, I'm wondering if iOS will have the same issue. Can you share the captured Set-Cookie header?

**Comment by hideki** [comment]
`Set-Cookie:` does not contain any path. HttpClient set same path with request URL. That causes mis-matching for next request with /db/_revs_diff .
