### ISSUE TITLE
update couchbase maven repo for new names of couchbase-lite-java-forestdb packages for both android and java

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#859]
This ticket depends on #858

**Comment by pasin** [comment]
If jenkins can upload the binary, we could close this issue.

**Comment by pasin** [comment]
Given that couchbase-lite-android is builable on Jenkins server, I'm closing this issue.

http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-master/2/
