### ISSUE TITLE
RevID generated from different API levels may not be the same

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#878]
Unit Test: https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/RevisionsTest.java#L369-L396

Currently the test fails when running on API 19 ARM emulator.

**Comment by snej** [comment]
Weird! I guess this would mean that either

* the JSON canonicalization isn't the same (are dictionary keys not sorting the same way?), or
* the MD5 checksum isn't working right on one or the other (sounds really unlikely since that would make MD5 useless...)

**Comment by hideki** [comment]
ref: #178

**Comment by borrrden** [comment]
FYI .NET solves this by using the `SortedDictionary` class which will order the keys first.  The equivalent in Java seems to be [TreeMap](https://stackoverflow.com/questions/4621464/whats-the-equivalent-to-a-net-sorteddictionary-in-java)

**Comment by hideki** [comment]
Hi @borrrden, CBL .NET does not apply `SortedDictionary` recursively, I believe it should be applied recursively.

**Comment by borrrden** [comment]
@hideki You are probably right, we don't have tests that go that deep.  @snej @pasin Does iOS recursively sort?

**Comment by pasin** [comment]
@borrrden iOS does it recursively.

**Comment by snej** [comment]
Yes, for the JSON to be in canonical form, _every_ object/map/dictionary in it needs to have its keys sorted.

I don't think you need to use a TreeMap for this. What iOS does is just (a) get the keys as an array of strings, (b) sort that array, (c) iterate over the array in order, looking up the matching value for each key.

**Comment by hideki** [comment]
For CBL Java, we uses third-party library (Jackson) to serialize between json and Map. Recreating Map object with TreeMap is expensive if document is large. Also I believe lookup cost of TreeMap is log(N). 

It seems Jackson allows to write own serializer. I will create new ticket and work for efficiently.
https://github.com/couchbase/couchbase-lite-java-core/issues/1465

**Comment by snej** [comment]
Serializing JSON is really easy, except for writing strings (because you have to escape some characters.) And even writing the strings isn't hard.
