### ISSUE TITLE
Check SQLite Sync Mode

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#887]
I'm creating an issue to check what the default Sync Mode on Android is. We should ensure that the Sync mode is set to full to prevent database file corruption.

**Comment by hideki** [comment]
What is Sync Mode?

**Comment by pasin** [comment]
https://www.sqlite.org/pragma.html#pragma_synchronous

By default, synchronous is set to FULL but I would like to make sure that we don't need to explicitly set that.

**Comment by pasin** [comment]
From the documentation, the synchronous mode is FULL by default. I don't think we need to do anything here.
