### ISSUE TITLE
Replication.docIds API discrepency

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#894]
API Spec:
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/replication/replication/index.html#string-docids--get-set-

Java/Android is using docIds per the API documentation however CBL iOS is using documentIDs. However we also have a method like `getPendingDocumentIDs()`. We may need some consistency among APIs and platforms here.

@zgramana could you please review?

**Comment by zgramana** [comment]
See https://github.com/couchbase/couchbase-lite-ios/commit/551ce200035b98c1df396dc3aacc97b0ef6172c5
