### ISSUE TITLE
(getAttachmentStorePath and getContentURL) API to public and attachments folder name?

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#895]
Hi,

 1)Currently getAttachmentStorePath and getContentURL is private , make it public.

 2)Current attachments folder name is db+" attachments".Why is the space needed here.?

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/Database.java
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/Attachment.java

3)As per our test the space in folder name wont work in android FileProvider design.

http://developer.android.com/reference/android/support/v4/content/FileProvider.html

4)Basically we are trying to make Uri For File.

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

> 1)Currently getAttachmentStorePath and getContentURL is private , make it public.

`getContentURL()` will be public from 1.2
https://github.com/couchbase/couchbase-lite-java-core/issues/683

currently no plan to make `getAttachmentStorePath ` to public method

> 2)Current attachments folder name is db+" attachments".Why is the space needed here.?

We will change database directory structure from 1.2

```
/<database name>.cblite2
   /db.sqlite3 or db.forestdb.<info>
  /attachments
      /<file>.blob
```

> 3)As per our test the space in folder name wont work in android FileProvider design.

As described above, we will remove space in attachment directory from v1.2

Happy Holidays!

**Comment by NitzDKoder** [comment]
@hideki thanks..happy holidays..

**Comment by NitzDKoder** [comment]
@hideki 

http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/tech-notes/cbl-encryption/index.html

"No access to attachment files
Generally you retrieve attachments as NSData objects, but Couchbase Lite does provide ways to get the path (or URL) of the file that contains an attachment. If you're doing the latter, it won't work with an encrypted database, because the attachment files themselves are encrypted and not directly readable. Instead, CBLAttachment.contentURL will be nil, and a HEAD call to an attachment URL in the REST API will not include a Location: header that gives the full path of the file.
However, we've added a new way to read large attachments efficiently. The method -[CBLAttachment openContentStream] returns an NSInputStream object through which you can read the decrypted contents of the attachment. Just make sure to close the stream when you're done."


With above design we can not use getContentURL API.. Is there way to make this API work?

We are making FileProvider using the URL to make the content available to 3rd party apps.
http://developer.android.com/reference/android/support/v4/content/FileProvider.html

Thanks
Nithin

**Comment by hideki** [comment]
Hi,

`getContentURL()` return URL to raw data (encrypted data).

After loaded data from the stream, app could save file into the disk, and can return URL to the file?

**Comment by NitzDKoder** [comment]
@hideki when DB is encrpyted..getContentURL()  will be null..
  *** If the database is encrypted, attachment files are also encrypted and not directly readable,
     * so this property will return null.**
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.3.0/src/main/java/com/couchbase/lite/Attachment.java

**After loaded data from the stream, app could save file into the disk, and can return URL to the file?**

This will be overhead right?
  ```
/**
     * Get the input stream of the content (aka 'body') data.
     * @throws CouchbaseLiteException
     */
    @InterfaceAudience.Public
    public InputStream getContent() throws CouchbaseLiteException {
        if (body != null) {
            return body;
        } else {
            return new ByteArrayInputStream(internalAttachment().getContent());
        }
    }
```
From InputStream create as temp file and make file-provider for 3rd party?

**Comment by hideki** [comment]
Hi @NitzDKoder,
`FileProvider` requires URL to file. And encrypted files should be decrypted. With current restrictions, we could not avoid to create un-encrypted file from the input stream.
