### ISSUE TITLE
Views Test failure on Windows when tested with ForestDB Storage Engine

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#900]
```
com.couchbase.lite.RouterTest > testViews FAILED
    junit.framework.AssertionFailedError at RouterTest.java:454

com.couchbase.lite.RouterTest > testTotalRowsAttributeOnViewQuery FAILED
    junit.framework.AssertionFailedError at RouterTest.java:868

com.couchbase.lite.RouterTest > testPostKeysView FAILED
    junit.framework.AssertionFailedError at RouterTest.java:590

com.couchbase.lite.ViewsTest > testIndexMultipleViewsDifferentMaps FAILED
    junit.framework.AssertionFailedError at ViewsTest.java:2736

com.couchbase.lite.ViewsTest > testViewGroupedStrings FAILED
    java.lang.IndexOutOfBoundsException at ViewsTest.java:1290

com.couchbase.lite.ViewsTest > testIndexMultipleViews FAILED
    junit.framework.AssertionFailedError at ViewsTest.java:2649

com.couchbase.lite.ViewsTest > testDocTypes FAILED
    junit.framework.AssertionFailedError at ViewsTest.java:2811
```

**Comment by pasin** [comment]
With the current master of couchbase-lite-java-core, the following Views tests still fail on Windows. All of them fail only with ForestDB Storage Engine but not SQLite Storage Engine.

testIndexMultipleViewsDifferentMaps
testViewGroupedStrings
testIndexMultipleViews
testDocTypes

**Comment by pasin** [comment]
ForestDBViewStore doesn't save views whose name has `/`? For example,

```
View v1 = createView(database, "agroup/view1");
View v2 = createView(database, "other/view2");
View v3 = createView(database, "other/view3");
View vX = createView(database, "other/viewX");
View v4 = createView(database, "view4");
View v5 = createView(database, "view5");

List<View> views = database.getAllViews()
// views contains only v4 and v5.
```

**Comment by pasin** [comment]
I guessed the real issue is probably about the file or directory name associated with the view name containing `/` character. See the following code when getting all view names:

```
public List<String> getAllViewNames() {
        List<String> result = new ArrayList<String>();
        String[] fileNames = new File(directory).list();
        for(String filename : fileNames){
            String viewName = ForestDBViewStore.fileNameToViewName(filename);
            if(viewName != null)
                result.add(viewName);
        }
        return result;
    }
```

**Comment by hideki** [comment]
@pasin, Thank you for investigating this issue.

**Comment by pasin** [comment]
In ForestDBViewStore, when creating a view, it will replace `/` character in the view name with `:` and use the new view name to construct the view index file path. Windows doesn't allow any of those characters: `\ / : * ? " < > |` in the file name. As a result, the store cannot create the index file.

@hideki could you please fix this? @borrrden do you have this issue on .NET (probably not as .NET code also replaces `/` with `:`)?

**Comment by pasin** [comment]
Another issue, when the View Store cannot create the index file, it doesn't return or throw an error.

**Comment by hideki** [comment]
Fixed with PR https://github.com/couchbaselabs/couchbase-lite-java-forestdb/pull/38
