### ISSUE TITLE
forestdb Transaction Error on Linux

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#902]
During `ReplicationInternalTest. testOneShotPullReplBulkGetWith404` on Linux, null transaction error occurs.

> [ERROR] [system.err] java: /home/hideki/github/couchbase-lite-java/libraries/couchbase-lite-java-forestdb/vendor/cbforest/C/c4Database.cc:103: forestdb::Transaction *c4Database::transaction(): Assertion `_transaction' failed.

Log: https://gist.github.com/hideki/1fd28b3c1db29a047596

According to jens, this could be caused by accessing forestdb from multiple threads simultaneously.
> Is it possible you're accidentally calling the same C4Database from multiple threads? So far that's the only way I can see for this to happen.

**Comment by hideki** [comment]
Note to Self

`ReplicationInternalTest.testOneShotPullReplBulkGetWith404()` was added recently.  

https://github.com/couchbase/couchbase-lite-android/blob/27a7dab0021285b4e66900bc797e46c5eb8a7842/src/androidTest/java/com/couchbase/lite/replicator/ReplicationInternalTest.java#L423

**Comment by snej** [comment]
The way ForestDB is being called in Java is not thread-safe. This is a big problem, a blocker for 1.2. We can't ship a release that's subject to random race-condition bugs.

Either the CBL Java code needs to synchronize its access to the ForestDB wrappers, or those Java wrapper methods need to be synchronized, or the C++ c4_xxx API functions need to use mutexes.

**Comment by hideki** [comment]
Hi @snej,

I am currently considering to wrap forestdb transaction by java synchronization to make sure forestdb transaction is thread-safe.

ForestDBStore.java`
- `runInTransaction(TransactionalTask task)`
- `inTransaction(Task task)`
- transaction block in `public RevisionInternal add(String inDocID,
                                 String inPrevRevID,
                                 Map<String, Object> properties,
                                 boolean deleting,
                                 boolean allowConflict,
                                 StorageValidation validationBlock,
                                 Status outStatus)`

https://github.com/couchbaselabs/couchbase-lite-java-forestdb/commit/0c33467539305cf357a9ba7bad2ffd68a101030c

**Comment by snej** [comment]
That will only fix the problem if _every_ call to C4Database is made in a transaction, and from looking at the code I don't think that's the case; only the write operations use transactions.

In other words, this isn't just a transaction problem. C4Database is not thread-safe and two threads cannot call it simultaneously.

**Comment by hideki** [comment]
Note to Self:

Dead-lock with cbforest thread-safety or null transaction error is caused by calling `ForstDBStore.beginTransaction()` and `ForestDBStore.endTransaction()`methods not in ordered from two threads. One is from WorkExecutor thread, another one is from RequestWorker which is remote request thread.  

```
com.couchbase.lite.replicator.ReplicationInternalTest > testContPullReplBulkGetWith404 STANDARD_OUT
	beginTransaction() thread: Id => 181, Name => CBLRequestWorker-b0107-0

com.couchbase.lite.replicator.ReplicationInternalTest > testContPullReplBulkGetWith404 STANDARD_OUT
	beginTransaction() thread: Id => 180, Name => CBLManagerWorkExecutor

com.couchbase.lite.replicator.ReplicationInternalTest > testContPullReplBulkGetWith404 STANDARD_OUT
	endTransaction() threadId=181
```

With backtrace for `beginTransaction()`
https://gist.github.com/hideki/a826403e9d80abaa67b2
