### ISSUE TITLE
Run functional tests on SG

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#908]
### Android 1.1 with sync_gateway 1.2
- [x] try release/1.1.0 with sync_gateway 1.2

### Android 1.2 with sync_gateway 1.1
- [x] try release/1.2.0-sqlite with sync_gateway 1.1
- [x] try release/1.2.0-sqlite-custom with sync_gateway 1.1
- [x] try release/1.2.0-sqlcipher with sync_gateway 1.1
- [x] try release/1.2.0-forestdb with sync_gateway 1.1
- [x] try release/1.2.0-forestdb-encrypt with sync_gateway 1.1

### Android 1.2 with sync_gateway 1.2
- [x] try release/1.2.0-sqlite with sync_gateway 1.2
- [x] try release/1.2.0-sqlite-custom with sync_gateway 1.2
- [x] try release/1.2.0-sqlcipher with sync_gateway 1.2
- [x] try release/1.2.0-forestdb with sync_gateway 1.2
- [x] try release/1.2.0-forestdb-encrypt with sync_gateway 1.2

**Comment by hideki** [comment]
I created all flavor of LiteServ Android

https://github.com/couchbase/couchbase-lite-android-liteserv
- release/1.2.0-sqlite
- release/1.2.0-sqlite-custom
- release/1.2.0-sqlcipher
- release/1.2.0-forestdb
- release/1.2.0-forestdb-encryption

Notes:
- Needs to uninstall application before switching storage type. They share same database name, encrypted database can not be opened by non-encryption support engine.
- They does not requires submodule update.

**Comment by andreibaranouski** [comment]
hi, do I need to test release/1.1.1 or release/1.1.0 when you say sync_gateway 1.1?

**Comment by hideki** [comment]
I think release/1.1.1 is fine.

**Comment by andreibaranouski** [comment]
found only one new issue with the following configuration: 
LiteServ Android 1.2.0-forestdb + SG release/1.1.1 https://github.com/couchbase/sync_gateway/issues/1509

**Comment by hideki** [comment]
Hi @andreibaranouski,
Is couchbase/sync_gateway#1509 Couchbase Lite Android issue? or SyncGateway issue?

**Comment by andreibaranouski** [comment]
#1509 is SG issue in release 1.1. it was fixed in 1.2 SG
