### ISSUE TITLE
Utils.headersToMap returns a case-sensitive map

### ISSUE THREAD

**Issue by paddlefish** [couchbase/couchbase-lite-java-core#917]
The HTTP specification (http://www.w3.org/Protocols/rfc2616/rfc2616.txt) in Section 4.2 Message Headers shows that HTTP headers are case-insensitive:
```
Field names are case-insensitive
```
In couchbase-lite for Android (version 1.1.0) the implementation of Utils.headersToMap uses a HashMap, which is Case-Sensitive.  Many call sites look for headers in the map using standard Map APIs, for example, in MultipartDocumentReader.java:
```
        String contentType = headers.get("Content-Type");
        if(contentType.startsWith("multipart/")){
```
If a sync peer returns a content-type header in another case variation, the header will not be found.  Furthermore, as this example shows, it will subsequently cause a NullPointerException when calling the method startsWith() on a null object.

Steps:
* Create a couchdb database and add a document, and add an attachment.
* Replicate to Android using couchbase lite

Result:
* NullPointerException in MultipartDocumentReader.java

Expected:
* Successful replication

Note: I will provide a PR with a fix.

**Comment by hideki** [comment]
Hi @paddlefish,

Thank you for your report. 

What version of CouchDB are you using? 1.6? We tested Couchbase Lite for Android against CouchDB 1.6. I wonder why you encounter the problem.

Thanks,
Hideki

**Comment by paddlefish** [comment]
It looks like I was using couchdb version 1.5. Perhaps couchdb 1.5 uses lower case content-type header.  This may be not-preferred, but it is definitely allowed by the spec.
