### ISSUE TITLE
Push Replicator hangs under certain condition

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#941]
Steps to reproduce:
1. Create 1000 docs on CouchDB/Sync Gateway
2. Start to pull docs from server.
3. During middle of pull replication, create another 1000 docs *without* using transaction. 
4. Check if 2000 documents exist in local database.
5. Start push replication
5. Middle of push replication, push replication hangs

Hangs in `PushInternal.waitIfPaused()` method
```java
    private void waitIfPaused(){
        while (paused) {
            Log.v(Log.TAG, "Waiting: " + paused);
            synchronized (pausedObj) {
                try {
                    pausedObj.wait();
                } catch (InterruptedException e) {
                }
            }
        }
    }
```

NOTEs: 
- If steps 3 uses Transaction to insert, this issue does not occur.
- Storage type (sqlite or forestdb) does not matter.
- Server type (CouchDB or Sync Gateway) does not matter.

**Comment by pasin** [comment]
This could be similar to what I fixed in the other place while fixing batcher. The paused variable doesn't get synchronized.

**Comment by pasin** [comment]
For more info, see waitIfPaused fix in here:

https://github.com/couchbase/couchbase-lite-java-core/pull/906/files
