### ISSUE TITLE
Test CBL Android 1.2 zip file distribution

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#944]
- [ ] couchbase-lite-andriod
- [ ] couchbase-lite-java-listener

**Comment by pasin** [comment]
@michaelkwok and @hideki 

Do we need cbl_collator_so-1.2.0-14.jar in the zip file?

**Comment by pasin** [comment]
Also Can we remove .pom files from the zip file?

**Comment by pasin** [comment]
@hideki If I want to check only couchbase-lite-android, what are the jar files that I don't need?

**Comment by hideki** [comment]
Required jars:
- couchbase-lite-android-xxx.aar
- couchbase-lite-android-sqlite-default-xxx.aar
- couchbase-lite-java-core-xxx.jar
- jackson-annotations-2.5.0.jar <-- this might not be required
- jackson-core-2.5.0.jar
- jackson-databind-2.5.0.jar
- stateless4j-2.4.0.jar

Not required:
- All others

**Comment by hideki** [comment]
We could remove all *.pom files and cbl_collator_so-xxx.jar

**Comment by pasin** [comment]
Here are the list of the files that I think we don't need to include the jar files:

- couchbase-lite-android-1.2.0-14.jar
- cbl_collator_so-1.2.0-14.jar
- *.pom

**Comment by pasin** [comment]
We should include README at least to tell what files are required for Android and what requires for listener.

**Comment by jamiltz** [comment]
From what I remember, the 1.1 release didn't require to add .aar libraries. This [blog post](http://life.nimbco.com/referencing-local-aar-files-with-android-studios-new-gradle-based-build-system/) was helpful to figure out how to include them. Out of curiosity, why is the .aar file type used for those 2 components?

**Comment by hideki** [comment]
AAR is generated automatically as project target is Android.

I have thought AAR is more compressed than JAR.
But It seems I am wrong:
- couchbase-lite-android-1.2.0-14.aar -> 752KB
- couchbase-lite-android-1.2.0-14.jar -> 10KB

We should review this after 1.2.0 release.

**Comment by jamiltz** [comment]
I took a look in couchbase-lite-android-sqlite-default and I see jni's for different architectures. Does it mean that it can run on the various supported platforms (OSX, Windows...) with a single AAR file?
![image](https://cloud.githubusercontent.com/assets/2589337/12565340/91d615f0-c3cd-11e5-8c6d-9ac1068b1cc1.png)

**Comment by hideki** [comment]
Hi @jamiltz,

It indicates CBL Android support 7 architectures of Android phone.


CBL Java supports OSX, Windows, and Linux

**Comment by jamiltz** [comment]
Very nice! Super great feature.
