### ISSUE TITLE
NPE in ManagerTest.testClose() on Nexus 9

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#959]
- This is currently only observed with Nexus 9.
- Not obserbable with other devices
- branch: release/1.2.0

```
01-27 23:30:28.746 15400-15594/com.couchbase.lite.test E/AndroidRuntime: FATAL EXCEPTION: ChangeTracker-http://localhost:60912/db
 Process: com.couchbase.lite.test, PID: 15400
 java.lang.NullPointerException: Attempt to invoke virtual method 'com.couchbase.lite.Manager com.couchbase.lite.Database.getManager()' on a null object reference
     at com.couchbase.lite.replicator.PullerInternal.getUserAgent(PullerInternal.java:1122)
     at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:265)
     at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228)
     at java.lang.Thread.run(Thread.java:818)
```

**Comment by DanGDroid** [comment]
i got the same with LG-g2 running android Lolipop

**Comment by hideki** [comment]
By fixing couchbase/couchbase-lite-android/issues/773, NPE is no longer observable. However still `ManagerTest.testClose()` fails.

Note: Need to fix this line: https://github.com/couchbase/couchbase-lite-android/blob/10966b386102269d4c0d9871046bb8a94a053c79/src/androidTest/java/com/couchbase/lite/ManagerTest.java#L375

**Comment by hideki** [comment]
I believe PR (https://github.com/couchbase/couchbase-lite-java-core/pull/1027) also addressed this issue. I will close this ticket.
