### ISSUE TITLE
ReplicationTest failure on Windows by non-closed InputStream

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#961]
Test code can not delete Database folder on Windows. It causes Replication Test failure on Windows.

This caused by not closing InputStream for push attachment. Recently we switched from File to InputStream for attachment. But code does not close InputStream properly. 

This is not only Windows problem. It also cause File Descriptor leak on other platforms.

**Comment by orenyodfat** [comment]
There is also similar issue on Android
