### ISSUE TITLE
Cannot pull changes after sync_gateway goes offline, then online

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#963]
I am testing TodoLite Android

1. I create a list and share it between 2 devices
2. I add a few task as see that they are shared correctly
3. I take the db offline via :4985/db/_offline
```
curl -X POST http://localhost:4985/todos/_offline
```
4. I add a few tasks on one client
5. I take the db online via :4985/db/_online
```
curl -X POST http://localhost:4985/todos/_online
```

Expected: I would expect the offline tasks to get pushed to sync_gateway and pulled to the other device.

Actual: Offline tasks do not replicate to the other device.

**Comment by sethrosetter** [comment]
Push works fine, seem to be an issue with pulling.

**Comment by ashvindersingh** [comment]
Is it possible if this related with https://github.com/couchbase/sync_gateway/issues/1527

**Comment by sethrosetter** [comment]
@ashvindersingh no. The _offline call in this case is successful and there is no blocking. The issue is related to bringing the db back online. The client does not wake up as expected.

**Comment by pasin** [comment]
I saw similar behavior when testing this case with ToDoLite-iOS. It also depends on time between online and offline. Push and Pull replicator have their own retry logic. Pull replicator is a bit more complicated as its change tracker also has its own retry cycle. We should check if the error status when the pull replicator stopped (I think it should be either 503 or 401). There might or might not be a bug in the retry logic. Need more investigation.

Note that either ToDoLite-iOS or Android doesn't handle 401 error case properly - it should reauthenticate when the error returned from the replicator is 401.

**Comment by sethrosetter** [comment]
@pasin If it helps, I tried with GrocerySync-Android as well with the same behavior. This issue seems unrelated to auth.

**Comment by snej** [comment]
The iOS version explicitly suspends the replicator when the app is backgrounded, and resumes it when foregrounded.

**Comment by zgramana** [comment]
Online/offline here refers to a SG database going offline/online.

**Comment by zgramana** [comment]
@hideki do you have a fix in progress, or at least in mind?

**Comment by hideki** [comment]
Note to Self:

- Once SG becomes offline mode, Client switches to send `POST http://10.17.2.82:4984/db/_changes` twice. Then SG returns 503, then client gave up. Never retry again.

![screen shot 2016-01-29 at 1 48 56 pm](https://cloud.githubusercontent.com/assets/15889/12689040/0f730892-c68f-11e5-97c1-58b9d9641d6c.png)

**Comment by hideki** [comment]
Note to self:

One of problems: In case of error, response from SG is not JSON Array. But ChangeTracker expects JSON Array, it causes infinite loop.

Response:
```
{"error":"Service Unavailable","reason":"DB is currently under maintenance"}
```

Code:
```java
Log.v(Log.TAG_CHANGE_TRACKER, "%s: readValue (oneshot)", this);
JsonFactory factory = new JsonFactory();
JsonParser jp = factory.createParser(inputStream);
while (jp.nextToken() != JsonToken.START_ARRAY) {
   // ignore these tokens
}
```
https://github.com/couchbase/couchbase-lite-java-core/blob/d704e12d973a1dcd763dd897ad34f0fee3950b5f/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L384

**Comment by sethrosetter** [comment]
@hideki tested with GrocerySync using 89039a10b0ccfc5e84ecf6b04bb96a24831b443f. The issue appears to be resolved.

Test steps:
1. Deployed grocery sync to and emulator and device using CBLite Android 1.2.0-30
2. Pointed at 1.2.0 sync_gateway + CBS 4.1.0
3. Added a few item. Verified that they replicated
4. Took grocery-sync db offline
5. Added 3 items on each deployment
6. Took grocery-sync db online
7. After a few seconds (due to transient error backoff), replication awoke, and all of the items sync'ed.

**Comment by hideki** [comment]
@sethrosetter Thank you very much for your verification!
