### ISSUE TITLE
Continuous pull replication not resuming when peer device goes offline/online

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#970]
Here’s the project that will reproduce the issue. Use 2 devices, input IP of device 2 in device 1 then click start pull which will start a continuous pull. Take device 2 offline, add docs, bring back online, the count of device 1 won’t update (the pull replication doesn’t resume) http://cl.ly/1a1V1s3B413a

**Comment by hideki** [comment]
Note To Self: 

Condition: Peer to Peer, One device pull replicate from other device.

Receiver side can not detect connection error by ChangeTracker.

**Comment by hideki** [comment]
Note to self:

ChangeTracker waits for 5min to detect SocketTime. And it can not receive Connection Error
https://gist.github.com/hideki/803a8d2bd226cfb13cdf

Currently default Socket Timeout value is 5min. 
https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#setSoTimeout(int)

https://github.com/couchbase/couchbase-lite-java-core/blob/f7f1cd4320f66d77bcd796cad7b0939fe0c53838/src/main/java/com/couchbase/lite/support/CouchbaseLiteHttpClientFactory.java#L46

For 1.2 solution
- Change Default value to 90 sec.
- Make it configurable.

**Comment by hideki** [comment]
I believe 5min SocketTimeout configuration comes from initial value of heart-beat. Changing default value of SocketTimeout to 90 sec could introduce another problem.

Currently DEFAULT_SO_TIMEOUT_SECONDS is configurable because it is `public static int`. Please modify this value directly.
https://github.com/couchbase/couchbase-lite-java-core/blob/f7f1cd4320f66d77bcd796cad7b0939fe0c53838/src/main/java/com/couchbase/lite/support/CouchbaseLiteHttpClientFactory.java#L46

**Comment by hideki** [comment]
Hi @ jamiltz,
If simply modifying `DEFAULT_SO_TIMEOUT_SECONDS ` value address the problem, please close this ticket. If you still have issue, please let us know.
Thanks!

**Comment by jamiltz** [comment]
I've tried running the change in the sample app and it works. But there are unexpected behaviour in a larger app that's using the Listener to do CRUD operations on the database. I've added the code:

```
			CouchbaseLiteHttpClientFactory clientFactory = new CouchbaseLiteHttpClientFactory(database.getPersistentCookieStore());
//			clientFactory.DEFAULT_SO_TIMEOUT_SECONDS = 10;
//			clientFactory.DEFAULT_CONNECTION_TIMEOUT_SECONDS = 10;
			manager.setDefaultHttpClientFactory(clientFactory);
```

I can see the requests made to the Listener but no responses. It's as if the Listener just closes the connection (even when I comment out the lines to set the DEFAULT values). Is there something I'm doing wrong?

**Comment by jamiltz** [comment]
My bad, I had messed around with the project. It's working great! Thanks! \O/

**Comment by hideki** [comment]
Hi @jamiltz 

FYI: Following code before starting replicator is good enough. So you can avoid to set DefaultHttpClientFactory for this issue.
```
CouchbaseLiteHttpClientFactory. DEFAULT_SO_TIMEOUT_SECONDS = 10; 
```
